// Code generated by ent, DO NOT EDIT.

package credential

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the credential type in the database.
	Label = "credential"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPrincipalID holds the string denoting the principal_id field in the database.
	FieldPrincipalID = "principal_id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldIdentifier holds the string denoting the identifier field in the database.
	FieldIdentifier = "identifier"
	// FieldSecretHash holds the string denoting the secret_hash field in the database.
	FieldSecretHash = "secret_hash"
	// FieldPublicKey holds the string denoting the public_key field in the database.
	FieldPublicKey = "public_key"
	// FieldKeyAlgorithm holds the string denoting the key_algorithm field in the database.
	FieldKeyAlgorithm = "key_algorithm"
	// FieldKeyID holds the string denoting the key_id field in the database.
	FieldKeyID = "key_id"
	// FieldWebauthnCredentialID holds the string denoting the webauthn_credential_id field in the database.
	FieldWebauthnCredentialID = "webauthn_credential_id"
	// FieldWebauthnPublicKey holds the string denoting the webauthn_public_key field in the database.
	FieldWebauthnPublicKey = "webauthn_public_key"
	// FieldWebauthnAaguid holds the string denoting the webauthn_aaguid field in the database.
	FieldWebauthnAaguid = "webauthn_aaguid"
	// FieldWebauthnSignCount holds the string denoting the webauthn_sign_count field in the database.
	FieldWebauthnSignCount = "webauthn_sign_count"
	// FieldScopes holds the string denoting the scopes field in the database.
	FieldScopes = "scopes"
	// FieldActive holds the string denoting the active field in the database.
	FieldActive = "active"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldRevoked holds the string denoting the revoked field in the database.
	FieldRevoked = "revoked"
	// FieldRevokedAt holds the string denoting the revoked_at field in the database.
	FieldRevokedAt = "revoked_at"
	// FieldRevokedReason holds the string denoting the revoked_reason field in the database.
	FieldRevokedReason = "revoked_reason"
	// FieldLastUsedAt holds the string denoting the last_used_at field in the database.
	FieldLastUsedAt = "last_used_at"
	// FieldLastUsedIP holds the string denoting the last_used_ip field in the database.
	FieldLastUsedIP = "last_used_ip"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgePrincipal holds the string denoting the principal edge name in mutations.
	EdgePrincipal = "principal"
	// Table holds the table name of the credential in the database.
	Table = "sf_credentials"
	// PrincipalTable is the table that holds the principal relation/edge.
	PrincipalTable = "sf_credentials"
	// PrincipalInverseTable is the table name for the Principal entity.
	// It exists in this package in order to avoid circular dependency with the "principal" package.
	PrincipalInverseTable = "sf_principals"
	// PrincipalColumn is the table column denoting the principal relation/edge.
	PrincipalColumn = "principal_id"
)

// Columns holds all SQL columns for credential fields.
var Columns = []string{
	FieldID,
	FieldPrincipalID,
	FieldType,
	FieldIdentifier,
	FieldSecretHash,
	FieldPublicKey,
	FieldKeyAlgorithm,
	FieldKeyID,
	FieldWebauthnCredentialID,
	FieldWebauthnPublicKey,
	FieldWebauthnAaguid,
	FieldWebauthnSignCount,
	FieldScopes,
	FieldActive,
	FieldExpiresAt,
	FieldRevoked,
	FieldRevokedAt,
	FieldRevokedReason,
	FieldLastUsedAt,
	FieldLastUsedIP,
	FieldName,
	FieldMetadata,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultWebauthnSignCount holds the default value on creation for the "webauthn_sign_count" field.
	DefaultWebauthnSignCount uint32
	// DefaultScopes holds the default value on creation for the "scopes" field.
	DefaultScopes []string
	// DefaultActive holds the default value on creation for the "active" field.
	DefaultActive bool
	// DefaultRevoked holds the default value on creation for the "revoked" field.
	DefaultRevoked bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Type defines the type for the "type" enum field.
type Type string

// Type values.
const (
	TypePassword     Type = "password"
	TypeAPIKey       Type = "api_key"
	TypeKeypair      Type = "keypair"
	TypeWebauthn     Type = "webauthn"
	TypeTotp         Type = "totp"
	TypeClientSecret Type = "client_secret"
)

func (_type Type) String() string {
	return string(_type)
}

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type Type) error {
	switch _type {
	case TypePassword, TypeAPIKey, TypeKeypair, TypeWebauthn, TypeTotp, TypeClientSecret:
		return nil
	default:
		return fmt.Errorf("credential: invalid enum value for type field: %q", _type)
	}
}

// OrderOption defines the ordering options for the Credential queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPrincipalID orders the results by the principal_id field.
func ByPrincipalID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrincipalID, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByIdentifier orders the results by the identifier field.
func ByIdentifier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdentifier, opts...).ToFunc()
}

// BySecretHash orders the results by the secret_hash field.
func BySecretHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSecretHash, opts...).ToFunc()
}

// ByPublicKey orders the results by the public_key field.
func ByPublicKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicKey, opts...).ToFunc()
}

// ByKeyAlgorithm orders the results by the key_algorithm field.
func ByKeyAlgorithm(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKeyAlgorithm, opts...).ToFunc()
}

// ByKeyID orders the results by the key_id field.
func ByKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKeyID, opts...).ToFunc()
}

// ByWebauthnAaguid orders the results by the webauthn_aaguid field.
func ByWebauthnAaguid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWebauthnAaguid, opts...).ToFunc()
}

// ByWebauthnSignCount orders the results by the webauthn_sign_count field.
func ByWebauthnSignCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWebauthnSignCount, opts...).ToFunc()
}

// ByActive orders the results by the active field.
func ByActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActive, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByRevoked orders the results by the revoked field.
func ByRevoked(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevoked, opts...).ToFunc()
}

// ByRevokedAt orders the results by the revoked_at field.
func ByRevokedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevokedAt, opts...).ToFunc()
}

// ByRevokedReason orders the results by the revoked_reason field.
func ByRevokedReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevokedReason, opts...).ToFunc()
}

// ByLastUsedAt orders the results by the last_used_at field.
func ByLastUsedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastUsedAt, opts...).ToFunc()
}

// ByLastUsedIP orders the results by the last_used_ip field.
func ByLastUsedIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastUsedIP, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPrincipalField orders the results by principal field.
func ByPrincipalField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPrincipalStep(), sql.OrderByField(field, opts...))
	}
}
func newPrincipalStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PrincipalInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PrincipalTable, PrincipalColumn),
	)
}
