// Code generated by ent, DO NOT EDIT.

package serviceaccountkeypair

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the serviceaccountkeypair type in the database.
	Label = "service_account_key_pair"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldServiceAccountID holds the string denoting the service_account_id field in the database.
	FieldServiceAccountID = "service_account_id"
	// FieldKeyID holds the string denoting the key_id field in the database.
	FieldKeyID = "key_id"
	// FieldKeyType holds the string denoting the key_type field in the database.
	FieldKeyType = "key_type"
	// FieldAlgorithm holds the string denoting the algorithm field in the database.
	FieldAlgorithm = "algorithm"
	// FieldPublicKeyPem holds the string denoting the public_key_pem field in the database.
	FieldPublicKeyPem = "public_key_pem"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldActive holds the string denoting the active field in the database.
	FieldActive = "active"
	// FieldLastUsedAt holds the string denoting the last_used_at field in the database.
	FieldLastUsedAt = "last_used_at"
	// FieldRevoked holds the string denoting the revoked field in the database.
	FieldRevoked = "revoked"
	// FieldRevokedAt holds the string denoting the revoked_at field in the database.
	FieldRevokedAt = "revoked_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeServiceAccount holds the string denoting the service_account edge name in mutations.
	EdgeServiceAccount = "service_account"
	// Table holds the table name of the serviceaccountkeypair in the database.
	Table = "sf_service_account_key_pairs"
	// ServiceAccountTable is the table that holds the service_account relation/edge.
	ServiceAccountTable = "sf_service_account_key_pairs"
	// ServiceAccountInverseTable is the table name for the ServiceAccount entity.
	// It exists in this package in order to avoid circular dependency with the "serviceaccount" package.
	ServiceAccountInverseTable = "sf_service_accounts"
	// ServiceAccountColumn is the table column denoting the service_account relation/edge.
	ServiceAccountColumn = "service_account_id"
)

// Columns holds all SQL columns for serviceaccountkeypair fields.
var Columns = []string{
	FieldID,
	FieldServiceAccountID,
	FieldKeyID,
	FieldKeyType,
	FieldAlgorithm,
	FieldPublicKeyPem,
	FieldExpiresAt,
	FieldActive,
	FieldLastUsedAt,
	FieldRevoked,
	FieldRevokedAt,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// KeyIDValidator is a validator for the "key_id" field. It is called by the builders before save.
	KeyIDValidator func(string) error
	// PublicKeyPemValidator is a validator for the "public_key_pem" field. It is called by the builders before save.
	PublicKeyPemValidator func(string) error
	// DefaultActive holds the default value on creation for the "active" field.
	DefaultActive bool
	// DefaultRevoked holds the default value on creation for the "revoked" field.
	DefaultRevoked bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// KeyType defines the type for the "key_type" enum field.
type KeyType string

// KeyTypeRsa is the default value of the KeyType enum.
const DefaultKeyType = KeyTypeRsa

// KeyType values.
const (
	KeyTypeRsa KeyType = "rsa"
	KeyTypeEc  KeyType = "ec"
)

func (kt KeyType) String() string {
	return string(kt)
}

// KeyTypeValidator is a validator for the "key_type" field enum values. It is called by the builders before save.
func KeyTypeValidator(kt KeyType) error {
	switch kt {
	case KeyTypeRsa, KeyTypeEc:
		return nil
	default:
		return fmt.Errorf("serviceaccountkeypair: invalid enum value for key_type field: %q", kt)
	}
}

// Algorithm defines the type for the "algorithm" enum field.
type Algorithm string

// AlgorithmRS256 is the default value of the Algorithm enum.
const DefaultAlgorithm = AlgorithmRS256

// Algorithm values.
const (
	AlgorithmRS256 Algorithm = "RS256"
	AlgorithmRS384 Algorithm = "RS384"
	AlgorithmRS512 Algorithm = "RS512"
	AlgorithmES256 Algorithm = "ES256"
	AlgorithmES384 Algorithm = "ES384"
	AlgorithmES512 Algorithm = "ES512"
)

func (a Algorithm) String() string {
	return string(a)
}

// AlgorithmValidator is a validator for the "algorithm" field enum values. It is called by the builders before save.
func AlgorithmValidator(a Algorithm) error {
	switch a {
	case AlgorithmRS256, AlgorithmRS384, AlgorithmRS512, AlgorithmES256, AlgorithmES384, AlgorithmES512:
		return nil
	default:
		return fmt.Errorf("serviceaccountkeypair: invalid enum value for algorithm field: %q", a)
	}
}

// OrderOption defines the ordering options for the ServiceAccountKeyPair queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByServiceAccountID orders the results by the service_account_id field.
func ByServiceAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServiceAccountID, opts...).ToFunc()
}

// ByKeyID orders the results by the key_id field.
func ByKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKeyID, opts...).ToFunc()
}

// ByKeyType orders the results by the key_type field.
func ByKeyType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKeyType, opts...).ToFunc()
}

// ByAlgorithm orders the results by the algorithm field.
func ByAlgorithm(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlgorithm, opts...).ToFunc()
}

// ByPublicKeyPem orders the results by the public_key_pem field.
func ByPublicKeyPem(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicKeyPem, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByActive orders the results by the active field.
func ByActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActive, opts...).ToFunc()
}

// ByLastUsedAt orders the results by the last_used_at field.
func ByLastUsedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastUsedAt, opts...).ToFunc()
}

// ByRevoked orders the results by the revoked field.
func ByRevoked(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevoked, opts...).ToFunc()
}

// ByRevokedAt orders the results by the revoked_at field.
func ByRevokedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevokedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByServiceAccountField orders the results by service_account field.
func ByServiceAccountField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newServiceAccountStep(), sql.OrderByField(field, opts...))
	}
}
func newServiceAccountStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ServiceAccountInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ServiceAccountTable, ServiceAccountColumn),
	)
}
