// Code generated by ent, DO NOT EDIT.

package listing

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the listing type in the database.
	Label = "listing"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatorOrgID holds the string denoting the creator_org_id field in the database.
	FieldCreatorOrgID = "creator_org_id"
	// FieldOwnerID holds the string denoting the owner_id field in the database.
	FieldOwnerID = "owner_id"
	// FieldProductType holds the string denoting the product_type field in the database.
	FieldProductType = "product_type"
	// FieldProductID holds the string denoting the product_id field in the database.
	FieldProductID = "product_id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldPricingModel holds the string denoting the pricing_model field in the database.
	FieldPricingModel = "pricing_model"
	// FieldPriceCents holds the string denoting the price_cents field in the database.
	FieldPriceCents = "price_cents"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldPublishedAt holds the string denoting the published_at field in the database.
	FieldPublishedAt = "published_at"
	// EdgeCreatorOrg holds the string denoting the creator_org edge name in mutations.
	EdgeCreatorOrg = "creator_org"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// EdgeLicenses holds the string denoting the licenses edge name in mutations.
	EdgeLicenses = "licenses"
	// Table holds the table name of the listing in the database.
	Table = "sf_listings"
	// CreatorOrgTable is the table that holds the creator_org relation/edge.
	CreatorOrgTable = "sf_listings"
	// CreatorOrgInverseTable is the table name for the Organization entity.
	// It exists in this package in order to avoid circular dependency with the "organization" package.
	CreatorOrgInverseTable = "sf_organizations"
	// CreatorOrgColumn is the table column denoting the creator_org relation/edge.
	CreatorOrgColumn = "creator_org_id"
	// OwnerTable is the table that holds the owner relation/edge.
	OwnerTable = "sf_listings"
	// OwnerInverseTable is the table name for the Principal entity.
	// It exists in this package in order to avoid circular dependency with the "principal" package.
	OwnerInverseTable = "sf_principals"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "owner_id"
	// LicensesTable is the table that holds the licenses relation/edge.
	LicensesTable = "sf_licenses"
	// LicensesInverseTable is the table name for the License entity.
	// It exists in this package in order to avoid circular dependency with the "license" package.
	LicensesInverseTable = "sf_licenses"
	// LicensesColumn is the table column denoting the licenses relation/edge.
	LicensesColumn = "listing_id"
)

// Columns holds all SQL columns for listing fields.
var Columns = []string{
	FieldID,
	FieldCreatorOrgID,
	FieldOwnerID,
	FieldProductType,
	FieldProductID,
	FieldTitle,
	FieldDescription,
	FieldPricingModel,
	FieldPriceCents,
	FieldCurrency,
	FieldStatus,
	FieldMetadata,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldPublishedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ProductTypeValidator is a validator for the "product_type" field. It is called by the builders before save.
	ProductTypeValidator func(string) error
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// DefaultPriceCents holds the default value on creation for the "price_cents" field.
	DefaultPriceCents int64
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	CurrencyValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// PricingModel defines the type for the "pricing_model" enum field.
type PricingModel string

// PricingModelFree is the default value of the PricingModel enum.
const DefaultPricingModel = PricingModelFree

// PricingModel values.
const (
	PricingModelFree         PricingModel = "free"
	PricingModelOneTime      PricingModel = "one_time"
	PricingModelSubscription PricingModel = "subscription"
	PricingModelPerSeat      PricingModel = "per_seat"
)

func (pm PricingModel) String() string {
	return string(pm)
}

// PricingModelValidator is a validator for the "pricing_model" field enum values. It is called by the builders before save.
func PricingModelValidator(pm PricingModel) error {
	switch pm {
	case PricingModelFree, PricingModelOneTime, PricingModelSubscription, PricingModelPerSeat:
		return nil
	default:
		return fmt.Errorf("listing: invalid enum value for pricing_model field: %q", pm)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusDraft is the default value of the Status enum.
const DefaultStatus = StatusDraft

// Status values.
const (
	StatusDraft         Status = "draft"
	StatusPendingReview Status = "pending_review"
	StatusPublished     Status = "published"
	StatusArchived      Status = "archived"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusDraft, StatusPendingReview, StatusPublished, StatusArchived:
		return nil
	default:
		return fmt.Errorf("listing: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Listing queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatorOrgID orders the results by the creator_org_id field.
func ByCreatorOrgID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatorOrgID, opts...).ToFunc()
}

// ByOwnerID orders the results by the owner_id field.
func ByOwnerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerID, opts...).ToFunc()
}

// ByProductType orders the results by the product_type field.
func ByProductType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductType, opts...).ToFunc()
}

// ByProductID orders the results by the product_id field.
func ByProductID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByPricingModel orders the results by the pricing_model field.
func ByPricingModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPricingModel, opts...).ToFunc()
}

// ByPriceCents orders the results by the price_cents field.
func ByPriceCents(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriceCents, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPublishedAt orders the results by the published_at field.
func ByPublishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublishedAt, opts...).ToFunc()
}

// ByCreatorOrgField orders the results by creator_org field.
func ByCreatorOrgField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCreatorOrgStep(), sql.OrderByField(field, opts...))
	}
}

// ByOwnerField orders the results by owner field.
func ByOwnerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOwnerStep(), sql.OrderByField(field, opts...))
	}
}

// ByLicensesCount orders the results by licenses count.
func ByLicensesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newLicensesStep(), opts...)
	}
}

// ByLicenses orders the results by licenses terms.
func ByLicenses(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLicensesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCreatorOrgStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CreatorOrgInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CreatorOrgTable, CreatorOrgColumn),
	)
}
func newOwnerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OwnerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
	)
}
func newLicensesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LicensesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, LicensesTable, LicensesColumn),
	)
}
