// Code generated by ent, DO NOT EDIT.

package application

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the application type in the database.
	Label = "application"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldPrincipalID holds the string denoting the principal_id field in the database.
	FieldPrincipalID = "principal_id"
	// FieldClientID holds the string denoting the client_id field in the database.
	FieldClientID = "client_id"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldLogoURL holds the string denoting the logo_url field in the database.
	FieldLogoURL = "logo_url"
	// FieldAppType holds the string denoting the app_type field in the database.
	FieldAppType = "app_type"
	// FieldRedirectUris holds the string denoting the redirect_uris field in the database.
	FieldRedirectUris = "redirect_uris"
	// FieldAllowedGrants holds the string denoting the allowed_grants field in the database.
	FieldAllowedGrants = "allowed_grants"
	// FieldAllowedResponseTypes holds the string denoting the allowed_response_types field in the database.
	FieldAllowedResponseTypes = "allowed_response_types"
	// FieldAccessTokenTTL holds the string denoting the access_token_ttl field in the database.
	FieldAccessTokenTTL = "access_token_ttl"
	// FieldRefreshTokenTTL holds the string denoting the refresh_token_ttl field in the database.
	FieldRefreshTokenTTL = "refresh_token_ttl"
	// FieldRefreshTokenRotation holds the string denoting the refresh_token_rotation field in the database.
	FieldRefreshTokenRotation = "refresh_token_rotation"
	// FieldFirstParty holds the string denoting the first_party field in the database.
	FieldFirstParty = "first_party"
	// FieldPublic holds the string denoting the public field in the database.
	FieldPublic = "public"
	// EdgePrincipal holds the string denoting the principal edge name in mutations.
	EdgePrincipal = "principal"
	// EdgeIssuedTokens holds the string denoting the issued_tokens edge name in mutations.
	EdgeIssuedTokens = "issued_tokens"
	// Table holds the table name of the application in the database.
	Table = "sf_applications"
	// PrincipalTable is the table that holds the principal relation/edge.
	PrincipalTable = "sf_applications"
	// PrincipalInverseTable is the table name for the Principal entity.
	// It exists in this package in order to avoid circular dependency with the "principal" package.
	PrincipalInverseTable = "sf_principals"
	// PrincipalColumn is the table column denoting the principal relation/edge.
	PrincipalColumn = "principal_id"
	// IssuedTokensTable is the table that holds the issued_tokens relation/edge.
	IssuedTokensTable = "sf_principal_tokens"
	// IssuedTokensInverseTable is the table name for the PrincipalToken entity.
	// It exists in this package in order to avoid circular dependency with the "principaltoken" package.
	IssuedTokensInverseTable = "sf_principal_tokens"
	// IssuedTokensColumn is the table column denoting the issued_tokens relation/edge.
	IssuedTokensColumn = "issued_by_app_id"
)

// Columns holds all SQL columns for application fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldPrincipalID,
	FieldClientID,
	FieldDescription,
	FieldLogoURL,
	FieldAppType,
	FieldRedirectUris,
	FieldAllowedGrants,
	FieldAllowedResponseTypes,
	FieldAccessTokenTTL,
	FieldRefreshTokenTTL,
	FieldRefreshTokenRotation,
	FieldFirstParty,
	FieldPublic,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	ClientIDValidator func(string) error
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// DefaultRedirectUris holds the default value on creation for the "redirect_uris" field.
	DefaultRedirectUris []string
	// DefaultAllowedGrants holds the default value on creation for the "allowed_grants" field.
	DefaultAllowedGrants []string
	// DefaultAllowedResponseTypes holds the default value on creation for the "allowed_response_types" field.
	DefaultAllowedResponseTypes []string
	// DefaultAccessTokenTTL holds the default value on creation for the "access_token_ttl" field.
	DefaultAccessTokenTTL int
	// DefaultRefreshTokenTTL holds the default value on creation for the "refresh_token_ttl" field.
	DefaultRefreshTokenTTL int
	// DefaultRefreshTokenRotation holds the default value on creation for the "refresh_token_rotation" field.
	DefaultRefreshTokenRotation bool
	// DefaultFirstParty holds the default value on creation for the "first_party" field.
	DefaultFirstParty bool
	// DefaultPublic holds the default value on creation for the "public" field.
	DefaultPublic bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// AppType defines the type for the "app_type" enum field.
type AppType string

// AppTypeWeb is the default value of the AppType enum.
const DefaultAppType = AppTypeWeb

// AppType values.
const (
	AppTypeWeb     AppType = "web"
	AppTypeSpa     AppType = "spa"
	AppTypeNative  AppType = "native"
	AppTypeMachine AppType = "machine"
)

func (at AppType) String() string {
	return string(at)
}

// AppTypeValidator is a validator for the "app_type" field enum values. It is called by the builders before save.
func AppTypeValidator(at AppType) error {
	switch at {
	case AppTypeWeb, AppTypeSpa, AppTypeNative, AppTypeMachine:
		return nil
	default:
		return fmt.Errorf("application: invalid enum value for app_type field: %q", at)
	}
}

// OrderOption defines the ordering options for the Application queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPrincipalID orders the results by the principal_id field.
func ByPrincipalID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrincipalID, opts...).ToFunc()
}

// ByClientID orders the results by the client_id field.
func ByClientID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientID, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByLogoURL orders the results by the logo_url field.
func ByLogoURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLogoURL, opts...).ToFunc()
}

// ByAppType orders the results by the app_type field.
func ByAppType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAppType, opts...).ToFunc()
}

// ByAccessTokenTTL orders the results by the access_token_ttl field.
func ByAccessTokenTTL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccessTokenTTL, opts...).ToFunc()
}

// ByRefreshTokenTTL orders the results by the refresh_token_ttl field.
func ByRefreshTokenTTL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefreshTokenTTL, opts...).ToFunc()
}

// ByRefreshTokenRotation orders the results by the refresh_token_rotation field.
func ByRefreshTokenRotation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefreshTokenRotation, opts...).ToFunc()
}

// ByFirstParty orders the results by the first_party field.
func ByFirstParty(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFirstParty, opts...).ToFunc()
}

// ByPublic orders the results by the public field.
func ByPublic(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublic, opts...).ToFunc()
}

// ByPrincipalField orders the results by principal field.
func ByPrincipalField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPrincipalStep(), sql.OrderByField(field, opts...))
	}
}

// ByIssuedTokensCount orders the results by issued_tokens count.
func ByIssuedTokensCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newIssuedTokensStep(), opts...)
	}
}

// ByIssuedTokens orders the results by issued_tokens terms.
func ByIssuedTokens(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newIssuedTokensStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newPrincipalStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PrincipalInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, PrincipalTable, PrincipalColumn),
	)
}
func newIssuedTokensStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(IssuedTokensInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, IssuedTokensTable, IssuedTokensColumn),
	)
}
