// Code generated by ent, DO NOT EDIT.

package externalidentity

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/plexusone/systemforge/identity/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldUpdatedAt, v))
}

// PrincipalID applies equality check predicate on the "principal_id" field. It's identical to PrincipalIDEQ.
func PrincipalID(v uuid.UUID) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldPrincipalID, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldProvider, v))
}

// Subject applies equality check predicate on the "subject" field. It's identical to SubjectEQ.
func Subject(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldSubject, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldEmail, v))
}

// EmailVerified applies equality check predicate on the "email_verified" field. It's identical to EmailVerifiedEQ.
func EmailVerified(v bool) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldEmailVerified, v))
}

// LastLoginAt applies equality check predicate on the "last_login_at" field. It's identical to LastLoginAtEQ.
func LastLoginAt(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldLastLoginAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLTE(FieldUpdatedAt, v))
}

// PrincipalIDEQ applies the EQ predicate on the "principal_id" field.
func PrincipalIDEQ(v uuid.UUID) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldPrincipalID, v))
}

// PrincipalIDNEQ applies the NEQ predicate on the "principal_id" field.
func PrincipalIDNEQ(v uuid.UUID) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNEQ(FieldPrincipalID, v))
}

// PrincipalIDIn applies the In predicate on the "principal_id" field.
func PrincipalIDIn(vs ...uuid.UUID) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldIn(FieldPrincipalID, vs...))
}

// PrincipalIDNotIn applies the NotIn predicate on the "principal_id" field.
func PrincipalIDNotIn(vs ...uuid.UUID) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNotIn(FieldPrincipalID, vs...))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldContainsFold(FieldProvider, v))
}

// SubjectEQ applies the EQ predicate on the "subject" field.
func SubjectEQ(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldSubject, v))
}

// SubjectNEQ applies the NEQ predicate on the "subject" field.
func SubjectNEQ(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNEQ(FieldSubject, v))
}

// SubjectIn applies the In predicate on the "subject" field.
func SubjectIn(vs ...string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldIn(FieldSubject, vs...))
}

// SubjectNotIn applies the NotIn predicate on the "subject" field.
func SubjectNotIn(vs ...string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNotIn(FieldSubject, vs...))
}

// SubjectGT applies the GT predicate on the "subject" field.
func SubjectGT(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGT(FieldSubject, v))
}

// SubjectGTE applies the GTE predicate on the "subject" field.
func SubjectGTE(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGTE(FieldSubject, v))
}

// SubjectLT applies the LT predicate on the "subject" field.
func SubjectLT(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLT(FieldSubject, v))
}

// SubjectLTE applies the LTE predicate on the "subject" field.
func SubjectLTE(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLTE(FieldSubject, v))
}

// SubjectContains applies the Contains predicate on the "subject" field.
func SubjectContains(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldContains(FieldSubject, v))
}

// SubjectHasPrefix applies the HasPrefix predicate on the "subject" field.
func SubjectHasPrefix(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldHasPrefix(FieldSubject, v))
}

// SubjectHasSuffix applies the HasSuffix predicate on the "subject" field.
func SubjectHasSuffix(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldHasSuffix(FieldSubject, v))
}

// SubjectEqualFold applies the EqualFold predicate on the "subject" field.
func SubjectEqualFold(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEqualFold(FieldSubject, v))
}

// SubjectContainsFold applies the ContainsFold predicate on the "subject" field.
func SubjectContainsFold(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldContainsFold(FieldSubject, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailIsNil applies the IsNil predicate on the "email" field.
func EmailIsNil() predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldIsNull(FieldEmail))
}

// EmailNotNil applies the NotNil predicate on the "email" field.
func EmailNotNil() predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNotNull(FieldEmail))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldContainsFold(FieldEmail, v))
}

// EmailVerifiedEQ applies the EQ predicate on the "email_verified" field.
func EmailVerifiedEQ(v bool) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldEmailVerified, v))
}

// EmailVerifiedNEQ applies the NEQ predicate on the "email_verified" field.
func EmailVerifiedNEQ(v bool) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNEQ(FieldEmailVerified, v))
}

// LastLoginAtEQ applies the EQ predicate on the "last_login_at" field.
func LastLoginAtEQ(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldLastLoginAt, v))
}

// LastLoginAtNEQ applies the NEQ predicate on the "last_login_at" field.
func LastLoginAtNEQ(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNEQ(FieldLastLoginAt, v))
}

// LastLoginAtIn applies the In predicate on the "last_login_at" field.
func LastLoginAtIn(vs ...time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldIn(FieldLastLoginAt, vs...))
}

// LastLoginAtNotIn applies the NotIn predicate on the "last_login_at" field.
func LastLoginAtNotIn(vs ...time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNotIn(FieldLastLoginAt, vs...))
}

// LastLoginAtGT applies the GT predicate on the "last_login_at" field.
func LastLoginAtGT(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGT(FieldLastLoginAt, v))
}

// LastLoginAtGTE applies the GTE predicate on the "last_login_at" field.
func LastLoginAtGTE(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGTE(FieldLastLoginAt, v))
}

// LastLoginAtLT applies the LT predicate on the "last_login_at" field.
func LastLoginAtLT(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLT(FieldLastLoginAt, v))
}

// LastLoginAtLTE applies the LTE predicate on the "last_login_at" field.
func LastLoginAtLTE(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLTE(FieldLastLoginAt, v))
}

// LastLoginAtIsNil applies the IsNil predicate on the "last_login_at" field.
func LastLoginAtIsNil() predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldIsNull(FieldLastLoginAt))
}

// LastLoginAtNotNil applies the NotNil predicate on the "last_login_at" field.
func LastLoginAtNotNil() predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNotNull(FieldLastLoginAt))
}

// HasPrincipal applies the HasEdge predicate on the "principal" edge.
func HasPrincipal() predicate.ExternalIdentity {
	return predicate.ExternalIdentity(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PrincipalTable, PrincipalColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPrincipalWith applies the HasEdge predicate on the "principal" edge with a given conditions (other predicates).
func HasPrincipalWith(preds ...predicate.Principal) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(func(s *sql.Selector) {
		step := newPrincipalStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ExternalIdentity) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ExternalIdentity) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ExternalIdentity) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.NotPredicates(p))
}
