package rls

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
)

// MigrationConfig configures RLS migration behavior.
type MigrationConfig struct {
	// Tables to apply RLS to. If empty, applies to SystemForge tables.
	Tables []string

	// TenantColumn is the column name for tenant isolation.
	// Defaults to "organization_id".
	TenantColumn string

	// SessionVariable is the PostgreSQL session variable for tenant ID.
	// Defaults to "app.current_tenant".
	SessionVariable string

	// BypassRoles are PostgreSQL roles that should bypass RLS.
	// Typically includes migration and admin roles.
	BypassRoles []string

	// AppRole is the PostgreSQL role used by the application.
	// RLS policies will be created for this role.
	AppRole string
}

// DefaultMigrationConfig returns default migration configuration.
func DefaultMigrationConfig() *MigrationConfig {
	return &MigrationConfig{
		TenantColumn:    "organization_id",
		SessionVariable: "app.current_tenant",
		AppRole:         "app_user",
	}
}

// SystemForgeTables returns the list of SystemForge tables that need RLS.
// These are the tables with tenant-scoped data.
var SystemForgeTables = []string{
	"sf_memberships",
	// sf_users and sf_organizations are typically not tenant-scoped
	// sf_oauth_accounts and sf_refresh_tokens are user-scoped, not tenant-scoped
}

// Migrator handles RLS migration for SystemForge tables.
type Migrator struct {
	db     *sql.DB
	config *MigrationConfig
}

// NewMigrator creates a new RLS migrator.
func NewMigrator(db *sql.DB, cfg *MigrationConfig) *Migrator {
	if cfg == nil {
		cfg = DefaultMigrationConfig()
	}
	return &Migrator{db: db, config: cfg}
}

// MigrateSystemForge applies RLS policies to SystemForge tables.
func (m *Migrator) MigrateSystemForge(ctx context.Context) error {
	tables := m.config.Tables
	if len(tables) == 0 {
		tables = SystemForgeTables
	}

	for _, table := range tables {
		if err := m.EnableRLS(ctx, table); err != nil {
			return fmt.Errorf("enabling RLS on %s: %w", table, err)
		}
	}

	// Grant bypass to specified roles
	for _, role := range m.config.BypassRoles {
		if err := m.GrantBypass(ctx, role); err != nil {
			return fmt.Errorf("granting bypass to %s: %w", role, err)
		}
	}

	return nil
}

// EnableRLS enables RLS on a table and creates standard policies.
func (m *Migrator) EnableRLS(ctx context.Context, table string) error {
	statements := []string{
		// Enable RLS
		fmt.Sprintf("ALTER TABLE %s ENABLE ROW LEVEL SECURITY", table),
		fmt.Sprintf("ALTER TABLE %s FORCE ROW LEVEL SECURITY", table),

		// Drop existing policies (idempotent)
		fmt.Sprintf("DROP POLICY IF EXISTS %s_tenant_isolation ON %s", table, table),

		// Create tenant isolation policy
		fmt.Sprintf(`CREATE POLICY %s_tenant_isolation ON %s
			FOR ALL
			USING (%s::text = current_setting('%s', true))
			WITH CHECK (%s::text = current_setting('%s', true))`,
			table, table,
			m.config.TenantColumn, m.config.SessionVariable,
			m.config.TenantColumn, m.config.SessionVariable),
	}

	for _, stmt := range statements {
		if _, err := m.db.ExecContext(ctx, stmt); err != nil {
			return fmt.Errorf("executing %q: %w", stmt, err)
		}
	}

	return nil
}

// DisableRLS disables RLS on a table and drops policies.
func (m *Migrator) DisableRLS(ctx context.Context, table string) error {
	statements := []string{
		fmt.Sprintf("DROP POLICY IF EXISTS %s_tenant_isolation ON %s", table, table),
		fmt.Sprintf("ALTER TABLE %s DISABLE ROW LEVEL SECURITY", table),
	}

	for _, stmt := range statements {
		if _, err := m.db.ExecContext(ctx, stmt); err != nil {
			return fmt.Errorf("executing %q: %w", stmt, err)
		}
	}

	return nil
}

// GrantBypass grants RLS bypass to a role.
func (m *Migrator) GrantBypass(ctx context.Context, role string) error {
	_, err := m.db.ExecContext(ctx, fmt.Sprintf("ALTER ROLE %s BYPASSRLS", role))
	return err
}

// RevokeBypass revokes RLS bypass from a role.
func (m *Migrator) RevokeBypass(ctx context.Context, role string) error {
	_, err := m.db.ExecContext(ctx, fmt.Sprintf("ALTER ROLE %s NOBYPASSRLS", role))
	return err
}

// GenerateMigrationSQL generates SQL for RLS migration without executing it.
// Useful for reviewing or including in migration files.
func (m *Migrator) GenerateMigrationSQL() string {
	tables := m.config.Tables
	if len(tables) == 0 {
		tables = SystemForgeTables
	}

	var sb strings.Builder
	sb.WriteString("-- SystemForge RLS Migration\n")
	sb.WriteString("-- Generated by github.com/plexusone/systemforge/rls\n\n")

	for _, table := range tables {
		fmt.Fprintf(&sb, "-- Enable RLS on %s\n", table)
		fmt.Fprintf(&sb, "ALTER TABLE %s ENABLE ROW LEVEL SECURITY;\n", table)
		fmt.Fprintf(&sb, "ALTER TABLE %s FORCE ROW LEVEL SECURITY;\n", table)
		fmt.Fprintf(&sb, "DROP POLICY IF EXISTS %s_tenant_isolation ON %s;\n", table, table)
		fmt.Fprintf(&sb, `CREATE POLICY %s_tenant_isolation ON %s
    FOR ALL
    USING (%s::text = current_setting('%s', true))
    WITH CHECK (%s::text = current_setting('%s', true));
`,
			table, table,
			m.config.TenantColumn, m.config.SessionVariable,
			m.config.TenantColumn, m.config.SessionVariable)
		sb.WriteString("\n")
	}

	for _, role := range m.config.BypassRoles {
		fmt.Fprintf(&sb, "-- Grant bypass to %s\n", role)
		fmt.Fprintf(&sb, "ALTER ROLE %s BYPASSRLS;\n", role)
	}

	return sb.String()
}

// GenerateRollbackSQL generates SQL to undo RLS migration.
func (m *Migrator) GenerateRollbackSQL() string {
	tables := m.config.Tables
	if len(tables) == 0 {
		tables = SystemForgeTables
	}

	var sb strings.Builder
	sb.WriteString("-- SystemForge RLS Rollback\n\n")

	for _, table := range tables {
		fmt.Fprintf(&sb, "DROP POLICY IF EXISTS %s_tenant_isolation ON %s;\n", table, table)
		fmt.Fprintf(&sb, "ALTER TABLE %s DISABLE ROW LEVEL SECURITY;\n", table)
	}

	for _, role := range m.config.BypassRoles {
		fmt.Fprintf(&sb, "ALTER ROLE %s NOBYPASSRLS;\n", role)
	}

	return sb.String()
}

// VerifyRLS checks that RLS is properly configured on tables.
func (m *Migrator) VerifyRLS(ctx context.Context) ([]TableRLSStatus, error) {
	tables := m.config.Tables
	if len(tables) == 0 {
		tables = SystemForgeTables
	}

	var results []TableRLSStatus
	for _, table := range tables {
		status, err := m.checkTableRLS(ctx, table)
		if err != nil {
			return nil, fmt.Errorf("checking %s: %w", table, err)
		}
		results = append(results, status)
	}

	return results, nil
}

// TableRLSStatus represents RLS status for a table.
type TableRLSStatus struct {
	Table       string
	RLSEnabled  bool
	RLSForced   bool
	HasPolicies bool
	Policies    []string
}

func (m *Migrator) checkTableRLS(ctx context.Context, table string) (TableRLSStatus, error) {
	status := TableRLSStatus{Table: table}

	// Check if RLS is enabled
	var rlsEnabled, rlsForced bool
	err := m.db.QueryRowContext(ctx, `
		SELECT relrowsecurity, relforcerowsecurity
		FROM pg_class
		WHERE relname = $1
	`, table).Scan(&rlsEnabled, &rlsForced)
	if err != nil {
		return status, err
	}
	status.RLSEnabled = rlsEnabled
	status.RLSForced = rlsForced

	// Get policies
	rows, err := m.db.QueryContext(ctx, `
		SELECT polname
		FROM pg_policy
		WHERE polrelid = $1::regclass
	`, table)
	if err != nil {
		return status, err
	}
	defer func() { _ = rows.Close() }()

	for rows.Next() {
		var polname string
		if err := rows.Scan(&polname); err != nil {
			return status, err
		}
		status.Policies = append(status.Policies, polname)
	}
	status.HasPolicies = len(status.Policies) > 0

	return status, rows.Err()
}
