// Code generated by ent, DO NOT EDIT.

package oauthtoken

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/plexusone/systemforge/identity/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLTE(FieldID, id))
}

// AppID applies equality check predicate on the "app_id" field. It's identical to AppIDEQ.
func AppID(v uuid.UUID) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldAppID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldUserID, v))
}

// Subject applies equality check predicate on the "subject" field. It's identical to SubjectEQ.
func Subject(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldSubject, v))
}

// ServiceAccountID applies equality check predicate on the "service_account_id" field. It's identical to ServiceAccountIDEQ.
func ServiceAccountID(v uuid.UUID) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldServiceAccountID, v))
}

// AccessTokenSignature applies equality check predicate on the "access_token_signature" field. It's identical to AccessTokenSignatureEQ.
func AccessTokenSignature(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldAccessTokenSignature, v))
}

// RefreshTokenSignature applies equality check predicate on the "refresh_token_signature" field. It's identical to RefreshTokenSignatureEQ.
func RefreshTokenSignature(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldRefreshTokenSignature, v))
}

// FamilyID applies equality check predicate on the "family_id" field. It's identical to FamilyIDEQ.
func FamilyID(v uuid.UUID) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldFamilyID, v))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldSessionID, v))
}

// RequestData applies equality check predicate on the "request_data" field. It's identical to RequestDataEQ.
func RequestData(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldRequestData, v))
}

// AccessExpiresAt applies equality check predicate on the "access_expires_at" field. It's identical to AccessExpiresAtEQ.
func AccessExpiresAt(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldAccessExpiresAt, v))
}

// RefreshExpiresAt applies equality check predicate on the "refresh_expires_at" field. It's identical to RefreshExpiresAtEQ.
func RefreshExpiresAt(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldRefreshExpiresAt, v))
}

// Revoked applies equality check predicate on the "revoked" field. It's identical to RevokedEQ.
func Revoked(v bool) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldRevoked, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedReason applies equality check predicate on the "revoked_reason" field. It's identical to RevokedReasonEQ.
func RevokedReason(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldRevokedReason, v))
}

// ClientIP applies equality check predicate on the "client_ip" field. It's identical to ClientIPEQ.
func ClientIP(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldClientIP, v))
}

// UserAgent applies equality check predicate on the "user_agent" field. It's identical to UserAgentEQ.
func UserAgent(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldUserAgent, v))
}

// LastUsedAt applies equality check predicate on the "last_used_at" field. It's identical to LastUsedAtEQ.
func LastUsedAt(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldLastUsedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldCreatedAt, v))
}

// AppIDEQ applies the EQ predicate on the "app_id" field.
func AppIDEQ(v uuid.UUID) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldAppID, v))
}

// AppIDNEQ applies the NEQ predicate on the "app_id" field.
func AppIDNEQ(v uuid.UUID) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNEQ(FieldAppID, v))
}

// AppIDIn applies the In predicate on the "app_id" field.
func AppIDIn(vs ...uuid.UUID) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIn(FieldAppID, vs...))
}

// AppIDNotIn applies the NotIn predicate on the "app_id" field.
func AppIDNotIn(vs ...uuid.UUID) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotIn(FieldAppID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotNull(FieldUserID))
}

// SubjectEQ applies the EQ predicate on the "subject" field.
func SubjectEQ(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldSubject, v))
}

// SubjectNEQ applies the NEQ predicate on the "subject" field.
func SubjectNEQ(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNEQ(FieldSubject, v))
}

// SubjectIn applies the In predicate on the "subject" field.
func SubjectIn(vs ...string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIn(FieldSubject, vs...))
}

// SubjectNotIn applies the NotIn predicate on the "subject" field.
func SubjectNotIn(vs ...string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotIn(FieldSubject, vs...))
}

// SubjectGT applies the GT predicate on the "subject" field.
func SubjectGT(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGT(FieldSubject, v))
}

// SubjectGTE applies the GTE predicate on the "subject" field.
func SubjectGTE(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGTE(FieldSubject, v))
}

// SubjectLT applies the LT predicate on the "subject" field.
func SubjectLT(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLT(FieldSubject, v))
}

// SubjectLTE applies the LTE predicate on the "subject" field.
func SubjectLTE(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLTE(FieldSubject, v))
}

// SubjectContains applies the Contains predicate on the "subject" field.
func SubjectContains(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldContains(FieldSubject, v))
}

// SubjectHasPrefix applies the HasPrefix predicate on the "subject" field.
func SubjectHasPrefix(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldHasPrefix(FieldSubject, v))
}

// SubjectHasSuffix applies the HasSuffix predicate on the "subject" field.
func SubjectHasSuffix(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldHasSuffix(FieldSubject, v))
}

// SubjectIsNil applies the IsNil predicate on the "subject" field.
func SubjectIsNil() predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIsNull(FieldSubject))
}

// SubjectNotNil applies the NotNil predicate on the "subject" field.
func SubjectNotNil() predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotNull(FieldSubject))
}

// SubjectEqualFold applies the EqualFold predicate on the "subject" field.
func SubjectEqualFold(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEqualFold(FieldSubject, v))
}

// SubjectContainsFold applies the ContainsFold predicate on the "subject" field.
func SubjectContainsFold(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldContainsFold(FieldSubject, v))
}

// ServiceAccountIDEQ applies the EQ predicate on the "service_account_id" field.
func ServiceAccountIDEQ(v uuid.UUID) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldServiceAccountID, v))
}

// ServiceAccountIDNEQ applies the NEQ predicate on the "service_account_id" field.
func ServiceAccountIDNEQ(v uuid.UUID) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNEQ(FieldServiceAccountID, v))
}

// ServiceAccountIDIn applies the In predicate on the "service_account_id" field.
func ServiceAccountIDIn(vs ...uuid.UUID) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIn(FieldServiceAccountID, vs...))
}

// ServiceAccountIDNotIn applies the NotIn predicate on the "service_account_id" field.
func ServiceAccountIDNotIn(vs ...uuid.UUID) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotIn(FieldServiceAccountID, vs...))
}

// ServiceAccountIDGT applies the GT predicate on the "service_account_id" field.
func ServiceAccountIDGT(v uuid.UUID) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGT(FieldServiceAccountID, v))
}

// ServiceAccountIDGTE applies the GTE predicate on the "service_account_id" field.
func ServiceAccountIDGTE(v uuid.UUID) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGTE(FieldServiceAccountID, v))
}

// ServiceAccountIDLT applies the LT predicate on the "service_account_id" field.
func ServiceAccountIDLT(v uuid.UUID) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLT(FieldServiceAccountID, v))
}

// ServiceAccountIDLTE applies the LTE predicate on the "service_account_id" field.
func ServiceAccountIDLTE(v uuid.UUID) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLTE(FieldServiceAccountID, v))
}

// ServiceAccountIDIsNil applies the IsNil predicate on the "service_account_id" field.
func ServiceAccountIDIsNil() predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIsNull(FieldServiceAccountID))
}

// ServiceAccountIDNotNil applies the NotNil predicate on the "service_account_id" field.
func ServiceAccountIDNotNil() predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotNull(FieldServiceAccountID))
}

// AccessTokenSignatureEQ applies the EQ predicate on the "access_token_signature" field.
func AccessTokenSignatureEQ(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldAccessTokenSignature, v))
}

// AccessTokenSignatureNEQ applies the NEQ predicate on the "access_token_signature" field.
func AccessTokenSignatureNEQ(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNEQ(FieldAccessTokenSignature, v))
}

// AccessTokenSignatureIn applies the In predicate on the "access_token_signature" field.
func AccessTokenSignatureIn(vs ...string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIn(FieldAccessTokenSignature, vs...))
}

// AccessTokenSignatureNotIn applies the NotIn predicate on the "access_token_signature" field.
func AccessTokenSignatureNotIn(vs ...string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotIn(FieldAccessTokenSignature, vs...))
}

// AccessTokenSignatureGT applies the GT predicate on the "access_token_signature" field.
func AccessTokenSignatureGT(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGT(FieldAccessTokenSignature, v))
}

// AccessTokenSignatureGTE applies the GTE predicate on the "access_token_signature" field.
func AccessTokenSignatureGTE(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGTE(FieldAccessTokenSignature, v))
}

// AccessTokenSignatureLT applies the LT predicate on the "access_token_signature" field.
func AccessTokenSignatureLT(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLT(FieldAccessTokenSignature, v))
}

// AccessTokenSignatureLTE applies the LTE predicate on the "access_token_signature" field.
func AccessTokenSignatureLTE(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLTE(FieldAccessTokenSignature, v))
}

// AccessTokenSignatureContains applies the Contains predicate on the "access_token_signature" field.
func AccessTokenSignatureContains(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldContains(FieldAccessTokenSignature, v))
}

// AccessTokenSignatureHasPrefix applies the HasPrefix predicate on the "access_token_signature" field.
func AccessTokenSignatureHasPrefix(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldHasPrefix(FieldAccessTokenSignature, v))
}

// AccessTokenSignatureHasSuffix applies the HasSuffix predicate on the "access_token_signature" field.
func AccessTokenSignatureHasSuffix(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldHasSuffix(FieldAccessTokenSignature, v))
}

// AccessTokenSignatureEqualFold applies the EqualFold predicate on the "access_token_signature" field.
func AccessTokenSignatureEqualFold(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEqualFold(FieldAccessTokenSignature, v))
}

// AccessTokenSignatureContainsFold applies the ContainsFold predicate on the "access_token_signature" field.
func AccessTokenSignatureContainsFold(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldContainsFold(FieldAccessTokenSignature, v))
}

// RefreshTokenSignatureEQ applies the EQ predicate on the "refresh_token_signature" field.
func RefreshTokenSignatureEQ(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldRefreshTokenSignature, v))
}

// RefreshTokenSignatureNEQ applies the NEQ predicate on the "refresh_token_signature" field.
func RefreshTokenSignatureNEQ(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNEQ(FieldRefreshTokenSignature, v))
}

// RefreshTokenSignatureIn applies the In predicate on the "refresh_token_signature" field.
func RefreshTokenSignatureIn(vs ...string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIn(FieldRefreshTokenSignature, vs...))
}

// RefreshTokenSignatureNotIn applies the NotIn predicate on the "refresh_token_signature" field.
func RefreshTokenSignatureNotIn(vs ...string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotIn(FieldRefreshTokenSignature, vs...))
}

// RefreshTokenSignatureGT applies the GT predicate on the "refresh_token_signature" field.
func RefreshTokenSignatureGT(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGT(FieldRefreshTokenSignature, v))
}

// RefreshTokenSignatureGTE applies the GTE predicate on the "refresh_token_signature" field.
func RefreshTokenSignatureGTE(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGTE(FieldRefreshTokenSignature, v))
}

// RefreshTokenSignatureLT applies the LT predicate on the "refresh_token_signature" field.
func RefreshTokenSignatureLT(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLT(FieldRefreshTokenSignature, v))
}

// RefreshTokenSignatureLTE applies the LTE predicate on the "refresh_token_signature" field.
func RefreshTokenSignatureLTE(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLTE(FieldRefreshTokenSignature, v))
}

// RefreshTokenSignatureContains applies the Contains predicate on the "refresh_token_signature" field.
func RefreshTokenSignatureContains(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldContains(FieldRefreshTokenSignature, v))
}

// RefreshTokenSignatureHasPrefix applies the HasPrefix predicate on the "refresh_token_signature" field.
func RefreshTokenSignatureHasPrefix(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldHasPrefix(FieldRefreshTokenSignature, v))
}

// RefreshTokenSignatureHasSuffix applies the HasSuffix predicate on the "refresh_token_signature" field.
func RefreshTokenSignatureHasSuffix(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldHasSuffix(FieldRefreshTokenSignature, v))
}

// RefreshTokenSignatureIsNil applies the IsNil predicate on the "refresh_token_signature" field.
func RefreshTokenSignatureIsNil() predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIsNull(FieldRefreshTokenSignature))
}

// RefreshTokenSignatureNotNil applies the NotNil predicate on the "refresh_token_signature" field.
func RefreshTokenSignatureNotNil() predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotNull(FieldRefreshTokenSignature))
}

// RefreshTokenSignatureEqualFold applies the EqualFold predicate on the "refresh_token_signature" field.
func RefreshTokenSignatureEqualFold(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEqualFold(FieldRefreshTokenSignature, v))
}

// RefreshTokenSignatureContainsFold applies the ContainsFold predicate on the "refresh_token_signature" field.
func RefreshTokenSignatureContainsFold(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldContainsFold(FieldRefreshTokenSignature, v))
}

// FamilyIDEQ applies the EQ predicate on the "family_id" field.
func FamilyIDEQ(v uuid.UUID) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldFamilyID, v))
}

// FamilyIDNEQ applies the NEQ predicate on the "family_id" field.
func FamilyIDNEQ(v uuid.UUID) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNEQ(FieldFamilyID, v))
}

// FamilyIDIn applies the In predicate on the "family_id" field.
func FamilyIDIn(vs ...uuid.UUID) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIn(FieldFamilyID, vs...))
}

// FamilyIDNotIn applies the NotIn predicate on the "family_id" field.
func FamilyIDNotIn(vs ...uuid.UUID) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotIn(FieldFamilyID, vs...))
}

// FamilyIDGT applies the GT predicate on the "family_id" field.
func FamilyIDGT(v uuid.UUID) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGT(FieldFamilyID, v))
}

// FamilyIDGTE applies the GTE predicate on the "family_id" field.
func FamilyIDGTE(v uuid.UUID) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGTE(FieldFamilyID, v))
}

// FamilyIDLT applies the LT predicate on the "family_id" field.
func FamilyIDLT(v uuid.UUID) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLT(FieldFamilyID, v))
}

// FamilyIDLTE applies the LTE predicate on the "family_id" field.
func FamilyIDLTE(v uuid.UUID) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLTE(FieldFamilyID, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDIsNil applies the IsNil predicate on the "session_id" field.
func SessionIDIsNil() predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIsNull(FieldSessionID))
}

// SessionIDNotNil applies the NotNil predicate on the "session_id" field.
func SessionIDNotNil() predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotNull(FieldSessionID))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldContainsFold(FieldSessionID, v))
}

// RequestDataEQ applies the EQ predicate on the "request_data" field.
func RequestDataEQ(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldRequestData, v))
}

// RequestDataNEQ applies the NEQ predicate on the "request_data" field.
func RequestDataNEQ(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNEQ(FieldRequestData, v))
}

// RequestDataIn applies the In predicate on the "request_data" field.
func RequestDataIn(vs ...string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIn(FieldRequestData, vs...))
}

// RequestDataNotIn applies the NotIn predicate on the "request_data" field.
func RequestDataNotIn(vs ...string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotIn(FieldRequestData, vs...))
}

// RequestDataGT applies the GT predicate on the "request_data" field.
func RequestDataGT(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGT(FieldRequestData, v))
}

// RequestDataGTE applies the GTE predicate on the "request_data" field.
func RequestDataGTE(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGTE(FieldRequestData, v))
}

// RequestDataLT applies the LT predicate on the "request_data" field.
func RequestDataLT(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLT(FieldRequestData, v))
}

// RequestDataLTE applies the LTE predicate on the "request_data" field.
func RequestDataLTE(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLTE(FieldRequestData, v))
}

// RequestDataContains applies the Contains predicate on the "request_data" field.
func RequestDataContains(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldContains(FieldRequestData, v))
}

// RequestDataHasPrefix applies the HasPrefix predicate on the "request_data" field.
func RequestDataHasPrefix(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldHasPrefix(FieldRequestData, v))
}

// RequestDataHasSuffix applies the HasSuffix predicate on the "request_data" field.
func RequestDataHasSuffix(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldHasSuffix(FieldRequestData, v))
}

// RequestDataIsNil applies the IsNil predicate on the "request_data" field.
func RequestDataIsNil() predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIsNull(FieldRequestData))
}

// RequestDataNotNil applies the NotNil predicate on the "request_data" field.
func RequestDataNotNil() predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotNull(FieldRequestData))
}

// RequestDataEqualFold applies the EqualFold predicate on the "request_data" field.
func RequestDataEqualFold(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEqualFold(FieldRequestData, v))
}

// RequestDataContainsFold applies the ContainsFold predicate on the "request_data" field.
func RequestDataContainsFold(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldContainsFold(FieldRequestData, v))
}

// AccessExpiresAtEQ applies the EQ predicate on the "access_expires_at" field.
func AccessExpiresAtEQ(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldAccessExpiresAt, v))
}

// AccessExpiresAtNEQ applies the NEQ predicate on the "access_expires_at" field.
func AccessExpiresAtNEQ(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNEQ(FieldAccessExpiresAt, v))
}

// AccessExpiresAtIn applies the In predicate on the "access_expires_at" field.
func AccessExpiresAtIn(vs ...time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIn(FieldAccessExpiresAt, vs...))
}

// AccessExpiresAtNotIn applies the NotIn predicate on the "access_expires_at" field.
func AccessExpiresAtNotIn(vs ...time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotIn(FieldAccessExpiresAt, vs...))
}

// AccessExpiresAtGT applies the GT predicate on the "access_expires_at" field.
func AccessExpiresAtGT(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGT(FieldAccessExpiresAt, v))
}

// AccessExpiresAtGTE applies the GTE predicate on the "access_expires_at" field.
func AccessExpiresAtGTE(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGTE(FieldAccessExpiresAt, v))
}

// AccessExpiresAtLT applies the LT predicate on the "access_expires_at" field.
func AccessExpiresAtLT(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLT(FieldAccessExpiresAt, v))
}

// AccessExpiresAtLTE applies the LTE predicate on the "access_expires_at" field.
func AccessExpiresAtLTE(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLTE(FieldAccessExpiresAt, v))
}

// RefreshExpiresAtEQ applies the EQ predicate on the "refresh_expires_at" field.
func RefreshExpiresAtEQ(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldRefreshExpiresAt, v))
}

// RefreshExpiresAtNEQ applies the NEQ predicate on the "refresh_expires_at" field.
func RefreshExpiresAtNEQ(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNEQ(FieldRefreshExpiresAt, v))
}

// RefreshExpiresAtIn applies the In predicate on the "refresh_expires_at" field.
func RefreshExpiresAtIn(vs ...time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIn(FieldRefreshExpiresAt, vs...))
}

// RefreshExpiresAtNotIn applies the NotIn predicate on the "refresh_expires_at" field.
func RefreshExpiresAtNotIn(vs ...time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotIn(FieldRefreshExpiresAt, vs...))
}

// RefreshExpiresAtGT applies the GT predicate on the "refresh_expires_at" field.
func RefreshExpiresAtGT(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGT(FieldRefreshExpiresAt, v))
}

// RefreshExpiresAtGTE applies the GTE predicate on the "refresh_expires_at" field.
func RefreshExpiresAtGTE(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGTE(FieldRefreshExpiresAt, v))
}

// RefreshExpiresAtLT applies the LT predicate on the "refresh_expires_at" field.
func RefreshExpiresAtLT(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLT(FieldRefreshExpiresAt, v))
}

// RefreshExpiresAtLTE applies the LTE predicate on the "refresh_expires_at" field.
func RefreshExpiresAtLTE(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLTE(FieldRefreshExpiresAt, v))
}

// RefreshExpiresAtIsNil applies the IsNil predicate on the "refresh_expires_at" field.
func RefreshExpiresAtIsNil() predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIsNull(FieldRefreshExpiresAt))
}

// RefreshExpiresAtNotNil applies the NotNil predicate on the "refresh_expires_at" field.
func RefreshExpiresAtNotNil() predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotNull(FieldRefreshExpiresAt))
}

// RevokedEQ applies the EQ predicate on the "revoked" field.
func RevokedEQ(v bool) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldRevoked, v))
}

// RevokedNEQ applies the NEQ predicate on the "revoked" field.
func RevokedNEQ(v bool) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNEQ(FieldRevoked, v))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedAtIsNil applies the IsNil predicate on the "revoked_at" field.
func RevokedAtIsNil() predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIsNull(FieldRevokedAt))
}

// RevokedAtNotNil applies the NotNil predicate on the "revoked_at" field.
func RevokedAtNotNil() predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotNull(FieldRevokedAt))
}

// RevokedReasonEQ applies the EQ predicate on the "revoked_reason" field.
func RevokedReasonEQ(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldRevokedReason, v))
}

// RevokedReasonNEQ applies the NEQ predicate on the "revoked_reason" field.
func RevokedReasonNEQ(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNEQ(FieldRevokedReason, v))
}

// RevokedReasonIn applies the In predicate on the "revoked_reason" field.
func RevokedReasonIn(vs ...string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIn(FieldRevokedReason, vs...))
}

// RevokedReasonNotIn applies the NotIn predicate on the "revoked_reason" field.
func RevokedReasonNotIn(vs ...string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotIn(FieldRevokedReason, vs...))
}

// RevokedReasonGT applies the GT predicate on the "revoked_reason" field.
func RevokedReasonGT(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGT(FieldRevokedReason, v))
}

// RevokedReasonGTE applies the GTE predicate on the "revoked_reason" field.
func RevokedReasonGTE(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGTE(FieldRevokedReason, v))
}

// RevokedReasonLT applies the LT predicate on the "revoked_reason" field.
func RevokedReasonLT(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLT(FieldRevokedReason, v))
}

// RevokedReasonLTE applies the LTE predicate on the "revoked_reason" field.
func RevokedReasonLTE(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLTE(FieldRevokedReason, v))
}

// RevokedReasonContains applies the Contains predicate on the "revoked_reason" field.
func RevokedReasonContains(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldContains(FieldRevokedReason, v))
}

// RevokedReasonHasPrefix applies the HasPrefix predicate on the "revoked_reason" field.
func RevokedReasonHasPrefix(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldHasPrefix(FieldRevokedReason, v))
}

// RevokedReasonHasSuffix applies the HasSuffix predicate on the "revoked_reason" field.
func RevokedReasonHasSuffix(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldHasSuffix(FieldRevokedReason, v))
}

// RevokedReasonIsNil applies the IsNil predicate on the "revoked_reason" field.
func RevokedReasonIsNil() predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIsNull(FieldRevokedReason))
}

// RevokedReasonNotNil applies the NotNil predicate on the "revoked_reason" field.
func RevokedReasonNotNil() predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotNull(FieldRevokedReason))
}

// RevokedReasonEqualFold applies the EqualFold predicate on the "revoked_reason" field.
func RevokedReasonEqualFold(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEqualFold(FieldRevokedReason, v))
}

// RevokedReasonContainsFold applies the ContainsFold predicate on the "revoked_reason" field.
func RevokedReasonContainsFold(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldContainsFold(FieldRevokedReason, v))
}

// ClientIPEQ applies the EQ predicate on the "client_ip" field.
func ClientIPEQ(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldClientIP, v))
}

// ClientIPNEQ applies the NEQ predicate on the "client_ip" field.
func ClientIPNEQ(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNEQ(FieldClientIP, v))
}

// ClientIPIn applies the In predicate on the "client_ip" field.
func ClientIPIn(vs ...string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIn(FieldClientIP, vs...))
}

// ClientIPNotIn applies the NotIn predicate on the "client_ip" field.
func ClientIPNotIn(vs ...string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotIn(FieldClientIP, vs...))
}

// ClientIPGT applies the GT predicate on the "client_ip" field.
func ClientIPGT(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGT(FieldClientIP, v))
}

// ClientIPGTE applies the GTE predicate on the "client_ip" field.
func ClientIPGTE(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGTE(FieldClientIP, v))
}

// ClientIPLT applies the LT predicate on the "client_ip" field.
func ClientIPLT(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLT(FieldClientIP, v))
}

// ClientIPLTE applies the LTE predicate on the "client_ip" field.
func ClientIPLTE(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLTE(FieldClientIP, v))
}

// ClientIPContains applies the Contains predicate on the "client_ip" field.
func ClientIPContains(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldContains(FieldClientIP, v))
}

// ClientIPHasPrefix applies the HasPrefix predicate on the "client_ip" field.
func ClientIPHasPrefix(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldHasPrefix(FieldClientIP, v))
}

// ClientIPHasSuffix applies the HasSuffix predicate on the "client_ip" field.
func ClientIPHasSuffix(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldHasSuffix(FieldClientIP, v))
}

// ClientIPIsNil applies the IsNil predicate on the "client_ip" field.
func ClientIPIsNil() predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIsNull(FieldClientIP))
}

// ClientIPNotNil applies the NotNil predicate on the "client_ip" field.
func ClientIPNotNil() predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotNull(FieldClientIP))
}

// ClientIPEqualFold applies the EqualFold predicate on the "client_ip" field.
func ClientIPEqualFold(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEqualFold(FieldClientIP, v))
}

// ClientIPContainsFold applies the ContainsFold predicate on the "client_ip" field.
func ClientIPContainsFold(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldContainsFold(FieldClientIP, v))
}

// UserAgentEQ applies the EQ predicate on the "user_agent" field.
func UserAgentEQ(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldUserAgent, v))
}

// UserAgentNEQ applies the NEQ predicate on the "user_agent" field.
func UserAgentNEQ(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNEQ(FieldUserAgent, v))
}

// UserAgentIn applies the In predicate on the "user_agent" field.
func UserAgentIn(vs ...string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIn(FieldUserAgent, vs...))
}

// UserAgentNotIn applies the NotIn predicate on the "user_agent" field.
func UserAgentNotIn(vs ...string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotIn(FieldUserAgent, vs...))
}

// UserAgentGT applies the GT predicate on the "user_agent" field.
func UserAgentGT(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGT(FieldUserAgent, v))
}

// UserAgentGTE applies the GTE predicate on the "user_agent" field.
func UserAgentGTE(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGTE(FieldUserAgent, v))
}

// UserAgentLT applies the LT predicate on the "user_agent" field.
func UserAgentLT(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLT(FieldUserAgent, v))
}

// UserAgentLTE applies the LTE predicate on the "user_agent" field.
func UserAgentLTE(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLTE(FieldUserAgent, v))
}

// UserAgentContains applies the Contains predicate on the "user_agent" field.
func UserAgentContains(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldContains(FieldUserAgent, v))
}

// UserAgentHasPrefix applies the HasPrefix predicate on the "user_agent" field.
func UserAgentHasPrefix(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldHasPrefix(FieldUserAgent, v))
}

// UserAgentHasSuffix applies the HasSuffix predicate on the "user_agent" field.
func UserAgentHasSuffix(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldHasSuffix(FieldUserAgent, v))
}

// UserAgentIsNil applies the IsNil predicate on the "user_agent" field.
func UserAgentIsNil() predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIsNull(FieldUserAgent))
}

// UserAgentNotNil applies the NotNil predicate on the "user_agent" field.
func UserAgentNotNil() predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotNull(FieldUserAgent))
}

// UserAgentEqualFold applies the EqualFold predicate on the "user_agent" field.
func UserAgentEqualFold(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEqualFold(FieldUserAgent, v))
}

// UserAgentContainsFold applies the ContainsFold predicate on the "user_agent" field.
func UserAgentContainsFold(v string) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldContainsFold(FieldUserAgent, v))
}

// LastUsedAtEQ applies the EQ predicate on the "last_used_at" field.
func LastUsedAtEQ(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldLastUsedAt, v))
}

// LastUsedAtNEQ applies the NEQ predicate on the "last_used_at" field.
func LastUsedAtNEQ(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNEQ(FieldLastUsedAt, v))
}

// LastUsedAtIn applies the In predicate on the "last_used_at" field.
func LastUsedAtIn(vs ...time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIn(FieldLastUsedAt, vs...))
}

// LastUsedAtNotIn applies the NotIn predicate on the "last_used_at" field.
func LastUsedAtNotIn(vs ...time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotIn(FieldLastUsedAt, vs...))
}

// LastUsedAtGT applies the GT predicate on the "last_used_at" field.
func LastUsedAtGT(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGT(FieldLastUsedAt, v))
}

// LastUsedAtGTE applies the GTE predicate on the "last_used_at" field.
func LastUsedAtGTE(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGTE(FieldLastUsedAt, v))
}

// LastUsedAtLT applies the LT predicate on the "last_used_at" field.
func LastUsedAtLT(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLT(FieldLastUsedAt, v))
}

// LastUsedAtLTE applies the LTE predicate on the "last_used_at" field.
func LastUsedAtLTE(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLTE(FieldLastUsedAt, v))
}

// LastUsedAtIsNil applies the IsNil predicate on the "last_used_at" field.
func LastUsedAtIsNil() predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIsNull(FieldLastUsedAt))
}

// LastUsedAtNotNil applies the NotNil predicate on the "last_used_at" field.
func LastUsedAtNotNil() predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotNull(FieldLastUsedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OAuthToken {
	return predicate.OAuthToken(sql.FieldLTE(FieldCreatedAt, v))
}

// HasApp applies the HasEdge predicate on the "app" edge.
func HasApp() predicate.OAuthToken {
	return predicate.OAuthToken(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AppTable, AppColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAppWith applies the HasEdge predicate on the "app" edge with a given conditions (other predicates).
func HasAppWith(preds ...predicate.OAuthApp) predicate.OAuthToken {
	return predicate.OAuthToken(func(s *sql.Selector) {
		step := newAppStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.OAuthToken {
	return predicate.OAuthToken(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.OAuthToken {
	return predicate.OAuthToken(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OAuthToken) predicate.OAuthToken {
	return predicate.OAuthToken(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OAuthToken) predicate.OAuthToken {
	return predicate.OAuthToken(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OAuthToken) predicate.OAuthToken {
	return predicate.OAuthToken(sql.NotPredicates(p))
}
