// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/plexusone/systemforge/identity/ent/externalidentity"
	"github.com/plexusone/systemforge/identity/ent/principal"
)

// ExternalIdentity is the model entity for the ExternalIdentity schema.
type ExternalIdentity struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Principal this upstream identity is linked to
	PrincipalID uuid.UUID `json:"principal_id,omitempty"`
	// Upstream provider name (e.g., github, google)
	Provider string `json:"provider,omitempty"`
	// Stable user ID at the provider (GitHub numeric id, Google sub)
	Subject string `json:"subject,omitempty"`
	// Email last reported by the provider
	Email string `json:"email,omitempty"`
	// Whether the provider asserted the email is verified
	EmailVerified bool `json:"email_verified,omitempty"`
	// Last successful login through this identity
	LastLoginAt *time.Time `json:"last_login_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ExternalIdentityQuery when eager-loading is set.
	Edges        ExternalIdentityEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ExternalIdentityEdges holds the relations/edges for other nodes in the graph.
type ExternalIdentityEdges struct {
	// Principal holds the value of the principal edge.
	Principal *Principal `json:"principal,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PrincipalOrErr returns the Principal value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ExternalIdentityEdges) PrincipalOrErr() (*Principal, error) {
	if e.Principal != nil {
		return e.Principal, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: principal.Label}
	}
	return nil, &NotLoadedError{edge: "principal"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ExternalIdentity) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case externalidentity.FieldEmailVerified:
			values[i] = new(sql.NullBool)
		case externalidentity.FieldProvider, externalidentity.FieldSubject, externalidentity.FieldEmail:
			values[i] = new(sql.NullString)
		case externalidentity.FieldCreatedAt, externalidentity.FieldUpdatedAt, externalidentity.FieldLastLoginAt:
			values[i] = new(sql.NullTime)
		case externalidentity.FieldID, externalidentity.FieldPrincipalID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ExternalIdentity fields.
func (_m *ExternalIdentity) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case externalidentity.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case externalidentity.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case externalidentity.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case externalidentity.FieldPrincipalID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field principal_id", values[i])
			} else if value != nil {
				_m.PrincipalID = *value
			}
		case externalidentity.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case externalidentity.FieldSubject:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subject", values[i])
			} else if value.Valid {
				_m.Subject = value.String
			}
		case externalidentity.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case externalidentity.FieldEmailVerified:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field email_verified", values[i])
			} else if value.Valid {
				_m.EmailVerified = value.Bool
			}
		case externalidentity.FieldLastLoginAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_login_at", values[i])
			} else if value.Valid {
				_m.LastLoginAt = new(time.Time)
				*_m.LastLoginAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ExternalIdentity.
// This includes values selected through modifiers, order, etc.
func (_m *ExternalIdentity) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPrincipal queries the "principal" edge of the ExternalIdentity entity.
func (_m *ExternalIdentity) QueryPrincipal() *PrincipalQuery {
	return NewExternalIdentityClient(_m.config).QueryPrincipal(_m)
}

// Update returns a builder for updating this ExternalIdentity.
// Note that you need to call ExternalIdentity.Unwrap() before calling this method if this ExternalIdentity
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ExternalIdentity) Update() *ExternalIdentityUpdateOne {
	return NewExternalIdentityClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ExternalIdentity entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ExternalIdentity) Unwrap() *ExternalIdentity {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ExternalIdentity is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ExternalIdentity) String() string {
	var builder strings.Builder
	builder.WriteString("ExternalIdentity(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("principal_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PrincipalID))
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("subject=")
	builder.WriteString(_m.Subject)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("email_verified=")
	builder.WriteString(fmt.Sprintf("%v", _m.EmailVerified))
	builder.WriteString(", ")
	if v := _m.LastLoginAt; v != nil {
		builder.WriteString("last_login_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ExternalIdentities is a parsable slice of ExternalIdentity.
type ExternalIdentities []*ExternalIdentity
