// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/plexusone/systemforge/identity/ent/loginsession"
)

// LoginSession is the model entity for the LoginSession schema.
type LoginSession struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Hex SHA-256 of the session token; the token itself is never stored
	TokenHash string `json:"token_hash,omitempty"`
	// Authenticated principal
	PrincipalID uuid.UUID `json:"principal_id,omitempty"`
	// Upstream provider used to sign in
	Provider string `json:"provider,omitempty"`
	// When the session was established
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Absolute session expiry
	ExpiresAt    time.Time `json:"expires_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LoginSession) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case loginsession.FieldTokenHash, loginsession.FieldProvider:
			values[i] = new(sql.NullString)
		case loginsession.FieldCreatedAt, loginsession.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		case loginsession.FieldID, loginsession.FieldPrincipalID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LoginSession fields.
func (_m *LoginSession) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case loginsession.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case loginsession.FieldTokenHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_hash", values[i])
			} else if value.Valid {
				_m.TokenHash = value.String
			}
		case loginsession.FieldPrincipalID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field principal_id", values[i])
			} else if value != nil {
				_m.PrincipalID = *value
			}
		case loginsession.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case loginsession.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case loginsession.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LoginSession.
// This includes values selected through modifiers, order, etc.
func (_m *LoginSession) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this LoginSession.
// Note that you need to call LoginSession.Unwrap() before calling this method if this LoginSession
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LoginSession) Update() *LoginSessionUpdateOne {
	return NewLoginSessionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LoginSession entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LoginSession) Unwrap() *LoginSession {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LoginSession is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LoginSession) String() string {
	var builder strings.Builder
	builder.WriteString("LoginSession(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("token_hash=")
	builder.WriteString(_m.TokenHash)
	builder.WriteString(", ")
	builder.WriteString("principal_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PrincipalID))
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// LoginSessions is a parsable slice of LoginSession.
type LoginSessions []*LoginSession
