// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/plexusone/systemforge/identity/ent/oauthapp"
	"github.com/plexusone/systemforge/identity/ent/oauthauthcode"
	"github.com/plexusone/systemforge/identity/ent/user"
)

// OAuthAuthCodeCreate is the builder for creating a OAuthAuthCode entity.
type OAuthAuthCodeCreate struct {
	config
	mutation *OAuthAuthCodeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCodeSignature sets the "code_signature" field.
func (_c *OAuthAuthCodeCreate) SetCodeSignature(v string) *OAuthAuthCodeCreate {
	_c.mutation.SetCodeSignature(v)
	return _c
}

// SetAppID sets the "app_id" field.
func (_c *OAuthAuthCodeCreate) SetAppID(v uuid.UUID) *OAuthAuthCodeCreate {
	_c.mutation.SetAppID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *OAuthAuthCodeCreate) SetUserID(v uuid.UUID) *OAuthAuthCodeCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *OAuthAuthCodeCreate) SetNillableUserID(v *uuid.UUID) *OAuthAuthCodeCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetSubject sets the "subject" field.
func (_c *OAuthAuthCodeCreate) SetSubject(v string) *OAuthAuthCodeCreate {
	_c.mutation.SetSubject(v)
	return _c
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_c *OAuthAuthCodeCreate) SetNillableSubject(v *string) *OAuthAuthCodeCreate {
	if v != nil {
		_c.SetSubject(*v)
	}
	return _c
}

// SetCodeChallenge sets the "code_challenge" field.
func (_c *OAuthAuthCodeCreate) SetCodeChallenge(v string) *OAuthAuthCodeCreate {
	_c.mutation.SetCodeChallenge(v)
	return _c
}

// SetNillableCodeChallenge sets the "code_challenge" field if the given value is not nil.
func (_c *OAuthAuthCodeCreate) SetNillableCodeChallenge(v *string) *OAuthAuthCodeCreate {
	if v != nil {
		_c.SetCodeChallenge(*v)
	}
	return _c
}

// SetCodeChallengeMethod sets the "code_challenge_method" field.
func (_c *OAuthAuthCodeCreate) SetCodeChallengeMethod(v string) *OAuthAuthCodeCreate {
	_c.mutation.SetCodeChallengeMethod(v)
	return _c
}

// SetNillableCodeChallengeMethod sets the "code_challenge_method" field if the given value is not nil.
func (_c *OAuthAuthCodeCreate) SetNillableCodeChallengeMethod(v *string) *OAuthAuthCodeCreate {
	if v != nil {
		_c.SetCodeChallengeMethod(*v)
	}
	return _c
}

// SetRedirectURI sets the "redirect_uri" field.
func (_c *OAuthAuthCodeCreate) SetRedirectURI(v string) *OAuthAuthCodeCreate {
	_c.mutation.SetRedirectURI(v)
	return _c
}

// SetScopes sets the "scopes" field.
func (_c *OAuthAuthCodeCreate) SetScopes(v []string) *OAuthAuthCodeCreate {
	_c.mutation.SetScopes(v)
	return _c
}

// SetState sets the "state" field.
func (_c *OAuthAuthCodeCreate) SetState(v string) *OAuthAuthCodeCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *OAuthAuthCodeCreate) SetNillableState(v *string) *OAuthAuthCodeCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetNonce sets the "nonce" field.
func (_c *OAuthAuthCodeCreate) SetNonce(v string) *OAuthAuthCodeCreate {
	_c.mutation.SetNonce(v)
	return _c
}

// SetNillableNonce sets the "nonce" field if the given value is not nil.
func (_c *OAuthAuthCodeCreate) SetNillableNonce(v *string) *OAuthAuthCodeCreate {
	if v != nil {
		_c.SetNonce(*v)
	}
	return _c
}

// SetRequestData sets the "request_data" field.
func (_c *OAuthAuthCodeCreate) SetRequestData(v string) *OAuthAuthCodeCreate {
	_c.mutation.SetRequestData(v)
	return _c
}

// SetNillableRequestData sets the "request_data" field if the given value is not nil.
func (_c *OAuthAuthCodeCreate) SetNillableRequestData(v *string) *OAuthAuthCodeCreate {
	if v != nil {
		_c.SetRequestData(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *OAuthAuthCodeCreate) SetExpiresAt(v time.Time) *OAuthAuthCodeCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetUsed sets the "used" field.
func (_c *OAuthAuthCodeCreate) SetUsed(v bool) *OAuthAuthCodeCreate {
	_c.mutation.SetUsed(v)
	return _c
}

// SetNillableUsed sets the "used" field if the given value is not nil.
func (_c *OAuthAuthCodeCreate) SetNillableUsed(v *bool) *OAuthAuthCodeCreate {
	if v != nil {
		_c.SetUsed(*v)
	}
	return _c
}

// SetUsedAt sets the "used_at" field.
func (_c *OAuthAuthCodeCreate) SetUsedAt(v time.Time) *OAuthAuthCodeCreate {
	_c.mutation.SetUsedAt(v)
	return _c
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_c *OAuthAuthCodeCreate) SetNillableUsedAt(v *time.Time) *OAuthAuthCodeCreate {
	if v != nil {
		_c.SetUsedAt(*v)
	}
	return _c
}

// SetClientIP sets the "client_ip" field.
func (_c *OAuthAuthCodeCreate) SetClientIP(v string) *OAuthAuthCodeCreate {
	_c.mutation.SetClientIP(v)
	return _c
}

// SetNillableClientIP sets the "client_ip" field if the given value is not nil.
func (_c *OAuthAuthCodeCreate) SetNillableClientIP(v *string) *OAuthAuthCodeCreate {
	if v != nil {
		_c.SetClientIP(*v)
	}
	return _c
}

// SetUserAgent sets the "user_agent" field.
func (_c *OAuthAuthCodeCreate) SetUserAgent(v string) *OAuthAuthCodeCreate {
	_c.mutation.SetUserAgent(v)
	return _c
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_c *OAuthAuthCodeCreate) SetNillableUserAgent(v *string) *OAuthAuthCodeCreate {
	if v != nil {
		_c.SetUserAgent(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OAuthAuthCodeCreate) SetCreatedAt(v time.Time) *OAuthAuthCodeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OAuthAuthCodeCreate) SetNillableCreatedAt(v *time.Time) *OAuthAuthCodeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OAuthAuthCodeCreate) SetID(v uuid.UUID) *OAuthAuthCodeCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *OAuthAuthCodeCreate) SetNillableID(v *uuid.UUID) *OAuthAuthCodeCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetApp sets the "app" edge to the OAuthApp entity.
func (_c *OAuthAuthCodeCreate) SetApp(v *OAuthApp) *OAuthAuthCodeCreate {
	return _c.SetAppID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *OAuthAuthCodeCreate) SetUser(v *User) *OAuthAuthCodeCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the OAuthAuthCodeMutation object of the builder.
func (_c *OAuthAuthCodeCreate) Mutation() *OAuthAuthCodeMutation {
	return _c.mutation
}

// Save creates the OAuthAuthCode in the database.
func (_c *OAuthAuthCodeCreate) Save(ctx context.Context) (*OAuthAuthCode, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OAuthAuthCodeCreate) SaveX(ctx context.Context) *OAuthAuthCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthAuthCodeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthAuthCodeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OAuthAuthCodeCreate) defaults() {
	if _, ok := _c.mutation.CodeChallengeMethod(); !ok {
		v := oauthauthcode.DefaultCodeChallengeMethod
		_c.mutation.SetCodeChallengeMethod(v)
	}
	if _, ok := _c.mutation.Scopes(); !ok {
		v := oauthauthcode.DefaultScopes
		_c.mutation.SetScopes(v)
	}
	if _, ok := _c.mutation.Used(); !ok {
		v := oauthauthcode.DefaultUsed
		_c.mutation.SetUsed(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := oauthauthcode.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := oauthauthcode.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OAuthAuthCodeCreate) check() error {
	if _, ok := _c.mutation.CodeSignature(); !ok {
		return &ValidationError{Name: "code_signature", err: errors.New(`ent: missing required field "OAuthAuthCode.code_signature"`)}
	}
	if _, ok := _c.mutation.AppID(); !ok {
		return &ValidationError{Name: "app_id", err: errors.New(`ent: missing required field "OAuthAuthCode.app_id"`)}
	}
	if _, ok := _c.mutation.RedirectURI(); !ok {
		return &ValidationError{Name: "redirect_uri", err: errors.New(`ent: missing required field "OAuthAuthCode.redirect_uri"`)}
	}
	if _, ok := _c.mutation.Scopes(); !ok {
		return &ValidationError{Name: "scopes", err: errors.New(`ent: missing required field "OAuthAuthCode.scopes"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "OAuthAuthCode.expires_at"`)}
	}
	if _, ok := _c.mutation.Used(); !ok {
		return &ValidationError{Name: "used", err: errors.New(`ent: missing required field "OAuthAuthCode.used"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OAuthAuthCode.created_at"`)}
	}
	if len(_c.mutation.AppIDs()) == 0 {
		return &ValidationError{Name: "app", err: errors.New(`ent: missing required edge "OAuthAuthCode.app"`)}
	}
	return nil
}

func (_c *OAuthAuthCodeCreate) sqlSave(ctx context.Context) (*OAuthAuthCode, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OAuthAuthCodeCreate) createSpec() (*OAuthAuthCode, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuthAuthCode{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oauthauthcode.Table, sqlgraph.NewFieldSpec(oauthauthcode.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CodeSignature(); ok {
		_spec.SetField(oauthauthcode.FieldCodeSignature, field.TypeString, value)
		_node.CodeSignature = value
	}
	if value, ok := _c.mutation.Subject(); ok {
		_spec.SetField(oauthauthcode.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := _c.mutation.CodeChallenge(); ok {
		_spec.SetField(oauthauthcode.FieldCodeChallenge, field.TypeString, value)
		_node.CodeChallenge = value
	}
	if value, ok := _c.mutation.CodeChallengeMethod(); ok {
		_spec.SetField(oauthauthcode.FieldCodeChallengeMethod, field.TypeString, value)
		_node.CodeChallengeMethod = value
	}
	if value, ok := _c.mutation.RedirectURI(); ok {
		_spec.SetField(oauthauthcode.FieldRedirectURI, field.TypeString, value)
		_node.RedirectURI = value
	}
	if value, ok := _c.mutation.Scopes(); ok {
		_spec.SetField(oauthauthcode.FieldScopes, field.TypeJSON, value)
		_node.Scopes = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(oauthauthcode.FieldState, field.TypeString, value)
		_node.State = value
	}
	if value, ok := _c.mutation.Nonce(); ok {
		_spec.SetField(oauthauthcode.FieldNonce, field.TypeString, value)
		_node.Nonce = value
	}
	if value, ok := _c.mutation.RequestData(); ok {
		_spec.SetField(oauthauthcode.FieldRequestData, field.TypeString, value)
		_node.RequestData = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthauthcode.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.Used(); ok {
		_spec.SetField(oauthauthcode.FieldUsed, field.TypeBool, value)
		_node.Used = value
	}
	if value, ok := _c.mutation.UsedAt(); ok {
		_spec.SetField(oauthauthcode.FieldUsedAt, field.TypeTime, value)
		_node.UsedAt = &value
	}
	if value, ok := _c.mutation.ClientIP(); ok {
		_spec.SetField(oauthauthcode.FieldClientIP, field.TypeString, value)
		_node.ClientIP = value
	}
	if value, ok := _c.mutation.UserAgent(); ok {
		_spec.SetField(oauthauthcode.FieldUserAgent, field.TypeString, value)
		_node.UserAgent = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(oauthauthcode.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.AppIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthauthcode.AppTable,
			Columns: []string{oauthauthcode.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthapp.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AppID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthauthcode.UserTable,
			Columns: []string{oauthauthcode.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OAuthAuthCode.Create().
//		SetCodeSignature(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OAuthAuthCodeUpsert) {
//			SetCodeSignature(v+v).
//		}).
//		Exec(ctx)
func (_c *OAuthAuthCodeCreate) OnConflict(opts ...sql.ConflictOption) *OAuthAuthCodeUpsertOne {
	_c.conflict = opts
	return &OAuthAuthCodeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OAuthAuthCode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OAuthAuthCodeCreate) OnConflictColumns(columns ...string) *OAuthAuthCodeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OAuthAuthCodeUpsertOne{
		create: _c,
	}
}

type (
	// OAuthAuthCodeUpsertOne is the builder for "upsert"-ing
	//  one OAuthAuthCode node.
	OAuthAuthCodeUpsertOne struct {
		create *OAuthAuthCodeCreate
	}

	// OAuthAuthCodeUpsert is the "OnConflict" setter.
	OAuthAuthCodeUpsert struct {
		*sql.UpdateSet
	}
)

// SetCodeSignature sets the "code_signature" field.
func (u *OAuthAuthCodeUpsert) SetCodeSignature(v string) *OAuthAuthCodeUpsert {
	u.Set(oauthauthcode.FieldCodeSignature, v)
	return u
}

// UpdateCodeSignature sets the "code_signature" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsert) UpdateCodeSignature() *OAuthAuthCodeUpsert {
	u.SetExcluded(oauthauthcode.FieldCodeSignature)
	return u
}

// SetAppID sets the "app_id" field.
func (u *OAuthAuthCodeUpsert) SetAppID(v uuid.UUID) *OAuthAuthCodeUpsert {
	u.Set(oauthauthcode.FieldAppID, v)
	return u
}

// UpdateAppID sets the "app_id" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsert) UpdateAppID() *OAuthAuthCodeUpsert {
	u.SetExcluded(oauthauthcode.FieldAppID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *OAuthAuthCodeUpsert) SetUserID(v uuid.UUID) *OAuthAuthCodeUpsert {
	u.Set(oauthauthcode.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsert) UpdateUserID() *OAuthAuthCodeUpsert {
	u.SetExcluded(oauthauthcode.FieldUserID)
	return u
}

// ClearUserID clears the value of the "user_id" field.
func (u *OAuthAuthCodeUpsert) ClearUserID() *OAuthAuthCodeUpsert {
	u.SetNull(oauthauthcode.FieldUserID)
	return u
}

// SetSubject sets the "subject" field.
func (u *OAuthAuthCodeUpsert) SetSubject(v string) *OAuthAuthCodeUpsert {
	u.Set(oauthauthcode.FieldSubject, v)
	return u
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsert) UpdateSubject() *OAuthAuthCodeUpsert {
	u.SetExcluded(oauthauthcode.FieldSubject)
	return u
}

// ClearSubject clears the value of the "subject" field.
func (u *OAuthAuthCodeUpsert) ClearSubject() *OAuthAuthCodeUpsert {
	u.SetNull(oauthauthcode.FieldSubject)
	return u
}

// SetCodeChallenge sets the "code_challenge" field.
func (u *OAuthAuthCodeUpsert) SetCodeChallenge(v string) *OAuthAuthCodeUpsert {
	u.Set(oauthauthcode.FieldCodeChallenge, v)
	return u
}

// UpdateCodeChallenge sets the "code_challenge" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsert) UpdateCodeChallenge() *OAuthAuthCodeUpsert {
	u.SetExcluded(oauthauthcode.FieldCodeChallenge)
	return u
}

// ClearCodeChallenge clears the value of the "code_challenge" field.
func (u *OAuthAuthCodeUpsert) ClearCodeChallenge() *OAuthAuthCodeUpsert {
	u.SetNull(oauthauthcode.FieldCodeChallenge)
	return u
}

// SetCodeChallengeMethod sets the "code_challenge_method" field.
func (u *OAuthAuthCodeUpsert) SetCodeChallengeMethod(v string) *OAuthAuthCodeUpsert {
	u.Set(oauthauthcode.FieldCodeChallengeMethod, v)
	return u
}

// UpdateCodeChallengeMethod sets the "code_challenge_method" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsert) UpdateCodeChallengeMethod() *OAuthAuthCodeUpsert {
	u.SetExcluded(oauthauthcode.FieldCodeChallengeMethod)
	return u
}

// ClearCodeChallengeMethod clears the value of the "code_challenge_method" field.
func (u *OAuthAuthCodeUpsert) ClearCodeChallengeMethod() *OAuthAuthCodeUpsert {
	u.SetNull(oauthauthcode.FieldCodeChallengeMethod)
	return u
}

// SetRedirectURI sets the "redirect_uri" field.
func (u *OAuthAuthCodeUpsert) SetRedirectURI(v string) *OAuthAuthCodeUpsert {
	u.Set(oauthauthcode.FieldRedirectURI, v)
	return u
}

// UpdateRedirectURI sets the "redirect_uri" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsert) UpdateRedirectURI() *OAuthAuthCodeUpsert {
	u.SetExcluded(oauthauthcode.FieldRedirectURI)
	return u
}

// SetScopes sets the "scopes" field.
func (u *OAuthAuthCodeUpsert) SetScopes(v []string) *OAuthAuthCodeUpsert {
	u.Set(oauthauthcode.FieldScopes, v)
	return u
}

// UpdateScopes sets the "scopes" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsert) UpdateScopes() *OAuthAuthCodeUpsert {
	u.SetExcluded(oauthauthcode.FieldScopes)
	return u
}

// SetState sets the "state" field.
func (u *OAuthAuthCodeUpsert) SetState(v string) *OAuthAuthCodeUpsert {
	u.Set(oauthauthcode.FieldState, v)
	return u
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsert) UpdateState() *OAuthAuthCodeUpsert {
	u.SetExcluded(oauthauthcode.FieldState)
	return u
}

// ClearState clears the value of the "state" field.
func (u *OAuthAuthCodeUpsert) ClearState() *OAuthAuthCodeUpsert {
	u.SetNull(oauthauthcode.FieldState)
	return u
}

// SetNonce sets the "nonce" field.
func (u *OAuthAuthCodeUpsert) SetNonce(v string) *OAuthAuthCodeUpsert {
	u.Set(oauthauthcode.FieldNonce, v)
	return u
}

// UpdateNonce sets the "nonce" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsert) UpdateNonce() *OAuthAuthCodeUpsert {
	u.SetExcluded(oauthauthcode.FieldNonce)
	return u
}

// ClearNonce clears the value of the "nonce" field.
func (u *OAuthAuthCodeUpsert) ClearNonce() *OAuthAuthCodeUpsert {
	u.SetNull(oauthauthcode.FieldNonce)
	return u
}

// SetRequestData sets the "request_data" field.
func (u *OAuthAuthCodeUpsert) SetRequestData(v string) *OAuthAuthCodeUpsert {
	u.Set(oauthauthcode.FieldRequestData, v)
	return u
}

// UpdateRequestData sets the "request_data" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsert) UpdateRequestData() *OAuthAuthCodeUpsert {
	u.SetExcluded(oauthauthcode.FieldRequestData)
	return u
}

// ClearRequestData clears the value of the "request_data" field.
func (u *OAuthAuthCodeUpsert) ClearRequestData() *OAuthAuthCodeUpsert {
	u.SetNull(oauthauthcode.FieldRequestData)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *OAuthAuthCodeUpsert) SetExpiresAt(v time.Time) *OAuthAuthCodeUpsert {
	u.Set(oauthauthcode.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsert) UpdateExpiresAt() *OAuthAuthCodeUpsert {
	u.SetExcluded(oauthauthcode.FieldExpiresAt)
	return u
}

// SetUsed sets the "used" field.
func (u *OAuthAuthCodeUpsert) SetUsed(v bool) *OAuthAuthCodeUpsert {
	u.Set(oauthauthcode.FieldUsed, v)
	return u
}

// UpdateUsed sets the "used" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsert) UpdateUsed() *OAuthAuthCodeUpsert {
	u.SetExcluded(oauthauthcode.FieldUsed)
	return u
}

// SetUsedAt sets the "used_at" field.
func (u *OAuthAuthCodeUpsert) SetUsedAt(v time.Time) *OAuthAuthCodeUpsert {
	u.Set(oauthauthcode.FieldUsedAt, v)
	return u
}

// UpdateUsedAt sets the "used_at" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsert) UpdateUsedAt() *OAuthAuthCodeUpsert {
	u.SetExcluded(oauthauthcode.FieldUsedAt)
	return u
}

// ClearUsedAt clears the value of the "used_at" field.
func (u *OAuthAuthCodeUpsert) ClearUsedAt() *OAuthAuthCodeUpsert {
	u.SetNull(oauthauthcode.FieldUsedAt)
	return u
}

// SetClientIP sets the "client_ip" field.
func (u *OAuthAuthCodeUpsert) SetClientIP(v string) *OAuthAuthCodeUpsert {
	u.Set(oauthauthcode.FieldClientIP, v)
	return u
}

// UpdateClientIP sets the "client_ip" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsert) UpdateClientIP() *OAuthAuthCodeUpsert {
	u.SetExcluded(oauthauthcode.FieldClientIP)
	return u
}

// ClearClientIP clears the value of the "client_ip" field.
func (u *OAuthAuthCodeUpsert) ClearClientIP() *OAuthAuthCodeUpsert {
	u.SetNull(oauthauthcode.FieldClientIP)
	return u
}

// SetUserAgent sets the "user_agent" field.
func (u *OAuthAuthCodeUpsert) SetUserAgent(v string) *OAuthAuthCodeUpsert {
	u.Set(oauthauthcode.FieldUserAgent, v)
	return u
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsert) UpdateUserAgent() *OAuthAuthCodeUpsert {
	u.SetExcluded(oauthauthcode.FieldUserAgent)
	return u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (u *OAuthAuthCodeUpsert) ClearUserAgent() *OAuthAuthCodeUpsert {
	u.SetNull(oauthauthcode.FieldUserAgent)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.OAuthAuthCode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(oauthauthcode.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OAuthAuthCodeUpsertOne) UpdateNewValues() *OAuthAuthCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(oauthauthcode.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(oauthauthcode.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OAuthAuthCode.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OAuthAuthCodeUpsertOne) Ignore() *OAuthAuthCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OAuthAuthCodeUpsertOne) DoNothing() *OAuthAuthCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OAuthAuthCodeCreate.OnConflict
// documentation for more info.
func (u *OAuthAuthCodeUpsertOne) Update(set func(*OAuthAuthCodeUpsert)) *OAuthAuthCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OAuthAuthCodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetCodeSignature sets the "code_signature" field.
func (u *OAuthAuthCodeUpsertOne) SetCodeSignature(v string) *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.SetCodeSignature(v)
	})
}

// UpdateCodeSignature sets the "code_signature" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsertOne) UpdateCodeSignature() *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.UpdateCodeSignature()
	})
}

// SetAppID sets the "app_id" field.
func (u *OAuthAuthCodeUpsertOne) SetAppID(v uuid.UUID) *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.SetAppID(v)
	})
}

// UpdateAppID sets the "app_id" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsertOne) UpdateAppID() *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.UpdateAppID()
	})
}

// SetUserID sets the "user_id" field.
func (u *OAuthAuthCodeUpsertOne) SetUserID(v uuid.UUID) *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsertOne) UpdateUserID() *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *OAuthAuthCodeUpsertOne) ClearUserID() *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.ClearUserID()
	})
}

// SetSubject sets the "subject" field.
func (u *OAuthAuthCodeUpsertOne) SetSubject(v string) *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.SetSubject(v)
	})
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsertOne) UpdateSubject() *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.UpdateSubject()
	})
}

// ClearSubject clears the value of the "subject" field.
func (u *OAuthAuthCodeUpsertOne) ClearSubject() *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.ClearSubject()
	})
}

// SetCodeChallenge sets the "code_challenge" field.
func (u *OAuthAuthCodeUpsertOne) SetCodeChallenge(v string) *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.SetCodeChallenge(v)
	})
}

// UpdateCodeChallenge sets the "code_challenge" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsertOne) UpdateCodeChallenge() *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.UpdateCodeChallenge()
	})
}

// ClearCodeChallenge clears the value of the "code_challenge" field.
func (u *OAuthAuthCodeUpsertOne) ClearCodeChallenge() *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.ClearCodeChallenge()
	})
}

// SetCodeChallengeMethod sets the "code_challenge_method" field.
func (u *OAuthAuthCodeUpsertOne) SetCodeChallengeMethod(v string) *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.SetCodeChallengeMethod(v)
	})
}

// UpdateCodeChallengeMethod sets the "code_challenge_method" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsertOne) UpdateCodeChallengeMethod() *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.UpdateCodeChallengeMethod()
	})
}

// ClearCodeChallengeMethod clears the value of the "code_challenge_method" field.
func (u *OAuthAuthCodeUpsertOne) ClearCodeChallengeMethod() *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.ClearCodeChallengeMethod()
	})
}

// SetRedirectURI sets the "redirect_uri" field.
func (u *OAuthAuthCodeUpsertOne) SetRedirectURI(v string) *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.SetRedirectURI(v)
	})
}

// UpdateRedirectURI sets the "redirect_uri" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsertOne) UpdateRedirectURI() *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.UpdateRedirectURI()
	})
}

// SetScopes sets the "scopes" field.
func (u *OAuthAuthCodeUpsertOne) SetScopes(v []string) *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.SetScopes(v)
	})
}

// UpdateScopes sets the "scopes" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsertOne) UpdateScopes() *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.UpdateScopes()
	})
}

// SetState sets the "state" field.
func (u *OAuthAuthCodeUpsertOne) SetState(v string) *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsertOne) UpdateState() *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.UpdateState()
	})
}

// ClearState clears the value of the "state" field.
func (u *OAuthAuthCodeUpsertOne) ClearState() *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.ClearState()
	})
}

// SetNonce sets the "nonce" field.
func (u *OAuthAuthCodeUpsertOne) SetNonce(v string) *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.SetNonce(v)
	})
}

// UpdateNonce sets the "nonce" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsertOne) UpdateNonce() *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.UpdateNonce()
	})
}

// ClearNonce clears the value of the "nonce" field.
func (u *OAuthAuthCodeUpsertOne) ClearNonce() *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.ClearNonce()
	})
}

// SetRequestData sets the "request_data" field.
func (u *OAuthAuthCodeUpsertOne) SetRequestData(v string) *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.SetRequestData(v)
	})
}

// UpdateRequestData sets the "request_data" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsertOne) UpdateRequestData() *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.UpdateRequestData()
	})
}

// ClearRequestData clears the value of the "request_data" field.
func (u *OAuthAuthCodeUpsertOne) ClearRequestData() *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.ClearRequestData()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *OAuthAuthCodeUpsertOne) SetExpiresAt(v time.Time) *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsertOne) UpdateExpiresAt() *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetUsed sets the "used" field.
func (u *OAuthAuthCodeUpsertOne) SetUsed(v bool) *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.SetUsed(v)
	})
}

// UpdateUsed sets the "used" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsertOne) UpdateUsed() *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.UpdateUsed()
	})
}

// SetUsedAt sets the "used_at" field.
func (u *OAuthAuthCodeUpsertOne) SetUsedAt(v time.Time) *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.SetUsedAt(v)
	})
}

// UpdateUsedAt sets the "used_at" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsertOne) UpdateUsedAt() *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.UpdateUsedAt()
	})
}

// ClearUsedAt clears the value of the "used_at" field.
func (u *OAuthAuthCodeUpsertOne) ClearUsedAt() *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.ClearUsedAt()
	})
}

// SetClientIP sets the "client_ip" field.
func (u *OAuthAuthCodeUpsertOne) SetClientIP(v string) *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.SetClientIP(v)
	})
}

// UpdateClientIP sets the "client_ip" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsertOne) UpdateClientIP() *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.UpdateClientIP()
	})
}

// ClearClientIP clears the value of the "client_ip" field.
func (u *OAuthAuthCodeUpsertOne) ClearClientIP() *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.ClearClientIP()
	})
}

// SetUserAgent sets the "user_agent" field.
func (u *OAuthAuthCodeUpsertOne) SetUserAgent(v string) *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.SetUserAgent(v)
	})
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsertOne) UpdateUserAgent() *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.UpdateUserAgent()
	})
}

// ClearUserAgent clears the value of the "user_agent" field.
func (u *OAuthAuthCodeUpsertOne) ClearUserAgent() *OAuthAuthCodeUpsertOne {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.ClearUserAgent()
	})
}

// Exec executes the query.
func (u *OAuthAuthCodeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OAuthAuthCodeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OAuthAuthCodeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OAuthAuthCodeUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: OAuthAuthCodeUpsertOne.ID is not supported by MySQL driver. Use OAuthAuthCodeUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OAuthAuthCodeUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OAuthAuthCodeCreateBulk is the builder for creating many OAuthAuthCode entities in bulk.
type OAuthAuthCodeCreateBulk struct {
	config
	err      error
	builders []*OAuthAuthCodeCreate
	conflict []sql.ConflictOption
}

// Save creates the OAuthAuthCode entities in the database.
func (_c *OAuthAuthCodeCreateBulk) Save(ctx context.Context) ([]*OAuthAuthCode, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OAuthAuthCode, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuthAuthCodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OAuthAuthCodeCreateBulk) SaveX(ctx context.Context) []*OAuthAuthCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthAuthCodeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthAuthCodeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OAuthAuthCode.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OAuthAuthCodeUpsert) {
//			SetCodeSignature(v+v).
//		}).
//		Exec(ctx)
func (_c *OAuthAuthCodeCreateBulk) OnConflict(opts ...sql.ConflictOption) *OAuthAuthCodeUpsertBulk {
	_c.conflict = opts
	return &OAuthAuthCodeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OAuthAuthCode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OAuthAuthCodeCreateBulk) OnConflictColumns(columns ...string) *OAuthAuthCodeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OAuthAuthCodeUpsertBulk{
		create: _c,
	}
}

// OAuthAuthCodeUpsertBulk is the builder for "upsert"-ing
// a bulk of OAuthAuthCode nodes.
type OAuthAuthCodeUpsertBulk struct {
	create *OAuthAuthCodeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OAuthAuthCode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(oauthauthcode.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OAuthAuthCodeUpsertBulk) UpdateNewValues() *OAuthAuthCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(oauthauthcode.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(oauthauthcode.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OAuthAuthCode.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OAuthAuthCodeUpsertBulk) Ignore() *OAuthAuthCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OAuthAuthCodeUpsertBulk) DoNothing() *OAuthAuthCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OAuthAuthCodeCreateBulk.OnConflict
// documentation for more info.
func (u *OAuthAuthCodeUpsertBulk) Update(set func(*OAuthAuthCodeUpsert)) *OAuthAuthCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OAuthAuthCodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetCodeSignature sets the "code_signature" field.
func (u *OAuthAuthCodeUpsertBulk) SetCodeSignature(v string) *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.SetCodeSignature(v)
	})
}

// UpdateCodeSignature sets the "code_signature" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsertBulk) UpdateCodeSignature() *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.UpdateCodeSignature()
	})
}

// SetAppID sets the "app_id" field.
func (u *OAuthAuthCodeUpsertBulk) SetAppID(v uuid.UUID) *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.SetAppID(v)
	})
}

// UpdateAppID sets the "app_id" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsertBulk) UpdateAppID() *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.UpdateAppID()
	})
}

// SetUserID sets the "user_id" field.
func (u *OAuthAuthCodeUpsertBulk) SetUserID(v uuid.UUID) *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsertBulk) UpdateUserID() *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *OAuthAuthCodeUpsertBulk) ClearUserID() *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.ClearUserID()
	})
}

// SetSubject sets the "subject" field.
func (u *OAuthAuthCodeUpsertBulk) SetSubject(v string) *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.SetSubject(v)
	})
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsertBulk) UpdateSubject() *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.UpdateSubject()
	})
}

// ClearSubject clears the value of the "subject" field.
func (u *OAuthAuthCodeUpsertBulk) ClearSubject() *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.ClearSubject()
	})
}

// SetCodeChallenge sets the "code_challenge" field.
func (u *OAuthAuthCodeUpsertBulk) SetCodeChallenge(v string) *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.SetCodeChallenge(v)
	})
}

// UpdateCodeChallenge sets the "code_challenge" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsertBulk) UpdateCodeChallenge() *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.UpdateCodeChallenge()
	})
}

// ClearCodeChallenge clears the value of the "code_challenge" field.
func (u *OAuthAuthCodeUpsertBulk) ClearCodeChallenge() *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.ClearCodeChallenge()
	})
}

// SetCodeChallengeMethod sets the "code_challenge_method" field.
func (u *OAuthAuthCodeUpsertBulk) SetCodeChallengeMethod(v string) *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.SetCodeChallengeMethod(v)
	})
}

// UpdateCodeChallengeMethod sets the "code_challenge_method" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsertBulk) UpdateCodeChallengeMethod() *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.UpdateCodeChallengeMethod()
	})
}

// ClearCodeChallengeMethod clears the value of the "code_challenge_method" field.
func (u *OAuthAuthCodeUpsertBulk) ClearCodeChallengeMethod() *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.ClearCodeChallengeMethod()
	})
}

// SetRedirectURI sets the "redirect_uri" field.
func (u *OAuthAuthCodeUpsertBulk) SetRedirectURI(v string) *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.SetRedirectURI(v)
	})
}

// UpdateRedirectURI sets the "redirect_uri" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsertBulk) UpdateRedirectURI() *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.UpdateRedirectURI()
	})
}

// SetScopes sets the "scopes" field.
func (u *OAuthAuthCodeUpsertBulk) SetScopes(v []string) *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.SetScopes(v)
	})
}

// UpdateScopes sets the "scopes" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsertBulk) UpdateScopes() *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.UpdateScopes()
	})
}

// SetState sets the "state" field.
func (u *OAuthAuthCodeUpsertBulk) SetState(v string) *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsertBulk) UpdateState() *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.UpdateState()
	})
}

// ClearState clears the value of the "state" field.
func (u *OAuthAuthCodeUpsertBulk) ClearState() *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.ClearState()
	})
}

// SetNonce sets the "nonce" field.
func (u *OAuthAuthCodeUpsertBulk) SetNonce(v string) *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.SetNonce(v)
	})
}

// UpdateNonce sets the "nonce" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsertBulk) UpdateNonce() *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.UpdateNonce()
	})
}

// ClearNonce clears the value of the "nonce" field.
func (u *OAuthAuthCodeUpsertBulk) ClearNonce() *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.ClearNonce()
	})
}

// SetRequestData sets the "request_data" field.
func (u *OAuthAuthCodeUpsertBulk) SetRequestData(v string) *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.SetRequestData(v)
	})
}

// UpdateRequestData sets the "request_data" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsertBulk) UpdateRequestData() *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.UpdateRequestData()
	})
}

// ClearRequestData clears the value of the "request_data" field.
func (u *OAuthAuthCodeUpsertBulk) ClearRequestData() *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.ClearRequestData()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *OAuthAuthCodeUpsertBulk) SetExpiresAt(v time.Time) *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsertBulk) UpdateExpiresAt() *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetUsed sets the "used" field.
func (u *OAuthAuthCodeUpsertBulk) SetUsed(v bool) *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.SetUsed(v)
	})
}

// UpdateUsed sets the "used" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsertBulk) UpdateUsed() *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.UpdateUsed()
	})
}

// SetUsedAt sets the "used_at" field.
func (u *OAuthAuthCodeUpsertBulk) SetUsedAt(v time.Time) *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.SetUsedAt(v)
	})
}

// UpdateUsedAt sets the "used_at" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsertBulk) UpdateUsedAt() *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.UpdateUsedAt()
	})
}

// ClearUsedAt clears the value of the "used_at" field.
func (u *OAuthAuthCodeUpsertBulk) ClearUsedAt() *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.ClearUsedAt()
	})
}

// SetClientIP sets the "client_ip" field.
func (u *OAuthAuthCodeUpsertBulk) SetClientIP(v string) *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.SetClientIP(v)
	})
}

// UpdateClientIP sets the "client_ip" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsertBulk) UpdateClientIP() *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.UpdateClientIP()
	})
}

// ClearClientIP clears the value of the "client_ip" field.
func (u *OAuthAuthCodeUpsertBulk) ClearClientIP() *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.ClearClientIP()
	})
}

// SetUserAgent sets the "user_agent" field.
func (u *OAuthAuthCodeUpsertBulk) SetUserAgent(v string) *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.SetUserAgent(v)
	})
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *OAuthAuthCodeUpsertBulk) UpdateUserAgent() *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.UpdateUserAgent()
	})
}

// ClearUserAgent clears the value of the "user_agent" field.
func (u *OAuthAuthCodeUpsertBulk) ClearUserAgent() *OAuthAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthCodeUpsert) {
		s.ClearUserAgent()
	})
}

// Exec executes the query.
func (u *OAuthAuthCodeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OAuthAuthCodeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OAuthAuthCodeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OAuthAuthCodeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
