// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/plexusone/systemforge/identity/ent/agent"
	"github.com/plexusone/systemforge/identity/ent/application"
	"github.com/plexusone/systemforge/identity/ent/credential"
	"github.com/plexusone/systemforge/identity/ent/externalidentity"
	"github.com/plexusone/systemforge/identity/ent/human"
	"github.com/plexusone/systemforge/identity/ent/invite"
	"github.com/plexusone/systemforge/identity/ent/license"
	"github.com/plexusone/systemforge/identity/ent/listing"
	"github.com/plexusone/systemforge/identity/ent/organization"
	"github.com/plexusone/systemforge/identity/ent/predicate"
	"github.com/plexusone/systemforge/identity/ent/principal"
	"github.com/plexusone/systemforge/identity/ent/principalmembership"
	"github.com/plexusone/systemforge/identity/ent/principaltoken"
	"github.com/plexusone/systemforge/identity/ent/seatassignment"
	"github.com/plexusone/systemforge/identity/ent/serviceprincipal"
)

// PrincipalUpdate is the builder for updating Principal entities.
type PrincipalUpdate struct {
	config
	hooks    []Hook
	mutation *PrincipalMutation
}

// Where appends a list predicates to the PrincipalUpdate builder.
func (_u *PrincipalUpdate) Where(ps ...predicate.Principal) *PrincipalUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PrincipalUpdate) SetUpdatedAt(v time.Time) *PrincipalUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetIdentifier sets the "identifier" field.
func (_u *PrincipalUpdate) SetIdentifier(v string) *PrincipalUpdate {
	_u.mutation.SetIdentifier(v)
	return _u
}

// SetNillableIdentifier sets the "identifier" field if the given value is not nil.
func (_u *PrincipalUpdate) SetNillableIdentifier(v *string) *PrincipalUpdate {
	if v != nil {
		_u.SetIdentifier(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *PrincipalUpdate) SetDisplayName(v string) *PrincipalUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *PrincipalUpdate) SetNillableDisplayName(v *string) *PrincipalUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetOrganizationID sets the "organization_id" field.
func (_u *PrincipalUpdate) SetOrganizationID(v uuid.UUID) *PrincipalUpdate {
	_u.mutation.SetOrganizationID(v)
	return _u
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (_u *PrincipalUpdate) SetNillableOrganizationID(v *uuid.UUID) *PrincipalUpdate {
	if v != nil {
		_u.SetOrganizationID(*v)
	}
	return _u
}

// ClearOrganizationID clears the value of the "organization_id" field.
func (_u *PrincipalUpdate) ClearOrganizationID() *PrincipalUpdate {
	_u.mutation.ClearOrganizationID()
	return _u
}

// SetActive sets the "active" field.
func (_u *PrincipalUpdate) SetActive(v bool) *PrincipalUpdate {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *PrincipalUpdate) SetNillableActive(v *bool) *PrincipalUpdate {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetCapabilities sets the "capabilities" field.
func (_u *PrincipalUpdate) SetCapabilities(v map[string]bool) *PrincipalUpdate {
	_u.mutation.SetCapabilities(v)
	return _u
}

// SetAllowedScopes sets the "allowed_scopes" field.
func (_u *PrincipalUpdate) SetAllowedScopes(v []string) *PrincipalUpdate {
	_u.mutation.SetAllowedScopes(v)
	return _u
}

// AppendAllowedScopes appends value to the "allowed_scopes" field.
func (_u *PrincipalUpdate) AppendAllowedScopes(v []string) *PrincipalUpdate {
	_u.mutation.AppendAllowedScopes(v)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *PrincipalUpdate) SetMetadata(v map[string]interface{}) *PrincipalUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *PrincipalUpdate) ClearMetadata() *PrincipalUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_u *PrincipalUpdate) SetOrganization(v *Organization) *PrincipalUpdate {
	return _u.SetOrganizationID(v.ID)
}

// SetHumanID sets the "human" edge to the Human entity by ID.
func (_u *PrincipalUpdate) SetHumanID(id uuid.UUID) *PrincipalUpdate {
	_u.mutation.SetHumanID(id)
	return _u
}

// SetNillableHumanID sets the "human" edge to the Human entity by ID if the given value is not nil.
func (_u *PrincipalUpdate) SetNillableHumanID(id *uuid.UUID) *PrincipalUpdate {
	if id != nil {
		_u = _u.SetHumanID(*id)
	}
	return _u
}

// SetHuman sets the "human" edge to the Human entity.
func (_u *PrincipalUpdate) SetHuman(v *Human) *PrincipalUpdate {
	return _u.SetHumanID(v.ID)
}

// SetApplicationID sets the "application" edge to the Application entity by ID.
func (_u *PrincipalUpdate) SetApplicationID(id uuid.UUID) *PrincipalUpdate {
	_u.mutation.SetApplicationID(id)
	return _u
}

// SetNillableApplicationID sets the "application" edge to the Application entity by ID if the given value is not nil.
func (_u *PrincipalUpdate) SetNillableApplicationID(id *uuid.UUID) *PrincipalUpdate {
	if id != nil {
		_u = _u.SetApplicationID(*id)
	}
	return _u
}

// SetApplication sets the "application" edge to the Application entity.
func (_u *PrincipalUpdate) SetApplication(v *Application) *PrincipalUpdate {
	return _u.SetApplicationID(v.ID)
}

// SetAgentID sets the "agent" edge to the Agent entity by ID.
func (_u *PrincipalUpdate) SetAgentID(id uuid.UUID) *PrincipalUpdate {
	_u.mutation.SetAgentID(id)
	return _u
}

// SetNillableAgentID sets the "agent" edge to the Agent entity by ID if the given value is not nil.
func (_u *PrincipalUpdate) SetNillableAgentID(id *uuid.UUID) *PrincipalUpdate {
	if id != nil {
		_u = _u.SetAgentID(*id)
	}
	return _u
}

// SetAgent sets the "agent" edge to the Agent entity.
func (_u *PrincipalUpdate) SetAgent(v *Agent) *PrincipalUpdate {
	return _u.SetAgentID(v.ID)
}

// SetServicePrincipalID sets the "service_principal" edge to the ServicePrincipal entity by ID.
func (_u *PrincipalUpdate) SetServicePrincipalID(id uuid.UUID) *PrincipalUpdate {
	_u.mutation.SetServicePrincipalID(id)
	return _u
}

// SetNillableServicePrincipalID sets the "service_principal" edge to the ServicePrincipal entity by ID if the given value is not nil.
func (_u *PrincipalUpdate) SetNillableServicePrincipalID(id *uuid.UUID) *PrincipalUpdate {
	if id != nil {
		_u = _u.SetServicePrincipalID(*id)
	}
	return _u
}

// SetServicePrincipal sets the "service_principal" edge to the ServicePrincipal entity.
func (_u *PrincipalUpdate) SetServicePrincipal(v *ServicePrincipal) *PrincipalUpdate {
	return _u.SetServicePrincipalID(v.ID)
}

// AddCredentialIDs adds the "credentials" edge to the Credential entity by IDs.
func (_u *PrincipalUpdate) AddCredentialIDs(ids ...uuid.UUID) *PrincipalUpdate {
	_u.mutation.AddCredentialIDs(ids...)
	return _u
}

// AddCredentials adds the "credentials" edges to the Credential entity.
func (_u *PrincipalUpdate) AddCredentials(v ...*Credential) *PrincipalUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCredentialIDs(ids...)
}

// AddExternalIdentityIDs adds the "external_identities" edge to the ExternalIdentity entity by IDs.
func (_u *PrincipalUpdate) AddExternalIdentityIDs(ids ...uuid.UUID) *PrincipalUpdate {
	_u.mutation.AddExternalIdentityIDs(ids...)
	return _u
}

// AddExternalIdentities adds the "external_identities" edges to the ExternalIdentity entity.
func (_u *PrincipalUpdate) AddExternalIdentities(v ...*ExternalIdentity) *PrincipalUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddExternalIdentityIDs(ids...)
}

// AddPrincipalTokenIDs adds the "principal_tokens" edge to the PrincipalToken entity by IDs.
func (_u *PrincipalUpdate) AddPrincipalTokenIDs(ids ...uuid.UUID) *PrincipalUpdate {
	_u.mutation.AddPrincipalTokenIDs(ids...)
	return _u
}

// AddPrincipalTokens adds the "principal_tokens" edges to the PrincipalToken entity.
func (_u *PrincipalUpdate) AddPrincipalTokens(v ...*PrincipalToken) *PrincipalUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPrincipalTokenIDs(ids...)
}

// AddPrincipalMembershipIDs adds the "principal_memberships" edge to the PrincipalMembership entity by IDs.
func (_u *PrincipalUpdate) AddPrincipalMembershipIDs(ids ...uuid.UUID) *PrincipalUpdate {
	_u.mutation.AddPrincipalMembershipIDs(ids...)
	return _u
}

// AddPrincipalMemberships adds the "principal_memberships" edges to the PrincipalMembership entity.
func (_u *PrincipalUpdate) AddPrincipalMemberships(v ...*PrincipalMembership) *PrincipalUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPrincipalMembershipIDs(ids...)
}

// AddOwnedOrganizationIDs adds the "owned_organizations" edge to the Organization entity by IDs.
func (_u *PrincipalUpdate) AddOwnedOrganizationIDs(ids ...uuid.UUID) *PrincipalUpdate {
	_u.mutation.AddOwnedOrganizationIDs(ids...)
	return _u
}

// AddOwnedOrganizations adds the "owned_organizations" edges to the Organization entity.
func (_u *PrincipalUpdate) AddOwnedOrganizations(v ...*Organization) *PrincipalUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOwnedOrganizationIDs(ids...)
}

// AddSentInviteIDs adds the "sent_invites" edge to the Invite entity by IDs.
func (_u *PrincipalUpdate) AddSentInviteIDs(ids ...uuid.UUID) *PrincipalUpdate {
	_u.mutation.AddSentInviteIDs(ids...)
	return _u
}

// AddSentInvites adds the "sent_invites" edges to the Invite entity.
func (_u *PrincipalUpdate) AddSentInvites(v ...*Invite) *PrincipalUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSentInviteIDs(ids...)
}

// AddOwnedListingIDs adds the "owned_listings" edge to the Listing entity by IDs.
func (_u *PrincipalUpdate) AddOwnedListingIDs(ids ...uuid.UUID) *PrincipalUpdate {
	_u.mutation.AddOwnedListingIDs(ids...)
	return _u
}

// AddOwnedListings adds the "owned_listings" edges to the Listing entity.
func (_u *PrincipalUpdate) AddOwnedListings(v ...*Listing) *PrincipalUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOwnedListingIDs(ids...)
}

// AddPurchasedLicenseIDs adds the "purchased_licenses" edge to the License entity by IDs.
func (_u *PrincipalUpdate) AddPurchasedLicenseIDs(ids ...uuid.UUID) *PrincipalUpdate {
	_u.mutation.AddPurchasedLicenseIDs(ids...)
	return _u
}

// AddPurchasedLicenses adds the "purchased_licenses" edges to the License entity.
func (_u *PrincipalUpdate) AddPurchasedLicenses(v ...*License) *PrincipalUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPurchasedLicenseIDs(ids...)
}

// AddSeatAssignmentIDs adds the "seat_assignments" edge to the SeatAssignment entity by IDs.
func (_u *PrincipalUpdate) AddSeatAssignmentIDs(ids ...uuid.UUID) *PrincipalUpdate {
	_u.mutation.AddSeatAssignmentIDs(ids...)
	return _u
}

// AddSeatAssignments adds the "seat_assignments" edges to the SeatAssignment entity.
func (_u *PrincipalUpdate) AddSeatAssignments(v ...*SeatAssignment) *PrincipalUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSeatAssignmentIDs(ids...)
}

// AddAssignedSeatIDs adds the "assigned_seats" edge to the SeatAssignment entity by IDs.
func (_u *PrincipalUpdate) AddAssignedSeatIDs(ids ...uuid.UUID) *PrincipalUpdate {
	_u.mutation.AddAssignedSeatIDs(ids...)
	return _u
}

// AddAssignedSeats adds the "assigned_seats" edges to the SeatAssignment entity.
func (_u *PrincipalUpdate) AddAssignedSeats(v ...*SeatAssignment) *PrincipalUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAssignedSeatIDs(ids...)
}

// Mutation returns the PrincipalMutation object of the builder.
func (_u *PrincipalUpdate) Mutation() *PrincipalMutation {
	return _u.mutation
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (_u *PrincipalUpdate) ClearOrganization() *PrincipalUpdate {
	_u.mutation.ClearOrganization()
	return _u
}

// ClearHuman clears the "human" edge to the Human entity.
func (_u *PrincipalUpdate) ClearHuman() *PrincipalUpdate {
	_u.mutation.ClearHuman()
	return _u
}

// ClearApplication clears the "application" edge to the Application entity.
func (_u *PrincipalUpdate) ClearApplication() *PrincipalUpdate {
	_u.mutation.ClearApplication()
	return _u
}

// ClearAgent clears the "agent" edge to the Agent entity.
func (_u *PrincipalUpdate) ClearAgent() *PrincipalUpdate {
	_u.mutation.ClearAgent()
	return _u
}

// ClearServicePrincipal clears the "service_principal" edge to the ServicePrincipal entity.
func (_u *PrincipalUpdate) ClearServicePrincipal() *PrincipalUpdate {
	_u.mutation.ClearServicePrincipal()
	return _u
}

// ClearCredentials clears all "credentials" edges to the Credential entity.
func (_u *PrincipalUpdate) ClearCredentials() *PrincipalUpdate {
	_u.mutation.ClearCredentials()
	return _u
}

// RemoveCredentialIDs removes the "credentials" edge to Credential entities by IDs.
func (_u *PrincipalUpdate) RemoveCredentialIDs(ids ...uuid.UUID) *PrincipalUpdate {
	_u.mutation.RemoveCredentialIDs(ids...)
	return _u
}

// RemoveCredentials removes "credentials" edges to Credential entities.
func (_u *PrincipalUpdate) RemoveCredentials(v ...*Credential) *PrincipalUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCredentialIDs(ids...)
}

// ClearExternalIdentities clears all "external_identities" edges to the ExternalIdentity entity.
func (_u *PrincipalUpdate) ClearExternalIdentities() *PrincipalUpdate {
	_u.mutation.ClearExternalIdentities()
	return _u
}

// RemoveExternalIdentityIDs removes the "external_identities" edge to ExternalIdentity entities by IDs.
func (_u *PrincipalUpdate) RemoveExternalIdentityIDs(ids ...uuid.UUID) *PrincipalUpdate {
	_u.mutation.RemoveExternalIdentityIDs(ids...)
	return _u
}

// RemoveExternalIdentities removes "external_identities" edges to ExternalIdentity entities.
func (_u *PrincipalUpdate) RemoveExternalIdentities(v ...*ExternalIdentity) *PrincipalUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveExternalIdentityIDs(ids...)
}

// ClearPrincipalTokens clears all "principal_tokens" edges to the PrincipalToken entity.
func (_u *PrincipalUpdate) ClearPrincipalTokens() *PrincipalUpdate {
	_u.mutation.ClearPrincipalTokens()
	return _u
}

// RemovePrincipalTokenIDs removes the "principal_tokens" edge to PrincipalToken entities by IDs.
func (_u *PrincipalUpdate) RemovePrincipalTokenIDs(ids ...uuid.UUID) *PrincipalUpdate {
	_u.mutation.RemovePrincipalTokenIDs(ids...)
	return _u
}

// RemovePrincipalTokens removes "principal_tokens" edges to PrincipalToken entities.
func (_u *PrincipalUpdate) RemovePrincipalTokens(v ...*PrincipalToken) *PrincipalUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePrincipalTokenIDs(ids...)
}

// ClearPrincipalMemberships clears all "principal_memberships" edges to the PrincipalMembership entity.
func (_u *PrincipalUpdate) ClearPrincipalMemberships() *PrincipalUpdate {
	_u.mutation.ClearPrincipalMemberships()
	return _u
}

// RemovePrincipalMembershipIDs removes the "principal_memberships" edge to PrincipalMembership entities by IDs.
func (_u *PrincipalUpdate) RemovePrincipalMembershipIDs(ids ...uuid.UUID) *PrincipalUpdate {
	_u.mutation.RemovePrincipalMembershipIDs(ids...)
	return _u
}

// RemovePrincipalMemberships removes "principal_memberships" edges to PrincipalMembership entities.
func (_u *PrincipalUpdate) RemovePrincipalMemberships(v ...*PrincipalMembership) *PrincipalUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePrincipalMembershipIDs(ids...)
}

// ClearOwnedOrganizations clears all "owned_organizations" edges to the Organization entity.
func (_u *PrincipalUpdate) ClearOwnedOrganizations() *PrincipalUpdate {
	_u.mutation.ClearOwnedOrganizations()
	return _u
}

// RemoveOwnedOrganizationIDs removes the "owned_organizations" edge to Organization entities by IDs.
func (_u *PrincipalUpdate) RemoveOwnedOrganizationIDs(ids ...uuid.UUID) *PrincipalUpdate {
	_u.mutation.RemoveOwnedOrganizationIDs(ids...)
	return _u
}

// RemoveOwnedOrganizations removes "owned_organizations" edges to Organization entities.
func (_u *PrincipalUpdate) RemoveOwnedOrganizations(v ...*Organization) *PrincipalUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOwnedOrganizationIDs(ids...)
}

// ClearSentInvites clears all "sent_invites" edges to the Invite entity.
func (_u *PrincipalUpdate) ClearSentInvites() *PrincipalUpdate {
	_u.mutation.ClearSentInvites()
	return _u
}

// RemoveSentInviteIDs removes the "sent_invites" edge to Invite entities by IDs.
func (_u *PrincipalUpdate) RemoveSentInviteIDs(ids ...uuid.UUID) *PrincipalUpdate {
	_u.mutation.RemoveSentInviteIDs(ids...)
	return _u
}

// RemoveSentInvites removes "sent_invites" edges to Invite entities.
func (_u *PrincipalUpdate) RemoveSentInvites(v ...*Invite) *PrincipalUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSentInviteIDs(ids...)
}

// ClearOwnedListings clears all "owned_listings" edges to the Listing entity.
func (_u *PrincipalUpdate) ClearOwnedListings() *PrincipalUpdate {
	_u.mutation.ClearOwnedListings()
	return _u
}

// RemoveOwnedListingIDs removes the "owned_listings" edge to Listing entities by IDs.
func (_u *PrincipalUpdate) RemoveOwnedListingIDs(ids ...uuid.UUID) *PrincipalUpdate {
	_u.mutation.RemoveOwnedListingIDs(ids...)
	return _u
}

// RemoveOwnedListings removes "owned_listings" edges to Listing entities.
func (_u *PrincipalUpdate) RemoveOwnedListings(v ...*Listing) *PrincipalUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOwnedListingIDs(ids...)
}

// ClearPurchasedLicenses clears all "purchased_licenses" edges to the License entity.
func (_u *PrincipalUpdate) ClearPurchasedLicenses() *PrincipalUpdate {
	_u.mutation.ClearPurchasedLicenses()
	return _u
}

// RemovePurchasedLicenseIDs removes the "purchased_licenses" edge to License entities by IDs.
func (_u *PrincipalUpdate) RemovePurchasedLicenseIDs(ids ...uuid.UUID) *PrincipalUpdate {
	_u.mutation.RemovePurchasedLicenseIDs(ids...)
	return _u
}

// RemovePurchasedLicenses removes "purchased_licenses" edges to License entities.
func (_u *PrincipalUpdate) RemovePurchasedLicenses(v ...*License) *PrincipalUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePurchasedLicenseIDs(ids...)
}

// ClearSeatAssignments clears all "seat_assignments" edges to the SeatAssignment entity.
func (_u *PrincipalUpdate) ClearSeatAssignments() *PrincipalUpdate {
	_u.mutation.ClearSeatAssignments()
	return _u
}

// RemoveSeatAssignmentIDs removes the "seat_assignments" edge to SeatAssignment entities by IDs.
func (_u *PrincipalUpdate) RemoveSeatAssignmentIDs(ids ...uuid.UUID) *PrincipalUpdate {
	_u.mutation.RemoveSeatAssignmentIDs(ids...)
	return _u
}

// RemoveSeatAssignments removes "seat_assignments" edges to SeatAssignment entities.
func (_u *PrincipalUpdate) RemoveSeatAssignments(v ...*SeatAssignment) *PrincipalUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSeatAssignmentIDs(ids...)
}

// ClearAssignedSeats clears all "assigned_seats" edges to the SeatAssignment entity.
func (_u *PrincipalUpdate) ClearAssignedSeats() *PrincipalUpdate {
	_u.mutation.ClearAssignedSeats()
	return _u
}

// RemoveAssignedSeatIDs removes the "assigned_seats" edge to SeatAssignment entities by IDs.
func (_u *PrincipalUpdate) RemoveAssignedSeatIDs(ids ...uuid.UUID) *PrincipalUpdate {
	_u.mutation.RemoveAssignedSeatIDs(ids...)
	return _u
}

// RemoveAssignedSeats removes "assigned_seats" edges to SeatAssignment entities.
func (_u *PrincipalUpdate) RemoveAssignedSeats(v ...*SeatAssignment) *PrincipalUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAssignedSeatIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PrincipalUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PrincipalUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PrincipalUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PrincipalUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PrincipalUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := principal.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PrincipalUpdate) check() error {
	if v, ok := _u.mutation.Identifier(); ok {
		if err := principal.IdentifierValidator(v); err != nil {
			return &ValidationError{Name: "identifier", err: fmt.Errorf(`ent: validator failed for field "Principal.identifier": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := principal.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "Principal.display_name": %w`, err)}
		}
	}
	return nil
}

func (_u *PrincipalUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(principal.Table, principal.Columns, sqlgraph.NewFieldSpec(principal.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(principal.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Identifier(); ok {
		_spec.SetField(principal.FieldIdentifier, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(principal.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(principal.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Capabilities(); ok {
		_spec.SetField(principal.FieldCapabilities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AllowedScopes(); ok {
		_spec.SetField(principal.FieldAllowedScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAllowedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, principal.FieldAllowedScopes, value)
		})
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(principal.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(principal.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   principal.OrganizationTable,
			Columns: []string{principal.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   principal.OrganizationTable,
			Columns: []string{principal.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.HumanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   principal.HumanTable,
			Columns: []string{principal.HumanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(human.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HumanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   principal.HumanTable,
			Columns: []string{principal.HumanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(human.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ApplicationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   principal.ApplicationTable,
			Columns: []string{principal.ApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(application.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ApplicationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   principal.ApplicationTable,
			Columns: []string{principal.ApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(application.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AgentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   principal.AgentTable,
			Columns: []string{principal.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AgentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   principal.AgentTable,
			Columns: []string{principal.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ServicePrincipalCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   principal.ServicePrincipalTable,
			Columns: []string{principal.ServicePrincipalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serviceprincipal.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServicePrincipalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   principal.ServicePrincipalTable,
			Columns: []string{principal.ServicePrincipalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serviceprincipal.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CredentialsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.CredentialsTable,
			Columns: []string{principal.CredentialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credential.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCredentialsIDs(); len(nodes) > 0 && !_u.mutation.CredentialsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.CredentialsTable,
			Columns: []string{principal.CredentialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credential.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CredentialsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.CredentialsTable,
			Columns: []string{principal.CredentialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credential.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ExternalIdentitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.ExternalIdentitiesTable,
			Columns: []string{principal.ExternalIdentitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(externalidentity.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedExternalIdentitiesIDs(); len(nodes) > 0 && !_u.mutation.ExternalIdentitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.ExternalIdentitiesTable,
			Columns: []string{principal.ExternalIdentitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(externalidentity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExternalIdentitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.ExternalIdentitiesTable,
			Columns: []string{principal.ExternalIdentitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(externalidentity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PrincipalTokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.PrincipalTokensTable,
			Columns: []string{principal.PrincipalTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(principaltoken.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPrincipalTokensIDs(); len(nodes) > 0 && !_u.mutation.PrincipalTokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.PrincipalTokensTable,
			Columns: []string{principal.PrincipalTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(principaltoken.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PrincipalTokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.PrincipalTokensTable,
			Columns: []string{principal.PrincipalTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(principaltoken.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PrincipalMembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.PrincipalMembershipsTable,
			Columns: []string{principal.PrincipalMembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(principalmembership.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPrincipalMembershipsIDs(); len(nodes) > 0 && !_u.mutation.PrincipalMembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.PrincipalMembershipsTable,
			Columns: []string{principal.PrincipalMembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(principalmembership.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PrincipalMembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.PrincipalMembershipsTable,
			Columns: []string{principal.PrincipalMembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(principalmembership.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OwnedOrganizationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.OwnedOrganizationsTable,
			Columns: []string{principal.OwnedOrganizationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOwnedOrganizationsIDs(); len(nodes) > 0 && !_u.mutation.OwnedOrganizationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.OwnedOrganizationsTable,
			Columns: []string{principal.OwnedOrganizationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnedOrganizationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.OwnedOrganizationsTable,
			Columns: []string{principal.OwnedOrganizationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SentInvitesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.SentInvitesTable,
			Columns: []string{principal.SentInvitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invite.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSentInvitesIDs(); len(nodes) > 0 && !_u.mutation.SentInvitesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.SentInvitesTable,
			Columns: []string{principal.SentInvitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invite.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SentInvitesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.SentInvitesTable,
			Columns: []string{principal.SentInvitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invite.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OwnedListingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.OwnedListingsTable,
			Columns: []string{principal.OwnedListingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listing.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOwnedListingsIDs(); len(nodes) > 0 && !_u.mutation.OwnedListingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.OwnedListingsTable,
			Columns: []string{principal.OwnedListingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listing.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnedListingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.OwnedListingsTable,
			Columns: []string{principal.OwnedListingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listing.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PurchasedLicensesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.PurchasedLicensesTable,
			Columns: []string{principal.PurchasedLicensesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(license.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPurchasedLicensesIDs(); len(nodes) > 0 && !_u.mutation.PurchasedLicensesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.PurchasedLicensesTable,
			Columns: []string{principal.PurchasedLicensesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(license.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PurchasedLicensesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.PurchasedLicensesTable,
			Columns: []string{principal.PurchasedLicensesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(license.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SeatAssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.SeatAssignmentsTable,
			Columns: []string{principal.SeatAssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seatassignment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSeatAssignmentsIDs(); len(nodes) > 0 && !_u.mutation.SeatAssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.SeatAssignmentsTable,
			Columns: []string{principal.SeatAssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seatassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SeatAssignmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.SeatAssignmentsTable,
			Columns: []string{principal.SeatAssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seatassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssignedSeatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.AssignedSeatsTable,
			Columns: []string{principal.AssignedSeatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seatassignment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAssignedSeatsIDs(); len(nodes) > 0 && !_u.mutation.AssignedSeatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.AssignedSeatsTable,
			Columns: []string{principal.AssignedSeatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seatassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssignedSeatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.AssignedSeatsTable,
			Columns: []string{principal.AssignedSeatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seatassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{principal.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PrincipalUpdateOne is the builder for updating a single Principal entity.
type PrincipalUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PrincipalMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PrincipalUpdateOne) SetUpdatedAt(v time.Time) *PrincipalUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetIdentifier sets the "identifier" field.
func (_u *PrincipalUpdateOne) SetIdentifier(v string) *PrincipalUpdateOne {
	_u.mutation.SetIdentifier(v)
	return _u
}

// SetNillableIdentifier sets the "identifier" field if the given value is not nil.
func (_u *PrincipalUpdateOne) SetNillableIdentifier(v *string) *PrincipalUpdateOne {
	if v != nil {
		_u.SetIdentifier(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *PrincipalUpdateOne) SetDisplayName(v string) *PrincipalUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *PrincipalUpdateOne) SetNillableDisplayName(v *string) *PrincipalUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetOrganizationID sets the "organization_id" field.
func (_u *PrincipalUpdateOne) SetOrganizationID(v uuid.UUID) *PrincipalUpdateOne {
	_u.mutation.SetOrganizationID(v)
	return _u
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (_u *PrincipalUpdateOne) SetNillableOrganizationID(v *uuid.UUID) *PrincipalUpdateOne {
	if v != nil {
		_u.SetOrganizationID(*v)
	}
	return _u
}

// ClearOrganizationID clears the value of the "organization_id" field.
func (_u *PrincipalUpdateOne) ClearOrganizationID() *PrincipalUpdateOne {
	_u.mutation.ClearOrganizationID()
	return _u
}

// SetActive sets the "active" field.
func (_u *PrincipalUpdateOne) SetActive(v bool) *PrincipalUpdateOne {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *PrincipalUpdateOne) SetNillableActive(v *bool) *PrincipalUpdateOne {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetCapabilities sets the "capabilities" field.
func (_u *PrincipalUpdateOne) SetCapabilities(v map[string]bool) *PrincipalUpdateOne {
	_u.mutation.SetCapabilities(v)
	return _u
}

// SetAllowedScopes sets the "allowed_scopes" field.
func (_u *PrincipalUpdateOne) SetAllowedScopes(v []string) *PrincipalUpdateOne {
	_u.mutation.SetAllowedScopes(v)
	return _u
}

// AppendAllowedScopes appends value to the "allowed_scopes" field.
func (_u *PrincipalUpdateOne) AppendAllowedScopes(v []string) *PrincipalUpdateOne {
	_u.mutation.AppendAllowedScopes(v)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *PrincipalUpdateOne) SetMetadata(v map[string]interface{}) *PrincipalUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *PrincipalUpdateOne) ClearMetadata() *PrincipalUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_u *PrincipalUpdateOne) SetOrganization(v *Organization) *PrincipalUpdateOne {
	return _u.SetOrganizationID(v.ID)
}

// SetHumanID sets the "human" edge to the Human entity by ID.
func (_u *PrincipalUpdateOne) SetHumanID(id uuid.UUID) *PrincipalUpdateOne {
	_u.mutation.SetHumanID(id)
	return _u
}

// SetNillableHumanID sets the "human" edge to the Human entity by ID if the given value is not nil.
func (_u *PrincipalUpdateOne) SetNillableHumanID(id *uuid.UUID) *PrincipalUpdateOne {
	if id != nil {
		_u = _u.SetHumanID(*id)
	}
	return _u
}

// SetHuman sets the "human" edge to the Human entity.
func (_u *PrincipalUpdateOne) SetHuman(v *Human) *PrincipalUpdateOne {
	return _u.SetHumanID(v.ID)
}

// SetApplicationID sets the "application" edge to the Application entity by ID.
func (_u *PrincipalUpdateOne) SetApplicationID(id uuid.UUID) *PrincipalUpdateOne {
	_u.mutation.SetApplicationID(id)
	return _u
}

// SetNillableApplicationID sets the "application" edge to the Application entity by ID if the given value is not nil.
func (_u *PrincipalUpdateOne) SetNillableApplicationID(id *uuid.UUID) *PrincipalUpdateOne {
	if id != nil {
		_u = _u.SetApplicationID(*id)
	}
	return _u
}

// SetApplication sets the "application" edge to the Application entity.
func (_u *PrincipalUpdateOne) SetApplication(v *Application) *PrincipalUpdateOne {
	return _u.SetApplicationID(v.ID)
}

// SetAgentID sets the "agent" edge to the Agent entity by ID.
func (_u *PrincipalUpdateOne) SetAgentID(id uuid.UUID) *PrincipalUpdateOne {
	_u.mutation.SetAgentID(id)
	return _u
}

// SetNillableAgentID sets the "agent" edge to the Agent entity by ID if the given value is not nil.
func (_u *PrincipalUpdateOne) SetNillableAgentID(id *uuid.UUID) *PrincipalUpdateOne {
	if id != nil {
		_u = _u.SetAgentID(*id)
	}
	return _u
}

// SetAgent sets the "agent" edge to the Agent entity.
func (_u *PrincipalUpdateOne) SetAgent(v *Agent) *PrincipalUpdateOne {
	return _u.SetAgentID(v.ID)
}

// SetServicePrincipalID sets the "service_principal" edge to the ServicePrincipal entity by ID.
func (_u *PrincipalUpdateOne) SetServicePrincipalID(id uuid.UUID) *PrincipalUpdateOne {
	_u.mutation.SetServicePrincipalID(id)
	return _u
}

// SetNillableServicePrincipalID sets the "service_principal" edge to the ServicePrincipal entity by ID if the given value is not nil.
func (_u *PrincipalUpdateOne) SetNillableServicePrincipalID(id *uuid.UUID) *PrincipalUpdateOne {
	if id != nil {
		_u = _u.SetServicePrincipalID(*id)
	}
	return _u
}

// SetServicePrincipal sets the "service_principal" edge to the ServicePrincipal entity.
func (_u *PrincipalUpdateOne) SetServicePrincipal(v *ServicePrincipal) *PrincipalUpdateOne {
	return _u.SetServicePrincipalID(v.ID)
}

// AddCredentialIDs adds the "credentials" edge to the Credential entity by IDs.
func (_u *PrincipalUpdateOne) AddCredentialIDs(ids ...uuid.UUID) *PrincipalUpdateOne {
	_u.mutation.AddCredentialIDs(ids...)
	return _u
}

// AddCredentials adds the "credentials" edges to the Credential entity.
func (_u *PrincipalUpdateOne) AddCredentials(v ...*Credential) *PrincipalUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCredentialIDs(ids...)
}

// AddExternalIdentityIDs adds the "external_identities" edge to the ExternalIdentity entity by IDs.
func (_u *PrincipalUpdateOne) AddExternalIdentityIDs(ids ...uuid.UUID) *PrincipalUpdateOne {
	_u.mutation.AddExternalIdentityIDs(ids...)
	return _u
}

// AddExternalIdentities adds the "external_identities" edges to the ExternalIdentity entity.
func (_u *PrincipalUpdateOne) AddExternalIdentities(v ...*ExternalIdentity) *PrincipalUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddExternalIdentityIDs(ids...)
}

// AddPrincipalTokenIDs adds the "principal_tokens" edge to the PrincipalToken entity by IDs.
func (_u *PrincipalUpdateOne) AddPrincipalTokenIDs(ids ...uuid.UUID) *PrincipalUpdateOne {
	_u.mutation.AddPrincipalTokenIDs(ids...)
	return _u
}

// AddPrincipalTokens adds the "principal_tokens" edges to the PrincipalToken entity.
func (_u *PrincipalUpdateOne) AddPrincipalTokens(v ...*PrincipalToken) *PrincipalUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPrincipalTokenIDs(ids...)
}

// AddPrincipalMembershipIDs adds the "principal_memberships" edge to the PrincipalMembership entity by IDs.
func (_u *PrincipalUpdateOne) AddPrincipalMembershipIDs(ids ...uuid.UUID) *PrincipalUpdateOne {
	_u.mutation.AddPrincipalMembershipIDs(ids...)
	return _u
}

// AddPrincipalMemberships adds the "principal_memberships" edges to the PrincipalMembership entity.
func (_u *PrincipalUpdateOne) AddPrincipalMemberships(v ...*PrincipalMembership) *PrincipalUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPrincipalMembershipIDs(ids...)
}

// AddOwnedOrganizationIDs adds the "owned_organizations" edge to the Organization entity by IDs.
func (_u *PrincipalUpdateOne) AddOwnedOrganizationIDs(ids ...uuid.UUID) *PrincipalUpdateOne {
	_u.mutation.AddOwnedOrganizationIDs(ids...)
	return _u
}

// AddOwnedOrganizations adds the "owned_organizations" edges to the Organization entity.
func (_u *PrincipalUpdateOne) AddOwnedOrganizations(v ...*Organization) *PrincipalUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOwnedOrganizationIDs(ids...)
}

// AddSentInviteIDs adds the "sent_invites" edge to the Invite entity by IDs.
func (_u *PrincipalUpdateOne) AddSentInviteIDs(ids ...uuid.UUID) *PrincipalUpdateOne {
	_u.mutation.AddSentInviteIDs(ids...)
	return _u
}

// AddSentInvites adds the "sent_invites" edges to the Invite entity.
func (_u *PrincipalUpdateOne) AddSentInvites(v ...*Invite) *PrincipalUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSentInviteIDs(ids...)
}

// AddOwnedListingIDs adds the "owned_listings" edge to the Listing entity by IDs.
func (_u *PrincipalUpdateOne) AddOwnedListingIDs(ids ...uuid.UUID) *PrincipalUpdateOne {
	_u.mutation.AddOwnedListingIDs(ids...)
	return _u
}

// AddOwnedListings adds the "owned_listings" edges to the Listing entity.
func (_u *PrincipalUpdateOne) AddOwnedListings(v ...*Listing) *PrincipalUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOwnedListingIDs(ids...)
}

// AddPurchasedLicenseIDs adds the "purchased_licenses" edge to the License entity by IDs.
func (_u *PrincipalUpdateOne) AddPurchasedLicenseIDs(ids ...uuid.UUID) *PrincipalUpdateOne {
	_u.mutation.AddPurchasedLicenseIDs(ids...)
	return _u
}

// AddPurchasedLicenses adds the "purchased_licenses" edges to the License entity.
func (_u *PrincipalUpdateOne) AddPurchasedLicenses(v ...*License) *PrincipalUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPurchasedLicenseIDs(ids...)
}

// AddSeatAssignmentIDs adds the "seat_assignments" edge to the SeatAssignment entity by IDs.
func (_u *PrincipalUpdateOne) AddSeatAssignmentIDs(ids ...uuid.UUID) *PrincipalUpdateOne {
	_u.mutation.AddSeatAssignmentIDs(ids...)
	return _u
}

// AddSeatAssignments adds the "seat_assignments" edges to the SeatAssignment entity.
func (_u *PrincipalUpdateOne) AddSeatAssignments(v ...*SeatAssignment) *PrincipalUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSeatAssignmentIDs(ids...)
}

// AddAssignedSeatIDs adds the "assigned_seats" edge to the SeatAssignment entity by IDs.
func (_u *PrincipalUpdateOne) AddAssignedSeatIDs(ids ...uuid.UUID) *PrincipalUpdateOne {
	_u.mutation.AddAssignedSeatIDs(ids...)
	return _u
}

// AddAssignedSeats adds the "assigned_seats" edges to the SeatAssignment entity.
func (_u *PrincipalUpdateOne) AddAssignedSeats(v ...*SeatAssignment) *PrincipalUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAssignedSeatIDs(ids...)
}

// Mutation returns the PrincipalMutation object of the builder.
func (_u *PrincipalUpdateOne) Mutation() *PrincipalMutation {
	return _u.mutation
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (_u *PrincipalUpdateOne) ClearOrganization() *PrincipalUpdateOne {
	_u.mutation.ClearOrganization()
	return _u
}

// ClearHuman clears the "human" edge to the Human entity.
func (_u *PrincipalUpdateOne) ClearHuman() *PrincipalUpdateOne {
	_u.mutation.ClearHuman()
	return _u
}

// ClearApplication clears the "application" edge to the Application entity.
func (_u *PrincipalUpdateOne) ClearApplication() *PrincipalUpdateOne {
	_u.mutation.ClearApplication()
	return _u
}

// ClearAgent clears the "agent" edge to the Agent entity.
func (_u *PrincipalUpdateOne) ClearAgent() *PrincipalUpdateOne {
	_u.mutation.ClearAgent()
	return _u
}

// ClearServicePrincipal clears the "service_principal" edge to the ServicePrincipal entity.
func (_u *PrincipalUpdateOne) ClearServicePrincipal() *PrincipalUpdateOne {
	_u.mutation.ClearServicePrincipal()
	return _u
}

// ClearCredentials clears all "credentials" edges to the Credential entity.
func (_u *PrincipalUpdateOne) ClearCredentials() *PrincipalUpdateOne {
	_u.mutation.ClearCredentials()
	return _u
}

// RemoveCredentialIDs removes the "credentials" edge to Credential entities by IDs.
func (_u *PrincipalUpdateOne) RemoveCredentialIDs(ids ...uuid.UUID) *PrincipalUpdateOne {
	_u.mutation.RemoveCredentialIDs(ids...)
	return _u
}

// RemoveCredentials removes "credentials" edges to Credential entities.
func (_u *PrincipalUpdateOne) RemoveCredentials(v ...*Credential) *PrincipalUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCredentialIDs(ids...)
}

// ClearExternalIdentities clears all "external_identities" edges to the ExternalIdentity entity.
func (_u *PrincipalUpdateOne) ClearExternalIdentities() *PrincipalUpdateOne {
	_u.mutation.ClearExternalIdentities()
	return _u
}

// RemoveExternalIdentityIDs removes the "external_identities" edge to ExternalIdentity entities by IDs.
func (_u *PrincipalUpdateOne) RemoveExternalIdentityIDs(ids ...uuid.UUID) *PrincipalUpdateOne {
	_u.mutation.RemoveExternalIdentityIDs(ids...)
	return _u
}

// RemoveExternalIdentities removes "external_identities" edges to ExternalIdentity entities.
func (_u *PrincipalUpdateOne) RemoveExternalIdentities(v ...*ExternalIdentity) *PrincipalUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveExternalIdentityIDs(ids...)
}

// ClearPrincipalTokens clears all "principal_tokens" edges to the PrincipalToken entity.
func (_u *PrincipalUpdateOne) ClearPrincipalTokens() *PrincipalUpdateOne {
	_u.mutation.ClearPrincipalTokens()
	return _u
}

// RemovePrincipalTokenIDs removes the "principal_tokens" edge to PrincipalToken entities by IDs.
func (_u *PrincipalUpdateOne) RemovePrincipalTokenIDs(ids ...uuid.UUID) *PrincipalUpdateOne {
	_u.mutation.RemovePrincipalTokenIDs(ids...)
	return _u
}

// RemovePrincipalTokens removes "principal_tokens" edges to PrincipalToken entities.
func (_u *PrincipalUpdateOne) RemovePrincipalTokens(v ...*PrincipalToken) *PrincipalUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePrincipalTokenIDs(ids...)
}

// ClearPrincipalMemberships clears all "principal_memberships" edges to the PrincipalMembership entity.
func (_u *PrincipalUpdateOne) ClearPrincipalMemberships() *PrincipalUpdateOne {
	_u.mutation.ClearPrincipalMemberships()
	return _u
}

// RemovePrincipalMembershipIDs removes the "principal_memberships" edge to PrincipalMembership entities by IDs.
func (_u *PrincipalUpdateOne) RemovePrincipalMembershipIDs(ids ...uuid.UUID) *PrincipalUpdateOne {
	_u.mutation.RemovePrincipalMembershipIDs(ids...)
	return _u
}

// RemovePrincipalMemberships removes "principal_memberships" edges to PrincipalMembership entities.
func (_u *PrincipalUpdateOne) RemovePrincipalMemberships(v ...*PrincipalMembership) *PrincipalUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePrincipalMembershipIDs(ids...)
}

// ClearOwnedOrganizations clears all "owned_organizations" edges to the Organization entity.
func (_u *PrincipalUpdateOne) ClearOwnedOrganizations() *PrincipalUpdateOne {
	_u.mutation.ClearOwnedOrganizations()
	return _u
}

// RemoveOwnedOrganizationIDs removes the "owned_organizations" edge to Organization entities by IDs.
func (_u *PrincipalUpdateOne) RemoveOwnedOrganizationIDs(ids ...uuid.UUID) *PrincipalUpdateOne {
	_u.mutation.RemoveOwnedOrganizationIDs(ids...)
	return _u
}

// RemoveOwnedOrganizations removes "owned_organizations" edges to Organization entities.
func (_u *PrincipalUpdateOne) RemoveOwnedOrganizations(v ...*Organization) *PrincipalUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOwnedOrganizationIDs(ids...)
}

// ClearSentInvites clears all "sent_invites" edges to the Invite entity.
func (_u *PrincipalUpdateOne) ClearSentInvites() *PrincipalUpdateOne {
	_u.mutation.ClearSentInvites()
	return _u
}

// RemoveSentInviteIDs removes the "sent_invites" edge to Invite entities by IDs.
func (_u *PrincipalUpdateOne) RemoveSentInviteIDs(ids ...uuid.UUID) *PrincipalUpdateOne {
	_u.mutation.RemoveSentInviteIDs(ids...)
	return _u
}

// RemoveSentInvites removes "sent_invites" edges to Invite entities.
func (_u *PrincipalUpdateOne) RemoveSentInvites(v ...*Invite) *PrincipalUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSentInviteIDs(ids...)
}

// ClearOwnedListings clears all "owned_listings" edges to the Listing entity.
func (_u *PrincipalUpdateOne) ClearOwnedListings() *PrincipalUpdateOne {
	_u.mutation.ClearOwnedListings()
	return _u
}

// RemoveOwnedListingIDs removes the "owned_listings" edge to Listing entities by IDs.
func (_u *PrincipalUpdateOne) RemoveOwnedListingIDs(ids ...uuid.UUID) *PrincipalUpdateOne {
	_u.mutation.RemoveOwnedListingIDs(ids...)
	return _u
}

// RemoveOwnedListings removes "owned_listings" edges to Listing entities.
func (_u *PrincipalUpdateOne) RemoveOwnedListings(v ...*Listing) *PrincipalUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOwnedListingIDs(ids...)
}

// ClearPurchasedLicenses clears all "purchased_licenses" edges to the License entity.
func (_u *PrincipalUpdateOne) ClearPurchasedLicenses() *PrincipalUpdateOne {
	_u.mutation.ClearPurchasedLicenses()
	return _u
}

// RemovePurchasedLicenseIDs removes the "purchased_licenses" edge to License entities by IDs.
func (_u *PrincipalUpdateOne) RemovePurchasedLicenseIDs(ids ...uuid.UUID) *PrincipalUpdateOne {
	_u.mutation.RemovePurchasedLicenseIDs(ids...)
	return _u
}

// RemovePurchasedLicenses removes "purchased_licenses" edges to License entities.
func (_u *PrincipalUpdateOne) RemovePurchasedLicenses(v ...*License) *PrincipalUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePurchasedLicenseIDs(ids...)
}

// ClearSeatAssignments clears all "seat_assignments" edges to the SeatAssignment entity.
func (_u *PrincipalUpdateOne) ClearSeatAssignments() *PrincipalUpdateOne {
	_u.mutation.ClearSeatAssignments()
	return _u
}

// RemoveSeatAssignmentIDs removes the "seat_assignments" edge to SeatAssignment entities by IDs.
func (_u *PrincipalUpdateOne) RemoveSeatAssignmentIDs(ids ...uuid.UUID) *PrincipalUpdateOne {
	_u.mutation.RemoveSeatAssignmentIDs(ids...)
	return _u
}

// RemoveSeatAssignments removes "seat_assignments" edges to SeatAssignment entities.
func (_u *PrincipalUpdateOne) RemoveSeatAssignments(v ...*SeatAssignment) *PrincipalUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSeatAssignmentIDs(ids...)
}

// ClearAssignedSeats clears all "assigned_seats" edges to the SeatAssignment entity.
func (_u *PrincipalUpdateOne) ClearAssignedSeats() *PrincipalUpdateOne {
	_u.mutation.ClearAssignedSeats()
	return _u
}

// RemoveAssignedSeatIDs removes the "assigned_seats" edge to SeatAssignment entities by IDs.
func (_u *PrincipalUpdateOne) RemoveAssignedSeatIDs(ids ...uuid.UUID) *PrincipalUpdateOne {
	_u.mutation.RemoveAssignedSeatIDs(ids...)
	return _u
}

// RemoveAssignedSeats removes "assigned_seats" edges to SeatAssignment entities.
func (_u *PrincipalUpdateOne) RemoveAssignedSeats(v ...*SeatAssignment) *PrincipalUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAssignedSeatIDs(ids...)
}

// Where appends a list predicates to the PrincipalUpdate builder.
func (_u *PrincipalUpdateOne) Where(ps ...predicate.Principal) *PrincipalUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PrincipalUpdateOne) Select(field string, fields ...string) *PrincipalUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Principal entity.
func (_u *PrincipalUpdateOne) Save(ctx context.Context) (*Principal, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PrincipalUpdateOne) SaveX(ctx context.Context) *Principal {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PrincipalUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PrincipalUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PrincipalUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := principal.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PrincipalUpdateOne) check() error {
	if v, ok := _u.mutation.Identifier(); ok {
		if err := principal.IdentifierValidator(v); err != nil {
			return &ValidationError{Name: "identifier", err: fmt.Errorf(`ent: validator failed for field "Principal.identifier": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := principal.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "Principal.display_name": %w`, err)}
		}
	}
	return nil
}

func (_u *PrincipalUpdateOne) sqlSave(ctx context.Context) (_node *Principal, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(principal.Table, principal.Columns, sqlgraph.NewFieldSpec(principal.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Principal.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, principal.FieldID)
		for _, f := range fields {
			if !principal.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != principal.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(principal.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Identifier(); ok {
		_spec.SetField(principal.FieldIdentifier, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(principal.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(principal.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Capabilities(); ok {
		_spec.SetField(principal.FieldCapabilities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AllowedScopes(); ok {
		_spec.SetField(principal.FieldAllowedScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAllowedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, principal.FieldAllowedScopes, value)
		})
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(principal.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(principal.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   principal.OrganizationTable,
			Columns: []string{principal.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   principal.OrganizationTable,
			Columns: []string{principal.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.HumanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   principal.HumanTable,
			Columns: []string{principal.HumanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(human.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HumanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   principal.HumanTable,
			Columns: []string{principal.HumanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(human.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ApplicationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   principal.ApplicationTable,
			Columns: []string{principal.ApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(application.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ApplicationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   principal.ApplicationTable,
			Columns: []string{principal.ApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(application.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AgentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   principal.AgentTable,
			Columns: []string{principal.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AgentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   principal.AgentTable,
			Columns: []string{principal.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ServicePrincipalCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   principal.ServicePrincipalTable,
			Columns: []string{principal.ServicePrincipalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serviceprincipal.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServicePrincipalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   principal.ServicePrincipalTable,
			Columns: []string{principal.ServicePrincipalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serviceprincipal.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CredentialsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.CredentialsTable,
			Columns: []string{principal.CredentialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credential.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCredentialsIDs(); len(nodes) > 0 && !_u.mutation.CredentialsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.CredentialsTable,
			Columns: []string{principal.CredentialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credential.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CredentialsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.CredentialsTable,
			Columns: []string{principal.CredentialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credential.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ExternalIdentitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.ExternalIdentitiesTable,
			Columns: []string{principal.ExternalIdentitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(externalidentity.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedExternalIdentitiesIDs(); len(nodes) > 0 && !_u.mutation.ExternalIdentitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.ExternalIdentitiesTable,
			Columns: []string{principal.ExternalIdentitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(externalidentity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExternalIdentitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.ExternalIdentitiesTable,
			Columns: []string{principal.ExternalIdentitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(externalidentity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PrincipalTokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.PrincipalTokensTable,
			Columns: []string{principal.PrincipalTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(principaltoken.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPrincipalTokensIDs(); len(nodes) > 0 && !_u.mutation.PrincipalTokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.PrincipalTokensTable,
			Columns: []string{principal.PrincipalTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(principaltoken.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PrincipalTokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.PrincipalTokensTable,
			Columns: []string{principal.PrincipalTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(principaltoken.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PrincipalMembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.PrincipalMembershipsTable,
			Columns: []string{principal.PrincipalMembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(principalmembership.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPrincipalMembershipsIDs(); len(nodes) > 0 && !_u.mutation.PrincipalMembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.PrincipalMembershipsTable,
			Columns: []string{principal.PrincipalMembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(principalmembership.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PrincipalMembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.PrincipalMembershipsTable,
			Columns: []string{principal.PrincipalMembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(principalmembership.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OwnedOrganizationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.OwnedOrganizationsTable,
			Columns: []string{principal.OwnedOrganizationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOwnedOrganizationsIDs(); len(nodes) > 0 && !_u.mutation.OwnedOrganizationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.OwnedOrganizationsTable,
			Columns: []string{principal.OwnedOrganizationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnedOrganizationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.OwnedOrganizationsTable,
			Columns: []string{principal.OwnedOrganizationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SentInvitesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.SentInvitesTable,
			Columns: []string{principal.SentInvitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invite.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSentInvitesIDs(); len(nodes) > 0 && !_u.mutation.SentInvitesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.SentInvitesTable,
			Columns: []string{principal.SentInvitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invite.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SentInvitesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.SentInvitesTable,
			Columns: []string{principal.SentInvitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invite.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OwnedListingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.OwnedListingsTable,
			Columns: []string{principal.OwnedListingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listing.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOwnedListingsIDs(); len(nodes) > 0 && !_u.mutation.OwnedListingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.OwnedListingsTable,
			Columns: []string{principal.OwnedListingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listing.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnedListingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.OwnedListingsTable,
			Columns: []string{principal.OwnedListingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listing.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PurchasedLicensesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.PurchasedLicensesTable,
			Columns: []string{principal.PurchasedLicensesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(license.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPurchasedLicensesIDs(); len(nodes) > 0 && !_u.mutation.PurchasedLicensesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.PurchasedLicensesTable,
			Columns: []string{principal.PurchasedLicensesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(license.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PurchasedLicensesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.PurchasedLicensesTable,
			Columns: []string{principal.PurchasedLicensesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(license.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SeatAssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.SeatAssignmentsTable,
			Columns: []string{principal.SeatAssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seatassignment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSeatAssignmentsIDs(); len(nodes) > 0 && !_u.mutation.SeatAssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.SeatAssignmentsTable,
			Columns: []string{principal.SeatAssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seatassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SeatAssignmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.SeatAssignmentsTable,
			Columns: []string{principal.SeatAssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seatassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssignedSeatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.AssignedSeatsTable,
			Columns: []string{principal.AssignedSeatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seatassignment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAssignedSeatsIDs(); len(nodes) > 0 && !_u.mutation.AssignedSeatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.AssignedSeatsTable,
			Columns: []string{principal.AssignedSeatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seatassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssignedSeatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   principal.AssignedSeatsTable,
			Columns: []string{principal.AssignedSeatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seatassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Principal{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{principal.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
