// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/plexusone/systemforge/identity/ent/agent"
	"github.com/plexusone/systemforge/identity/ent/application"
	"github.com/plexusone/systemforge/identity/ent/credential"
	"github.com/plexusone/systemforge/identity/ent/externalidentity"
	"github.com/plexusone/systemforge/identity/ent/human"
	"github.com/plexusone/systemforge/identity/ent/invite"
	"github.com/plexusone/systemforge/identity/ent/license"
	"github.com/plexusone/systemforge/identity/ent/listing"
	"github.com/plexusone/systemforge/identity/ent/organization"
	"github.com/plexusone/systemforge/identity/ent/predicate"
	"github.com/plexusone/systemforge/identity/ent/principal"
	"github.com/plexusone/systemforge/identity/ent/principalmembership"
	"github.com/plexusone/systemforge/identity/ent/principaltoken"
	"github.com/plexusone/systemforge/identity/ent/seatassignment"
	"github.com/plexusone/systemforge/identity/ent/serviceprincipal"
)

// PrincipalQuery is the builder for querying Principal entities.
type PrincipalQuery struct {
	config
	ctx                      *QueryContext
	order                    []principal.OrderOption
	inters                   []Interceptor
	predicates               []predicate.Principal
	withOrganization         *OrganizationQuery
	withHuman                *HumanQuery
	withApplication          *ApplicationQuery
	withAgent                *AgentQuery
	withServicePrincipal     *ServicePrincipalQuery
	withCredentials          *CredentialQuery
	withExternalIdentities   *ExternalIdentityQuery
	withPrincipalTokens      *PrincipalTokenQuery
	withPrincipalMemberships *PrincipalMembershipQuery
	withOwnedOrganizations   *OrganizationQuery
	withSentInvites          *InviteQuery
	withOwnedListings        *ListingQuery
	withPurchasedLicenses    *LicenseQuery
	withSeatAssignments      *SeatAssignmentQuery
	withAssignedSeats        *SeatAssignmentQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PrincipalQuery builder.
func (_q *PrincipalQuery) Where(ps ...predicate.Principal) *PrincipalQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *PrincipalQuery) Limit(limit int) *PrincipalQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *PrincipalQuery) Offset(offset int) *PrincipalQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *PrincipalQuery) Unique(unique bool) *PrincipalQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *PrincipalQuery) Order(o ...principal.OrderOption) *PrincipalQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryOrganization chains the current query on the "organization" edge.
func (_q *PrincipalQuery) QueryOrganization() *OrganizationQuery {
	query := (&OrganizationClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(principal.Table, principal.FieldID, selector),
			sqlgraph.To(organization.Table, organization.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, principal.OrganizationTable, principal.OrganizationColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryHuman chains the current query on the "human" edge.
func (_q *PrincipalQuery) QueryHuman() *HumanQuery {
	query := (&HumanClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(principal.Table, principal.FieldID, selector),
			sqlgraph.To(human.Table, human.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, principal.HumanTable, principal.HumanColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryApplication chains the current query on the "application" edge.
func (_q *PrincipalQuery) QueryApplication() *ApplicationQuery {
	query := (&ApplicationClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(principal.Table, principal.FieldID, selector),
			sqlgraph.To(application.Table, application.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, principal.ApplicationTable, principal.ApplicationColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAgent chains the current query on the "agent" edge.
func (_q *PrincipalQuery) QueryAgent() *AgentQuery {
	query := (&AgentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(principal.Table, principal.FieldID, selector),
			sqlgraph.To(agent.Table, agent.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, principal.AgentTable, principal.AgentColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryServicePrincipal chains the current query on the "service_principal" edge.
func (_q *PrincipalQuery) QueryServicePrincipal() *ServicePrincipalQuery {
	query := (&ServicePrincipalClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(principal.Table, principal.FieldID, selector),
			sqlgraph.To(serviceprincipal.Table, serviceprincipal.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, principal.ServicePrincipalTable, principal.ServicePrincipalColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCredentials chains the current query on the "credentials" edge.
func (_q *PrincipalQuery) QueryCredentials() *CredentialQuery {
	query := (&CredentialClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(principal.Table, principal.FieldID, selector),
			sqlgraph.To(credential.Table, credential.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, principal.CredentialsTable, principal.CredentialsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryExternalIdentities chains the current query on the "external_identities" edge.
func (_q *PrincipalQuery) QueryExternalIdentities() *ExternalIdentityQuery {
	query := (&ExternalIdentityClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(principal.Table, principal.FieldID, selector),
			sqlgraph.To(externalidentity.Table, externalidentity.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, principal.ExternalIdentitiesTable, principal.ExternalIdentitiesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPrincipalTokens chains the current query on the "principal_tokens" edge.
func (_q *PrincipalQuery) QueryPrincipalTokens() *PrincipalTokenQuery {
	query := (&PrincipalTokenClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(principal.Table, principal.FieldID, selector),
			sqlgraph.To(principaltoken.Table, principaltoken.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, principal.PrincipalTokensTable, principal.PrincipalTokensColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPrincipalMemberships chains the current query on the "principal_memberships" edge.
func (_q *PrincipalQuery) QueryPrincipalMemberships() *PrincipalMembershipQuery {
	query := (&PrincipalMembershipClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(principal.Table, principal.FieldID, selector),
			sqlgraph.To(principalmembership.Table, principalmembership.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, principal.PrincipalMembershipsTable, principal.PrincipalMembershipsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryOwnedOrganizations chains the current query on the "owned_organizations" edge.
func (_q *PrincipalQuery) QueryOwnedOrganizations() *OrganizationQuery {
	query := (&OrganizationClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(principal.Table, principal.FieldID, selector),
			sqlgraph.To(organization.Table, organization.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, principal.OwnedOrganizationsTable, principal.OwnedOrganizationsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySentInvites chains the current query on the "sent_invites" edge.
func (_q *PrincipalQuery) QuerySentInvites() *InviteQuery {
	query := (&InviteClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(principal.Table, principal.FieldID, selector),
			sqlgraph.To(invite.Table, invite.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, principal.SentInvitesTable, principal.SentInvitesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryOwnedListings chains the current query on the "owned_listings" edge.
func (_q *PrincipalQuery) QueryOwnedListings() *ListingQuery {
	query := (&ListingClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(principal.Table, principal.FieldID, selector),
			sqlgraph.To(listing.Table, listing.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, principal.OwnedListingsTable, principal.OwnedListingsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPurchasedLicenses chains the current query on the "purchased_licenses" edge.
func (_q *PrincipalQuery) QueryPurchasedLicenses() *LicenseQuery {
	query := (&LicenseClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(principal.Table, principal.FieldID, selector),
			sqlgraph.To(license.Table, license.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, principal.PurchasedLicensesTable, principal.PurchasedLicensesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySeatAssignments chains the current query on the "seat_assignments" edge.
func (_q *PrincipalQuery) QuerySeatAssignments() *SeatAssignmentQuery {
	query := (&SeatAssignmentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(principal.Table, principal.FieldID, selector),
			sqlgraph.To(seatassignment.Table, seatassignment.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, principal.SeatAssignmentsTable, principal.SeatAssignmentsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAssignedSeats chains the current query on the "assigned_seats" edge.
func (_q *PrincipalQuery) QueryAssignedSeats() *SeatAssignmentQuery {
	query := (&SeatAssignmentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(principal.Table, principal.FieldID, selector),
			sqlgraph.To(seatassignment.Table, seatassignment.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, principal.AssignedSeatsTable, principal.AssignedSeatsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Principal entity from the query.
// Returns a *NotFoundError when no Principal was found.
func (_q *PrincipalQuery) First(ctx context.Context) (*Principal, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{principal.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *PrincipalQuery) FirstX(ctx context.Context) *Principal {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Principal ID from the query.
// Returns a *NotFoundError when no Principal ID was found.
func (_q *PrincipalQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{principal.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *PrincipalQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Principal entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Principal entity is found.
// Returns a *NotFoundError when no Principal entities are found.
func (_q *PrincipalQuery) Only(ctx context.Context) (*Principal, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{principal.Label}
	default:
		return nil, &NotSingularError{principal.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *PrincipalQuery) OnlyX(ctx context.Context) *Principal {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Principal ID in the query.
// Returns a *NotSingularError when more than one Principal ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *PrincipalQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{principal.Label}
	default:
		err = &NotSingularError{principal.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *PrincipalQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Principals.
func (_q *PrincipalQuery) All(ctx context.Context) ([]*Principal, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Principal, *PrincipalQuery]()
	return withInterceptors[[]*Principal](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *PrincipalQuery) AllX(ctx context.Context) []*Principal {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Principal IDs.
func (_q *PrincipalQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(principal.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *PrincipalQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *PrincipalQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*PrincipalQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *PrincipalQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *PrincipalQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *PrincipalQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PrincipalQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *PrincipalQuery) Clone() *PrincipalQuery {
	if _q == nil {
		return nil
	}
	return &PrincipalQuery{
		config:                   _q.config,
		ctx:                      _q.ctx.Clone(),
		order:                    append([]principal.OrderOption{}, _q.order...),
		inters:                   append([]Interceptor{}, _q.inters...),
		predicates:               append([]predicate.Principal{}, _q.predicates...),
		withOrganization:         _q.withOrganization.Clone(),
		withHuman:                _q.withHuman.Clone(),
		withApplication:          _q.withApplication.Clone(),
		withAgent:                _q.withAgent.Clone(),
		withServicePrincipal:     _q.withServicePrincipal.Clone(),
		withCredentials:          _q.withCredentials.Clone(),
		withExternalIdentities:   _q.withExternalIdentities.Clone(),
		withPrincipalTokens:      _q.withPrincipalTokens.Clone(),
		withPrincipalMemberships: _q.withPrincipalMemberships.Clone(),
		withOwnedOrganizations:   _q.withOwnedOrganizations.Clone(),
		withSentInvites:          _q.withSentInvites.Clone(),
		withOwnedListings:        _q.withOwnedListings.Clone(),
		withPurchasedLicenses:    _q.withPurchasedLicenses.Clone(),
		withSeatAssignments:      _q.withSeatAssignments.Clone(),
		withAssignedSeats:        _q.withAssignedSeats.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithOrganization tells the query-builder to eager-load the nodes that are connected to
// the "organization" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PrincipalQuery) WithOrganization(opts ...func(*OrganizationQuery)) *PrincipalQuery {
	query := (&OrganizationClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOrganization = query
	return _q
}

// WithHuman tells the query-builder to eager-load the nodes that are connected to
// the "human" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PrincipalQuery) WithHuman(opts ...func(*HumanQuery)) *PrincipalQuery {
	query := (&HumanClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withHuman = query
	return _q
}

// WithApplication tells the query-builder to eager-load the nodes that are connected to
// the "application" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PrincipalQuery) WithApplication(opts ...func(*ApplicationQuery)) *PrincipalQuery {
	query := (&ApplicationClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withApplication = query
	return _q
}

// WithAgent tells the query-builder to eager-load the nodes that are connected to
// the "agent" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PrincipalQuery) WithAgent(opts ...func(*AgentQuery)) *PrincipalQuery {
	query := (&AgentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAgent = query
	return _q
}

// WithServicePrincipal tells the query-builder to eager-load the nodes that are connected to
// the "service_principal" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PrincipalQuery) WithServicePrincipal(opts ...func(*ServicePrincipalQuery)) *PrincipalQuery {
	query := (&ServicePrincipalClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withServicePrincipal = query
	return _q
}

// WithCredentials tells the query-builder to eager-load the nodes that are connected to
// the "credentials" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PrincipalQuery) WithCredentials(opts ...func(*CredentialQuery)) *PrincipalQuery {
	query := (&CredentialClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCredentials = query
	return _q
}

// WithExternalIdentities tells the query-builder to eager-load the nodes that are connected to
// the "external_identities" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PrincipalQuery) WithExternalIdentities(opts ...func(*ExternalIdentityQuery)) *PrincipalQuery {
	query := (&ExternalIdentityClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withExternalIdentities = query
	return _q
}

// WithPrincipalTokens tells the query-builder to eager-load the nodes that are connected to
// the "principal_tokens" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PrincipalQuery) WithPrincipalTokens(opts ...func(*PrincipalTokenQuery)) *PrincipalQuery {
	query := (&PrincipalTokenClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPrincipalTokens = query
	return _q
}

// WithPrincipalMemberships tells the query-builder to eager-load the nodes that are connected to
// the "principal_memberships" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PrincipalQuery) WithPrincipalMemberships(opts ...func(*PrincipalMembershipQuery)) *PrincipalQuery {
	query := (&PrincipalMembershipClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPrincipalMemberships = query
	return _q
}

// WithOwnedOrganizations tells the query-builder to eager-load the nodes that are connected to
// the "owned_organizations" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PrincipalQuery) WithOwnedOrganizations(opts ...func(*OrganizationQuery)) *PrincipalQuery {
	query := (&OrganizationClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOwnedOrganizations = query
	return _q
}

// WithSentInvites tells the query-builder to eager-load the nodes that are connected to
// the "sent_invites" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PrincipalQuery) WithSentInvites(opts ...func(*InviteQuery)) *PrincipalQuery {
	query := (&InviteClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSentInvites = query
	return _q
}

// WithOwnedListings tells the query-builder to eager-load the nodes that are connected to
// the "owned_listings" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PrincipalQuery) WithOwnedListings(opts ...func(*ListingQuery)) *PrincipalQuery {
	query := (&ListingClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOwnedListings = query
	return _q
}

// WithPurchasedLicenses tells the query-builder to eager-load the nodes that are connected to
// the "purchased_licenses" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PrincipalQuery) WithPurchasedLicenses(opts ...func(*LicenseQuery)) *PrincipalQuery {
	query := (&LicenseClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPurchasedLicenses = query
	return _q
}

// WithSeatAssignments tells the query-builder to eager-load the nodes that are connected to
// the "seat_assignments" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PrincipalQuery) WithSeatAssignments(opts ...func(*SeatAssignmentQuery)) *PrincipalQuery {
	query := (&SeatAssignmentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSeatAssignments = query
	return _q
}

// WithAssignedSeats tells the query-builder to eager-load the nodes that are connected to
// the "assigned_seats" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PrincipalQuery) WithAssignedSeats(opts ...func(*SeatAssignmentQuery)) *PrincipalQuery {
	query := (&SeatAssignmentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAssignedSeats = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Principal.Query().
//		GroupBy(principal.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *PrincipalQuery) GroupBy(field string, fields ...string) *PrincipalGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PrincipalGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = principal.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Principal.Query().
//		Select(principal.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *PrincipalQuery) Select(fields ...string) *PrincipalSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &PrincipalSelect{PrincipalQuery: _q}
	sbuild.label = principal.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PrincipalSelect configured with the given aggregations.
func (_q *PrincipalQuery) Aggregate(fns ...AggregateFunc) *PrincipalSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *PrincipalQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !principal.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *PrincipalQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Principal, error) {
	var (
		nodes       = []*Principal{}
		_spec       = _q.querySpec()
		loadedTypes = [15]bool{
			_q.withOrganization != nil,
			_q.withHuman != nil,
			_q.withApplication != nil,
			_q.withAgent != nil,
			_q.withServicePrincipal != nil,
			_q.withCredentials != nil,
			_q.withExternalIdentities != nil,
			_q.withPrincipalTokens != nil,
			_q.withPrincipalMemberships != nil,
			_q.withOwnedOrganizations != nil,
			_q.withSentInvites != nil,
			_q.withOwnedListings != nil,
			_q.withPurchasedLicenses != nil,
			_q.withSeatAssignments != nil,
			_q.withAssignedSeats != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Principal).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Principal{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withOrganization; query != nil {
		if err := _q.loadOrganization(ctx, query, nodes, nil,
			func(n *Principal, e *Organization) { n.Edges.Organization = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withHuman; query != nil {
		if err := _q.loadHuman(ctx, query, nodes, nil,
			func(n *Principal, e *Human) { n.Edges.Human = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withApplication; query != nil {
		if err := _q.loadApplication(ctx, query, nodes, nil,
			func(n *Principal, e *Application) { n.Edges.Application = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAgent; query != nil {
		if err := _q.loadAgent(ctx, query, nodes, nil,
			func(n *Principal, e *Agent) { n.Edges.Agent = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withServicePrincipal; query != nil {
		if err := _q.loadServicePrincipal(ctx, query, nodes, nil,
			func(n *Principal, e *ServicePrincipal) { n.Edges.ServicePrincipal = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCredentials; query != nil {
		if err := _q.loadCredentials(ctx, query, nodes,
			func(n *Principal) { n.Edges.Credentials = []*Credential{} },
			func(n *Principal, e *Credential) { n.Edges.Credentials = append(n.Edges.Credentials, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withExternalIdentities; query != nil {
		if err := _q.loadExternalIdentities(ctx, query, nodes,
			func(n *Principal) { n.Edges.ExternalIdentities = []*ExternalIdentity{} },
			func(n *Principal, e *ExternalIdentity) {
				n.Edges.ExternalIdentities = append(n.Edges.ExternalIdentities, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withPrincipalTokens; query != nil {
		if err := _q.loadPrincipalTokens(ctx, query, nodes,
			func(n *Principal) { n.Edges.PrincipalTokens = []*PrincipalToken{} },
			func(n *Principal, e *PrincipalToken) { n.Edges.PrincipalTokens = append(n.Edges.PrincipalTokens, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPrincipalMemberships; query != nil {
		if err := _q.loadPrincipalMemberships(ctx, query, nodes,
			func(n *Principal) { n.Edges.PrincipalMemberships = []*PrincipalMembership{} },
			func(n *Principal, e *PrincipalMembership) {
				n.Edges.PrincipalMemberships = append(n.Edges.PrincipalMemberships, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withOwnedOrganizations; query != nil {
		if err := _q.loadOwnedOrganizations(ctx, query, nodes,
			func(n *Principal) { n.Edges.OwnedOrganizations = []*Organization{} },
			func(n *Principal, e *Organization) {
				n.Edges.OwnedOrganizations = append(n.Edges.OwnedOrganizations, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withSentInvites; query != nil {
		if err := _q.loadSentInvites(ctx, query, nodes,
			func(n *Principal) { n.Edges.SentInvites = []*Invite{} },
			func(n *Principal, e *Invite) { n.Edges.SentInvites = append(n.Edges.SentInvites, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withOwnedListings; query != nil {
		if err := _q.loadOwnedListings(ctx, query, nodes,
			func(n *Principal) { n.Edges.OwnedListings = []*Listing{} },
			func(n *Principal, e *Listing) { n.Edges.OwnedListings = append(n.Edges.OwnedListings, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPurchasedLicenses; query != nil {
		if err := _q.loadPurchasedLicenses(ctx, query, nodes,
			func(n *Principal) { n.Edges.PurchasedLicenses = []*License{} },
			func(n *Principal, e *License) { n.Edges.PurchasedLicenses = append(n.Edges.PurchasedLicenses, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSeatAssignments; query != nil {
		if err := _q.loadSeatAssignments(ctx, query, nodes,
			func(n *Principal) { n.Edges.SeatAssignments = []*SeatAssignment{} },
			func(n *Principal, e *SeatAssignment) { n.Edges.SeatAssignments = append(n.Edges.SeatAssignments, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAssignedSeats; query != nil {
		if err := _q.loadAssignedSeats(ctx, query, nodes,
			func(n *Principal) { n.Edges.AssignedSeats = []*SeatAssignment{} },
			func(n *Principal, e *SeatAssignment) { n.Edges.AssignedSeats = append(n.Edges.AssignedSeats, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *PrincipalQuery) loadOrganization(ctx context.Context, query *OrganizationQuery, nodes []*Principal, init func(*Principal), assign func(*Principal, *Organization)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Principal)
	for i := range nodes {
		if nodes[i].OrganizationID == nil {
			continue
		}
		fk := *nodes[i].OrganizationID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(organization.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "organization_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *PrincipalQuery) loadHuman(ctx context.Context, query *HumanQuery, nodes []*Principal, init func(*Principal), assign func(*Principal, *Human)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Principal)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(human.FieldPrincipalID)
	}
	query.Where(predicate.Human(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(principal.HumanColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.PrincipalID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "principal_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *PrincipalQuery) loadApplication(ctx context.Context, query *ApplicationQuery, nodes []*Principal, init func(*Principal), assign func(*Principal, *Application)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Principal)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(application.FieldPrincipalID)
	}
	query.Where(predicate.Application(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(principal.ApplicationColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.PrincipalID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "principal_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *PrincipalQuery) loadAgent(ctx context.Context, query *AgentQuery, nodes []*Principal, init func(*Principal), assign func(*Principal, *Agent)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Principal)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(agent.FieldPrincipalID)
	}
	query.Where(predicate.Agent(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(principal.AgentColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.PrincipalID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "principal_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *PrincipalQuery) loadServicePrincipal(ctx context.Context, query *ServicePrincipalQuery, nodes []*Principal, init func(*Principal), assign func(*Principal, *ServicePrincipal)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Principal)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(serviceprincipal.FieldPrincipalID)
	}
	query.Where(predicate.ServicePrincipal(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(principal.ServicePrincipalColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.PrincipalID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "principal_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *PrincipalQuery) loadCredentials(ctx context.Context, query *CredentialQuery, nodes []*Principal, init func(*Principal), assign func(*Principal, *Credential)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Principal)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(credential.FieldPrincipalID)
	}
	query.Where(predicate.Credential(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(principal.CredentialsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.PrincipalID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "principal_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *PrincipalQuery) loadExternalIdentities(ctx context.Context, query *ExternalIdentityQuery, nodes []*Principal, init func(*Principal), assign func(*Principal, *ExternalIdentity)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Principal)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(externalidentity.FieldPrincipalID)
	}
	query.Where(predicate.ExternalIdentity(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(principal.ExternalIdentitiesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.PrincipalID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "principal_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *PrincipalQuery) loadPrincipalTokens(ctx context.Context, query *PrincipalTokenQuery, nodes []*Principal, init func(*Principal), assign func(*Principal, *PrincipalToken)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Principal)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(principaltoken.FieldPrincipalID)
	}
	query.Where(predicate.PrincipalToken(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(principal.PrincipalTokensColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.PrincipalID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "principal_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *PrincipalQuery) loadPrincipalMemberships(ctx context.Context, query *PrincipalMembershipQuery, nodes []*Principal, init func(*Principal), assign func(*Principal, *PrincipalMembership)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Principal)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(principalmembership.FieldPrincipalID)
	}
	query.Where(predicate.PrincipalMembership(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(principal.PrincipalMembershipsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.PrincipalID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "principal_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *PrincipalQuery) loadOwnedOrganizations(ctx context.Context, query *OrganizationQuery, nodes []*Principal, init func(*Principal), assign func(*Principal, *Organization)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Principal)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(organization.FieldOwnerPrincipalID)
	}
	query.Where(predicate.Organization(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(principal.OwnedOrganizationsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.OwnerPrincipalID
		if fk == nil {
			return fmt.Errorf(`foreign-key "owner_principal_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "owner_principal_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *PrincipalQuery) loadSentInvites(ctx context.Context, query *InviteQuery, nodes []*Principal, init func(*Principal), assign func(*Principal, *Invite)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Principal)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(invite.FieldInviterPrincipalID)
	}
	query.Where(predicate.Invite(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(principal.SentInvitesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.InviterPrincipalID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "inviter_principal_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *PrincipalQuery) loadOwnedListings(ctx context.Context, query *ListingQuery, nodes []*Principal, init func(*Principal), assign func(*Principal, *Listing)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Principal)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(listing.FieldOwnerID)
	}
	query.Where(predicate.Listing(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(principal.OwnedListingsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.OwnerID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "owner_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *PrincipalQuery) loadPurchasedLicenses(ctx context.Context, query *LicenseQuery, nodes []*Principal, init func(*Principal), assign func(*Principal, *License)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Principal)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(license.FieldPurchasedBy)
	}
	query.Where(predicate.License(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(principal.PurchasedLicensesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.PurchasedBy
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "purchased_by" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *PrincipalQuery) loadSeatAssignments(ctx context.Context, query *SeatAssignmentQuery, nodes []*Principal, init func(*Principal), assign func(*Principal, *SeatAssignment)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Principal)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(seatassignment.FieldPrincipalID)
	}
	query.Where(predicate.SeatAssignment(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(principal.SeatAssignmentsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.PrincipalID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "principal_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *PrincipalQuery) loadAssignedSeats(ctx context.Context, query *SeatAssignmentQuery, nodes []*Principal, init func(*Principal), assign func(*Principal, *SeatAssignment)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Principal)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(seatassignment.FieldAssignedBy)
	}
	query.Where(predicate.SeatAssignment(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(principal.AssignedSeatsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.AssignedBy
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "assigned_by" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *PrincipalQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *PrincipalQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(principal.Table, principal.Columns, sqlgraph.NewFieldSpec(principal.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, principal.FieldID)
		for i := range fields {
			if fields[i] != principal.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withOrganization != nil {
			_spec.Node.AddColumnOnce(principal.FieldOrganizationID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *PrincipalQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(principal.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = principal.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PrincipalGroupBy is the group-by builder for Principal entities.
type PrincipalGroupBy struct {
	selector
	build *PrincipalQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *PrincipalGroupBy) Aggregate(fns ...AggregateFunc) *PrincipalGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *PrincipalGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PrincipalQuery, *PrincipalGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *PrincipalGroupBy) sqlScan(ctx context.Context, root *PrincipalQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PrincipalSelect is the builder for selecting fields of Principal entities.
type PrincipalSelect struct {
	*PrincipalQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *PrincipalSelect) Aggregate(fns ...AggregateFunc) *PrincipalSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *PrincipalSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PrincipalQuery, *PrincipalSelect](ctx, _s.PrincipalQuery, _s, _s.inters, v)
}

func (_s *PrincipalSelect) sqlScan(ctx context.Context, root *PrincipalQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
