// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/plexusone/systemforge/identity/ent/agent"
	"github.com/plexusone/systemforge/identity/ent/apikey"
	"github.com/plexusone/systemforge/identity/ent/application"
	"github.com/plexusone/systemforge/identity/ent/credential"
	"github.com/plexusone/systemforge/identity/ent/externalidentity"
	"github.com/plexusone/systemforge/identity/ent/human"
	"github.com/plexusone/systemforge/identity/ent/invite"
	"github.com/plexusone/systemforge/identity/ent/license"
	"github.com/plexusone/systemforge/identity/ent/listing"
	"github.com/plexusone/systemforge/identity/ent/membership"
	"github.com/plexusone/systemforge/identity/ent/oauthaccount"
	"github.com/plexusone/systemforge/identity/ent/oauthapp"
	"github.com/plexusone/systemforge/identity/ent/oauthappsecret"
	"github.com/plexusone/systemforge/identity/ent/oauthauthcode"
	"github.com/plexusone/systemforge/identity/ent/oauthconsent"
	"github.com/plexusone/systemforge/identity/ent/oauthtoken"
	"github.com/plexusone/systemforge/identity/ent/organization"
	"github.com/plexusone/systemforge/identity/ent/principal"
	"github.com/plexusone/systemforge/identity/ent/principalmembership"
	"github.com/plexusone/systemforge/identity/ent/principaltoken"
	"github.com/plexusone/systemforge/identity/ent/refreshtoken"
	"github.com/plexusone/systemforge/identity/ent/schema"
	"github.com/plexusone/systemforge/identity/ent/seatassignment"
	"github.com/plexusone/systemforge/identity/ent/serviceaccount"
	"github.com/plexusone/systemforge/identity/ent/serviceaccountkeypair"
	"github.com/plexusone/systemforge/identity/ent/serviceprincipal"
	"github.com/plexusone/systemforge/identity/ent/subscription"
	"github.com/plexusone/systemforge/identity/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	apikeyMixin := schema.APIKey{}.Mixin()
	apikeyMixinFields0 := apikeyMixin[0].Fields()
	_ = apikeyMixinFields0
	apikeyFields := schema.APIKey{}.Fields()
	_ = apikeyFields
	// apikeyDescCreatedAt is the schema descriptor for created_at field.
	apikeyDescCreatedAt := apikeyMixinFields0[1].Descriptor()
	// apikey.DefaultCreatedAt holds the default value on creation for the created_at field.
	apikey.DefaultCreatedAt = apikeyDescCreatedAt.Default.(func() time.Time)
	// apikeyDescUpdatedAt is the schema descriptor for updated_at field.
	apikeyDescUpdatedAt := apikeyMixinFields0[2].Descriptor()
	// apikey.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	apikey.DefaultUpdatedAt = apikeyDescUpdatedAt.Default.(func() time.Time)
	// apikey.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	apikey.UpdateDefaultUpdatedAt = apikeyDescUpdatedAt.UpdateDefault.(func() time.Time)
	// apikeyDescName is the schema descriptor for name field.
	apikeyDescName := apikeyFields[0].Descriptor()
	// apikey.NameValidator is a validator for the "name" field. It is called by the builders before save.
	apikey.NameValidator = apikeyDescName.Validators[0].(func(string) error)
	// apikeyDescPrefix is the schema descriptor for prefix field.
	apikeyDescPrefix := apikeyFields[1].Descriptor()
	// apikey.PrefixValidator is a validator for the "prefix" field. It is called by the builders before save.
	apikey.PrefixValidator = apikeyDescPrefix.Validators[0].(func(string) error)
	// apikeyDescKeyHash is the schema descriptor for key_hash field.
	apikeyDescKeyHash := apikeyFields[2].Descriptor()
	// apikey.KeyHashValidator is a validator for the "key_hash" field. It is called by the builders before save.
	apikey.KeyHashValidator = apikeyDescKeyHash.Validators[0].(func(string) error)
	// apikeyDescRevoked is the schema descriptor for revoked field.
	apikeyDescRevoked := apikeyFields[8].Descriptor()
	// apikey.DefaultRevoked holds the default value on creation for the revoked field.
	apikey.DefaultRevoked = apikeyDescRevoked.Default.(bool)
	// apikeyDescID is the schema descriptor for id field.
	apikeyDescID := apikeyMixinFields0[0].Descriptor()
	// apikey.DefaultID holds the default value on creation for the id field.
	apikey.DefaultID = apikeyDescID.Default.(func() uuid.UUID)
	agentMixin := schema.Agent{}.Mixin()
	agentMixinFields0 := agentMixin[0].Fields()
	_ = agentMixinFields0
	agentFields := schema.Agent{}.Fields()
	_ = agentFields
	// agentDescCreatedAt is the schema descriptor for created_at field.
	agentDescCreatedAt := agentMixinFields0[1].Descriptor()
	// agent.DefaultCreatedAt holds the default value on creation for the created_at field.
	agent.DefaultCreatedAt = agentDescCreatedAt.Default.(func() time.Time)
	// agentDescUpdatedAt is the schema descriptor for updated_at field.
	agentDescUpdatedAt := agentMixinFields0[2].Descriptor()
	// agent.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	agent.DefaultUpdatedAt = agentDescUpdatedAt.Default.(func() time.Time)
	// agent.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	agent.UpdateDefaultUpdatedAt = agentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// agentDescModelID is the schema descriptor for model_id field.
	agentDescModelID := agentFields[1].Descriptor()
	// agent.ModelIDValidator is a validator for the "model_id" field. It is called by the builders before save.
	agent.ModelIDValidator = agentDescModelID.Validators[0].(func(string) error)
	// agentDescCapabilityConstraints is the schema descriptor for capability_constraints field.
	agentDescCapabilityConstraints := agentFields[4].Descriptor()
	// agent.DefaultCapabilityConstraints holds the default value on creation for the capability_constraints field.
	agent.DefaultCapabilityConstraints = agentDescCapabilityConstraints.Default.([]string)
	// agentDescResourceConstraints is the schema descriptor for resource_constraints field.
	agentDescResourceConstraints := agentFields[5].Descriptor()
	// agent.DefaultResourceConstraints holds the default value on creation for the resource_constraints field.
	agent.DefaultResourceConstraints = agentDescResourceConstraints.Default.([]string)
	// agentDescMaxTokenLifetime is the schema descriptor for max_token_lifetime field.
	agentDescMaxTokenLifetime := agentFields[6].Descriptor()
	// agent.DefaultMaxTokenLifetime holds the default value on creation for the max_token_lifetime field.
	agent.DefaultMaxTokenLifetime = agentDescMaxTokenLifetime.Default.(int)
	// agentDescRequiresConfirmation is the schema descriptor for requires_confirmation field.
	agentDescRequiresConfirmation := agentFields[8].Descriptor()
	// agent.DefaultRequiresConfirmation holds the default value on creation for the requires_confirmation field.
	agent.DefaultRequiresConfirmation = agentDescRequiresConfirmation.Default.(bool)
	// agentDescID is the schema descriptor for id field.
	agentDescID := agentMixinFields0[0].Descriptor()
	// agent.DefaultID holds the default value on creation for the id field.
	agent.DefaultID = agentDescID.Default.(func() uuid.UUID)
	applicationMixin := schema.Application{}.Mixin()
	applicationMixinFields0 := applicationMixin[0].Fields()
	_ = applicationMixinFields0
	applicationFields := schema.Application{}.Fields()
	_ = applicationFields
	// applicationDescCreatedAt is the schema descriptor for created_at field.
	applicationDescCreatedAt := applicationMixinFields0[1].Descriptor()
	// application.DefaultCreatedAt holds the default value on creation for the created_at field.
	application.DefaultCreatedAt = applicationDescCreatedAt.Default.(func() time.Time)
	// applicationDescUpdatedAt is the schema descriptor for updated_at field.
	applicationDescUpdatedAt := applicationMixinFields0[2].Descriptor()
	// application.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	application.DefaultUpdatedAt = applicationDescUpdatedAt.Default.(func() time.Time)
	// application.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	application.UpdateDefaultUpdatedAt = applicationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// applicationDescClientID is the schema descriptor for client_id field.
	applicationDescClientID := applicationFields[1].Descriptor()
	// application.ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	application.ClientIDValidator = applicationDescClientID.Validators[0].(func(string) error)
	// applicationDescDescription is the schema descriptor for description field.
	applicationDescDescription := applicationFields[2].Descriptor()
	// application.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	application.DescriptionValidator = applicationDescDescription.Validators[0].(func(string) error)
	// applicationDescRedirectUris is the schema descriptor for redirect_uris field.
	applicationDescRedirectUris := applicationFields[5].Descriptor()
	// application.DefaultRedirectUris holds the default value on creation for the redirect_uris field.
	application.DefaultRedirectUris = applicationDescRedirectUris.Default.([]string)
	// applicationDescAllowedGrants is the schema descriptor for allowed_grants field.
	applicationDescAllowedGrants := applicationFields[6].Descriptor()
	// application.DefaultAllowedGrants holds the default value on creation for the allowed_grants field.
	application.DefaultAllowedGrants = applicationDescAllowedGrants.Default.([]string)
	// applicationDescAllowedResponseTypes is the schema descriptor for allowed_response_types field.
	applicationDescAllowedResponseTypes := applicationFields[7].Descriptor()
	// application.DefaultAllowedResponseTypes holds the default value on creation for the allowed_response_types field.
	application.DefaultAllowedResponseTypes = applicationDescAllowedResponseTypes.Default.([]string)
	// applicationDescAccessTokenTTL is the schema descriptor for access_token_ttl field.
	applicationDescAccessTokenTTL := applicationFields[8].Descriptor()
	// application.DefaultAccessTokenTTL holds the default value on creation for the access_token_ttl field.
	application.DefaultAccessTokenTTL = applicationDescAccessTokenTTL.Default.(int)
	// applicationDescRefreshTokenTTL is the schema descriptor for refresh_token_ttl field.
	applicationDescRefreshTokenTTL := applicationFields[9].Descriptor()
	// application.DefaultRefreshTokenTTL holds the default value on creation for the refresh_token_ttl field.
	application.DefaultRefreshTokenTTL = applicationDescRefreshTokenTTL.Default.(int)
	// applicationDescRefreshTokenRotation is the schema descriptor for refresh_token_rotation field.
	applicationDescRefreshTokenRotation := applicationFields[10].Descriptor()
	// application.DefaultRefreshTokenRotation holds the default value on creation for the refresh_token_rotation field.
	application.DefaultRefreshTokenRotation = applicationDescRefreshTokenRotation.Default.(bool)
	// applicationDescFirstParty is the schema descriptor for first_party field.
	applicationDescFirstParty := applicationFields[11].Descriptor()
	// application.DefaultFirstParty holds the default value on creation for the first_party field.
	application.DefaultFirstParty = applicationDescFirstParty.Default.(bool)
	// applicationDescPublic is the schema descriptor for public field.
	applicationDescPublic := applicationFields[12].Descriptor()
	// application.DefaultPublic holds the default value on creation for the public field.
	application.DefaultPublic = applicationDescPublic.Default.(bool)
	// applicationDescID is the schema descriptor for id field.
	applicationDescID := applicationMixinFields0[0].Descriptor()
	// application.DefaultID holds the default value on creation for the id field.
	application.DefaultID = applicationDescID.Default.(func() uuid.UUID)
	credentialFields := schema.Credential{}.Fields()
	_ = credentialFields
	// credentialDescWebauthnSignCount is the schema descriptor for webauthn_sign_count field.
	credentialDescWebauthnSignCount := credentialFields[11].Descriptor()
	// credential.DefaultWebauthnSignCount holds the default value on creation for the webauthn_sign_count field.
	credential.DefaultWebauthnSignCount = credentialDescWebauthnSignCount.Default.(uint32)
	// credentialDescScopes is the schema descriptor for scopes field.
	credentialDescScopes := credentialFields[12].Descriptor()
	// credential.DefaultScopes holds the default value on creation for the scopes field.
	credential.DefaultScopes = credentialDescScopes.Default.([]string)
	// credentialDescActive is the schema descriptor for active field.
	credentialDescActive := credentialFields[13].Descriptor()
	// credential.DefaultActive holds the default value on creation for the active field.
	credential.DefaultActive = credentialDescActive.Default.(bool)
	// credentialDescRevoked is the schema descriptor for revoked field.
	credentialDescRevoked := credentialFields[15].Descriptor()
	// credential.DefaultRevoked holds the default value on creation for the revoked field.
	credential.DefaultRevoked = credentialDescRevoked.Default.(bool)
	// credentialDescCreatedAt is the schema descriptor for created_at field.
	credentialDescCreatedAt := credentialFields[22].Descriptor()
	// credential.DefaultCreatedAt holds the default value on creation for the created_at field.
	credential.DefaultCreatedAt = credentialDescCreatedAt.Default.(func() time.Time)
	// credentialDescUpdatedAt is the schema descriptor for updated_at field.
	credentialDescUpdatedAt := credentialFields[23].Descriptor()
	// credential.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	credential.DefaultUpdatedAt = credentialDescUpdatedAt.Default.(func() time.Time)
	// credential.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	credential.UpdateDefaultUpdatedAt = credentialDescUpdatedAt.UpdateDefault.(func() time.Time)
	// credentialDescID is the schema descriptor for id field.
	credentialDescID := credentialFields[0].Descriptor()
	// credential.DefaultID holds the default value on creation for the id field.
	credential.DefaultID = credentialDescID.Default.(func() uuid.UUID)
	externalidentityMixin := schema.ExternalIdentity{}.Mixin()
	externalidentityMixinFields0 := externalidentityMixin[0].Fields()
	_ = externalidentityMixinFields0
	externalidentityFields := schema.ExternalIdentity{}.Fields()
	_ = externalidentityFields
	// externalidentityDescCreatedAt is the schema descriptor for created_at field.
	externalidentityDescCreatedAt := externalidentityMixinFields0[1].Descriptor()
	// externalidentity.DefaultCreatedAt holds the default value on creation for the created_at field.
	externalidentity.DefaultCreatedAt = externalidentityDescCreatedAt.Default.(func() time.Time)
	// externalidentityDescUpdatedAt is the schema descriptor for updated_at field.
	externalidentityDescUpdatedAt := externalidentityMixinFields0[2].Descriptor()
	// externalidentity.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	externalidentity.DefaultUpdatedAt = externalidentityDescUpdatedAt.Default.(func() time.Time)
	// externalidentity.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	externalidentity.UpdateDefaultUpdatedAt = externalidentityDescUpdatedAt.UpdateDefault.(func() time.Time)
	// externalidentityDescProvider is the schema descriptor for provider field.
	externalidentityDescProvider := externalidentityFields[1].Descriptor()
	// externalidentity.ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	externalidentity.ProviderValidator = externalidentityDescProvider.Validators[0].(func(string) error)
	// externalidentityDescSubject is the schema descriptor for subject field.
	externalidentityDescSubject := externalidentityFields[2].Descriptor()
	// externalidentity.SubjectValidator is a validator for the "subject" field. It is called by the builders before save.
	externalidentity.SubjectValidator = externalidentityDescSubject.Validators[0].(func(string) error)
	// externalidentityDescEmailVerified is the schema descriptor for email_verified field.
	externalidentityDescEmailVerified := externalidentityFields[4].Descriptor()
	// externalidentity.DefaultEmailVerified holds the default value on creation for the email_verified field.
	externalidentity.DefaultEmailVerified = externalidentityDescEmailVerified.Default.(bool)
	// externalidentityDescID is the schema descriptor for id field.
	externalidentityDescID := externalidentityMixinFields0[0].Descriptor()
	// externalidentity.DefaultID holds the default value on creation for the id field.
	externalidentity.DefaultID = externalidentityDescID.Default.(func() uuid.UUID)
	humanMixin := schema.Human{}.Mixin()
	humanMixinFields0 := humanMixin[0].Fields()
	_ = humanMixinFields0
	humanFields := schema.Human{}.Fields()
	_ = humanFields
	// humanDescCreatedAt is the schema descriptor for created_at field.
	humanDescCreatedAt := humanMixinFields0[1].Descriptor()
	// human.DefaultCreatedAt holds the default value on creation for the created_at field.
	human.DefaultCreatedAt = humanDescCreatedAt.Default.(func() time.Time)
	// humanDescUpdatedAt is the schema descriptor for updated_at field.
	humanDescUpdatedAt := humanMixinFields0[2].Descriptor()
	// human.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	human.DefaultUpdatedAt = humanDescUpdatedAt.Default.(func() time.Time)
	// human.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	human.UpdateDefaultUpdatedAt = humanDescUpdatedAt.UpdateDefault.(func() time.Time)
	// humanDescEmail is the schema descriptor for email field.
	humanDescEmail := humanFields[1].Descriptor()
	// human.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	human.EmailValidator = humanDescEmail.Validators[0].(func(string) error)
	// humanDescLocale is the schema descriptor for locale field.
	humanDescLocale := humanFields[5].Descriptor()
	// human.DefaultLocale holds the default value on creation for the locale field.
	human.DefaultLocale = humanDescLocale.Default.(string)
	// humanDescTimezone is the schema descriptor for timezone field.
	humanDescTimezone := humanFields[6].Descriptor()
	// human.DefaultTimezone holds the default value on creation for the timezone field.
	human.DefaultTimezone = humanDescTimezone.Default.(string)
	// humanDescIsPlatformAdmin is the schema descriptor for is_platform_admin field.
	humanDescIsPlatformAdmin := humanFields[7].Descriptor()
	// human.DefaultIsPlatformAdmin holds the default value on creation for the is_platform_admin field.
	human.DefaultIsPlatformAdmin = humanDescIsPlatformAdmin.Default.(bool)
	// humanDescID is the schema descriptor for id field.
	humanDescID := humanMixinFields0[0].Descriptor()
	// human.DefaultID holds the default value on creation for the id field.
	human.DefaultID = humanDescID.Default.(func() uuid.UUID)
	inviteMixin := schema.Invite{}.Mixin()
	inviteMixinFields0 := inviteMixin[0].Fields()
	_ = inviteMixinFields0
	inviteFields := schema.Invite{}.Fields()
	_ = inviteFields
	// inviteDescCreatedAt is the schema descriptor for created_at field.
	inviteDescCreatedAt := inviteMixinFields0[1].Descriptor()
	// invite.DefaultCreatedAt holds the default value on creation for the created_at field.
	invite.DefaultCreatedAt = inviteDescCreatedAt.Default.(func() time.Time)
	// inviteDescUpdatedAt is the schema descriptor for updated_at field.
	inviteDescUpdatedAt := inviteMixinFields0[2].Descriptor()
	// invite.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	invite.DefaultUpdatedAt = inviteDescUpdatedAt.Default.(func() time.Time)
	// invite.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	invite.UpdateDefaultUpdatedAt = inviteDescUpdatedAt.UpdateDefault.(func() time.Time)
	// inviteDescEmail is the schema descriptor for email field.
	inviteDescEmail := inviteFields[2].Descriptor()
	// invite.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	invite.EmailValidator = inviteDescEmail.Validators[0].(func(string) error)
	// inviteDescRole is the schema descriptor for role field.
	inviteDescRole := inviteFields[3].Descriptor()
	// invite.DefaultRole holds the default value on creation for the role field.
	invite.DefaultRole = inviteDescRole.Default.(string)
	// invite.RoleValidator is a validator for the "role" field. It is called by the builders before save.
	invite.RoleValidator = inviteDescRole.Validators[0].(func(string) error)
	// inviteDescToken is the schema descriptor for token field.
	inviteDescToken := inviteFields[4].Descriptor()
	// invite.TokenValidator is a validator for the "token" field. It is called by the builders before save.
	invite.TokenValidator = inviteDescToken.Validators[0].(func(string) error)
	// inviteDescResendCount is the schema descriptor for resend_count field.
	inviteDescResendCount := inviteFields[10].Descriptor()
	// invite.DefaultResendCount holds the default value on creation for the resend_count field.
	invite.DefaultResendCount = inviteDescResendCount.Default.(int)
	// inviteDescLastSentAt is the schema descriptor for last_sent_at field.
	inviteDescLastSentAt := inviteFields[11].Descriptor()
	// invite.DefaultLastSentAt holds the default value on creation for the last_sent_at field.
	invite.DefaultLastSentAt = inviteDescLastSentAt.Default.(func() time.Time)
	// inviteDescID is the schema descriptor for id field.
	inviteDescID := inviteMixinFields0[0].Descriptor()
	// invite.DefaultID holds the default value on creation for the id field.
	invite.DefaultID = inviteDescID.Default.(func() uuid.UUID)
	licenseMixin := schema.License{}.Mixin()
	licenseMixinFields0 := licenseMixin[0].Fields()
	_ = licenseMixinFields0
	licenseFields := schema.License{}.Fields()
	_ = licenseFields
	// licenseDescUsedSeats is the schema descriptor for used_seats field.
	licenseDescUsedSeats := licenseMixinFields0[6].Descriptor()
	// license.DefaultUsedSeats holds the default value on creation for the used_seats field.
	license.DefaultUsedSeats = licenseDescUsedSeats.Default.(int)
	// licenseDescValidFrom is the schema descriptor for valid_from field.
	licenseDescValidFrom := licenseMixinFields0[7].Descriptor()
	// license.DefaultValidFrom holds the default value on creation for the valid_from field.
	license.DefaultValidFrom = licenseDescValidFrom.Default.(func() time.Time)
	// licenseDescCreatedAt is the schema descriptor for created_at field.
	licenseDescCreatedAt := licenseMixinFields0[10].Descriptor()
	// license.DefaultCreatedAt holds the default value on creation for the created_at field.
	license.DefaultCreatedAt = licenseDescCreatedAt.Default.(func() time.Time)
	// licenseDescUpdatedAt is the schema descriptor for updated_at field.
	licenseDescUpdatedAt := licenseMixinFields0[11].Descriptor()
	// license.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	license.DefaultUpdatedAt = licenseDescUpdatedAt.Default.(func() time.Time)
	// license.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	license.UpdateDefaultUpdatedAt = licenseDescUpdatedAt.UpdateDefault.(func() time.Time)
	// licenseDescID is the schema descriptor for id field.
	licenseDescID := licenseMixinFields0[0].Descriptor()
	// license.DefaultID holds the default value on creation for the id field.
	license.DefaultID = licenseDescID.Default.(func() uuid.UUID)
	listingMixin := schema.Listing{}.Mixin()
	listingMixinFields0 := listingMixin[0].Fields()
	_ = listingMixinFields0
	listingFields := schema.Listing{}.Fields()
	_ = listingFields
	// listingDescProductType is the schema descriptor for product_type field.
	listingDescProductType := listingMixinFields0[3].Descriptor()
	// listing.ProductTypeValidator is a validator for the "product_type" field. It is called by the builders before save.
	listing.ProductTypeValidator = listingDescProductType.Validators[0].(func(string) error)
	// listingDescTitle is the schema descriptor for title field.
	listingDescTitle := listingMixinFields0[5].Descriptor()
	// listing.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	listing.TitleValidator = func() func(string) error {
		validators := listingDescTitle.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(title string) error {
			for _, fn := range fns {
				if err := fn(title); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// listingDescPriceCents is the schema descriptor for price_cents field.
	listingDescPriceCents := listingMixinFields0[8].Descriptor()
	// listing.DefaultPriceCents holds the default value on creation for the price_cents field.
	listing.DefaultPriceCents = listingDescPriceCents.Default.(int64)
	// listingDescCurrency is the schema descriptor for currency field.
	listingDescCurrency := listingMixinFields0[9].Descriptor()
	// listing.DefaultCurrency holds the default value on creation for the currency field.
	listing.DefaultCurrency = listingDescCurrency.Default.(string)
	// listing.CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	listing.CurrencyValidator = listingDescCurrency.Validators[0].(func(string) error)
	// listingDescCreatedAt is the schema descriptor for created_at field.
	listingDescCreatedAt := listingMixinFields0[12].Descriptor()
	// listing.DefaultCreatedAt holds the default value on creation for the created_at field.
	listing.DefaultCreatedAt = listingDescCreatedAt.Default.(func() time.Time)
	// listingDescUpdatedAt is the schema descriptor for updated_at field.
	listingDescUpdatedAt := listingMixinFields0[13].Descriptor()
	// listing.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	listing.DefaultUpdatedAt = listingDescUpdatedAt.Default.(func() time.Time)
	// listing.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	listing.UpdateDefaultUpdatedAt = listingDescUpdatedAt.UpdateDefault.(func() time.Time)
	// listingDescID is the schema descriptor for id field.
	listingDescID := listingMixinFields0[0].Descriptor()
	// listing.DefaultID holds the default value on creation for the id field.
	listing.DefaultID = listingDescID.Default.(func() uuid.UUID)
	membershipMixin := schema.Membership{}.Mixin()
	membershipMixinFields0 := membershipMixin[0].Fields()
	_ = membershipMixinFields0
	membershipFields := schema.Membership{}.Fields()
	_ = membershipFields
	// membershipDescCreatedAt is the schema descriptor for created_at field.
	membershipDescCreatedAt := membershipMixinFields0[1].Descriptor()
	// membership.DefaultCreatedAt holds the default value on creation for the created_at field.
	membership.DefaultCreatedAt = membershipDescCreatedAt.Default.(func() time.Time)
	// membershipDescUpdatedAt is the schema descriptor for updated_at field.
	membershipDescUpdatedAt := membershipMixinFields0[2].Descriptor()
	// membership.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	membership.DefaultUpdatedAt = membershipDescUpdatedAt.Default.(func() time.Time)
	// membership.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	membership.UpdateDefaultUpdatedAt = membershipDescUpdatedAt.UpdateDefault.(func() time.Time)
	// membershipDescRole is the schema descriptor for role field.
	membershipDescRole := membershipFields[2].Descriptor()
	// membership.RoleValidator is a validator for the "role" field. It is called by the builders before save.
	membership.RoleValidator = membershipDescRole.Validators[0].(func(string) error)
	// membershipDescID is the schema descriptor for id field.
	membershipDescID := membershipMixinFields0[0].Descriptor()
	// membership.DefaultID holds the default value on creation for the id field.
	membership.DefaultID = membershipDescID.Default.(func() uuid.UUID)
	oauthaccountMixin := schema.OAuthAccount{}.Mixin()
	oauthaccountMixinFields0 := oauthaccountMixin[0].Fields()
	_ = oauthaccountMixinFields0
	oauthaccountFields := schema.OAuthAccount{}.Fields()
	_ = oauthaccountFields
	// oauthaccountDescCreatedAt is the schema descriptor for created_at field.
	oauthaccountDescCreatedAt := oauthaccountMixinFields0[1].Descriptor()
	// oauthaccount.DefaultCreatedAt holds the default value on creation for the created_at field.
	oauthaccount.DefaultCreatedAt = oauthaccountDescCreatedAt.Default.(func() time.Time)
	// oauthaccountDescUpdatedAt is the schema descriptor for updated_at field.
	oauthaccountDescUpdatedAt := oauthaccountMixinFields0[2].Descriptor()
	// oauthaccount.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	oauthaccount.DefaultUpdatedAt = oauthaccountDescUpdatedAt.Default.(func() time.Time)
	// oauthaccount.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	oauthaccount.UpdateDefaultUpdatedAt = oauthaccountDescUpdatedAt.UpdateDefault.(func() time.Time)
	// oauthaccountDescProvider is the schema descriptor for provider field.
	oauthaccountDescProvider := oauthaccountFields[1].Descriptor()
	// oauthaccount.ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	oauthaccount.ProviderValidator = oauthaccountDescProvider.Validators[0].(func(string) error)
	// oauthaccountDescProviderUserID is the schema descriptor for provider_user_id field.
	oauthaccountDescProviderUserID := oauthaccountFields[2].Descriptor()
	// oauthaccount.ProviderUserIDValidator is a validator for the "provider_user_id" field. It is called by the builders before save.
	oauthaccount.ProviderUserIDValidator = oauthaccountDescProviderUserID.Validators[0].(func(string) error)
	// oauthaccountDescID is the schema descriptor for id field.
	oauthaccountDescID := oauthaccountMixinFields0[0].Descriptor()
	// oauthaccount.DefaultID holds the default value on creation for the id field.
	oauthaccount.DefaultID = oauthaccountDescID.Default.(func() uuid.UUID)
	oauthappFields := schema.OAuthApp{}.Fields()
	_ = oauthappFields
	// oauthappDescClientID is the schema descriptor for client_id field.
	oauthappDescClientID := oauthappFields[1].Descriptor()
	// oauthapp.ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	oauthapp.ClientIDValidator = oauthappDescClientID.Validators[0].(func(string) error)
	// oauthappDescName is the schema descriptor for name field.
	oauthappDescName := oauthappFields[2].Descriptor()
	// oauthapp.NameValidator is a validator for the "name" field. It is called by the builders before save.
	oauthapp.NameValidator = func() func(string) error {
		validators := oauthappDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// oauthappDescDescription is the schema descriptor for description field.
	oauthappDescDescription := oauthappFields[3].Descriptor()
	// oauthapp.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	oauthapp.DescriptionValidator = oauthappDescDescription.Validators[0].(func(string) error)
	// oauthappDescRedirectUris is the schema descriptor for redirect_uris field.
	oauthappDescRedirectUris := oauthappFields[8].Descriptor()
	// oauthapp.DefaultRedirectUris holds the default value on creation for the redirect_uris field.
	oauthapp.DefaultRedirectUris = oauthappDescRedirectUris.Default.([]string)
	// oauthappDescAllowedScopes is the schema descriptor for allowed_scopes field.
	oauthappDescAllowedScopes := oauthappFields[9].Descriptor()
	// oauthapp.DefaultAllowedScopes holds the default value on creation for the allowed_scopes field.
	oauthapp.DefaultAllowedScopes = oauthappDescAllowedScopes.Default.([]string)
	// oauthappDescAllowedGrants is the schema descriptor for allowed_grants field.
	oauthappDescAllowedGrants := oauthappFields[10].Descriptor()
	// oauthapp.DefaultAllowedGrants holds the default value on creation for the allowed_grants field.
	oauthapp.DefaultAllowedGrants = oauthappDescAllowedGrants.Default.([]string)
	// oauthappDescAllowedResponseTypes is the schema descriptor for allowed_response_types field.
	oauthappDescAllowedResponseTypes := oauthappFields[11].Descriptor()
	// oauthapp.DefaultAllowedResponseTypes holds the default value on creation for the allowed_response_types field.
	oauthapp.DefaultAllowedResponseTypes = oauthappDescAllowedResponseTypes.Default.([]string)
	// oauthappDescAccessTokenTTL is the schema descriptor for access_token_ttl field.
	oauthappDescAccessTokenTTL := oauthappFields[12].Descriptor()
	// oauthapp.DefaultAccessTokenTTL holds the default value on creation for the access_token_ttl field.
	oauthapp.DefaultAccessTokenTTL = oauthappDescAccessTokenTTL.Default.(int)
	// oauthappDescRefreshTokenTTL is the schema descriptor for refresh_token_ttl field.
	oauthappDescRefreshTokenTTL := oauthappFields[13].Descriptor()
	// oauthapp.DefaultRefreshTokenTTL holds the default value on creation for the refresh_token_ttl field.
	oauthapp.DefaultRefreshTokenTTL = oauthappDescRefreshTokenTTL.Default.(int)
	// oauthappDescRefreshTokenRotation is the schema descriptor for refresh_token_rotation field.
	oauthappDescRefreshTokenRotation := oauthappFields[14].Descriptor()
	// oauthapp.DefaultRefreshTokenRotation holds the default value on creation for the refresh_token_rotation field.
	oauthapp.DefaultRefreshTokenRotation = oauthappDescRefreshTokenRotation.Default.(bool)
	// oauthappDescFirstParty is the schema descriptor for first_party field.
	oauthappDescFirstParty := oauthappFields[15].Descriptor()
	// oauthapp.DefaultFirstParty holds the default value on creation for the first_party field.
	oauthapp.DefaultFirstParty = oauthappDescFirstParty.Default.(bool)
	// oauthappDescPublic is the schema descriptor for public field.
	oauthappDescPublic := oauthappFields[16].Descriptor()
	// oauthapp.DefaultPublic holds the default value on creation for the public field.
	oauthapp.DefaultPublic = oauthappDescPublic.Default.(bool)
	// oauthappDescActive is the schema descriptor for active field.
	oauthappDescActive := oauthappFields[17].Descriptor()
	// oauthapp.DefaultActive holds the default value on creation for the active field.
	oauthapp.DefaultActive = oauthappDescActive.Default.(bool)
	// oauthappDescCreatedAt is the schema descriptor for created_at field.
	oauthappDescCreatedAt := oauthappFields[20].Descriptor()
	// oauthapp.DefaultCreatedAt holds the default value on creation for the created_at field.
	oauthapp.DefaultCreatedAt = oauthappDescCreatedAt.Default.(func() time.Time)
	// oauthappDescUpdatedAt is the schema descriptor for updated_at field.
	oauthappDescUpdatedAt := oauthappFields[21].Descriptor()
	// oauthapp.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	oauthapp.DefaultUpdatedAt = oauthappDescUpdatedAt.Default.(func() time.Time)
	// oauthapp.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	oauthapp.UpdateDefaultUpdatedAt = oauthappDescUpdatedAt.UpdateDefault.(func() time.Time)
	// oauthappDescID is the schema descriptor for id field.
	oauthappDescID := oauthappFields[0].Descriptor()
	// oauthapp.DefaultID holds the default value on creation for the id field.
	oauthapp.DefaultID = oauthappDescID.Default.(func() uuid.UUID)
	oauthappsecretFields := schema.OAuthAppSecret{}.Fields()
	_ = oauthappsecretFields
	// oauthappsecretDescSecretHash is the schema descriptor for secret_hash field.
	oauthappsecretDescSecretHash := oauthappsecretFields[2].Descriptor()
	// oauthappsecret.SecretHashValidator is a validator for the "secret_hash" field. It is called by the builders before save.
	oauthappsecret.SecretHashValidator = oauthappsecretDescSecretHash.Validators[0].(func(string) error)
	// oauthappsecretDescSecretPrefix is the schema descriptor for secret_prefix field.
	oauthappsecretDescSecretPrefix := oauthappsecretFields[3].Descriptor()
	// oauthappsecret.SecretPrefixValidator is a validator for the "secret_prefix" field. It is called by the builders before save.
	oauthappsecret.SecretPrefixValidator = oauthappsecretDescSecretPrefix.Validators[0].(func(string) error)
	// oauthappsecretDescRevoked is the schema descriptor for revoked field.
	oauthappsecretDescRevoked := oauthappsecretFields[6].Descriptor()
	// oauthappsecret.DefaultRevoked holds the default value on creation for the revoked field.
	oauthappsecret.DefaultRevoked = oauthappsecretDescRevoked.Default.(bool)
	// oauthappsecretDescCreatedAt is the schema descriptor for created_at field.
	oauthappsecretDescCreatedAt := oauthappsecretFields[8].Descriptor()
	// oauthappsecret.DefaultCreatedAt holds the default value on creation for the created_at field.
	oauthappsecret.DefaultCreatedAt = oauthappsecretDescCreatedAt.Default.(func() time.Time)
	// oauthappsecretDescID is the schema descriptor for id field.
	oauthappsecretDescID := oauthappsecretFields[0].Descriptor()
	// oauthappsecret.DefaultID holds the default value on creation for the id field.
	oauthappsecret.DefaultID = oauthappsecretDescID.Default.(func() uuid.UUID)
	oauthauthcodeFields := schema.OAuthAuthCode{}.Fields()
	_ = oauthauthcodeFields
	// oauthauthcodeDescCodeChallengeMethod is the schema descriptor for code_challenge_method field.
	oauthauthcodeDescCodeChallengeMethod := oauthauthcodeFields[5].Descriptor()
	// oauthauthcode.DefaultCodeChallengeMethod holds the default value on creation for the code_challenge_method field.
	oauthauthcode.DefaultCodeChallengeMethod = oauthauthcodeDescCodeChallengeMethod.Default.(string)
	// oauthauthcodeDescScopes is the schema descriptor for scopes field.
	oauthauthcodeDescScopes := oauthauthcodeFields[7].Descriptor()
	// oauthauthcode.DefaultScopes holds the default value on creation for the scopes field.
	oauthauthcode.DefaultScopes = oauthauthcodeDescScopes.Default.([]string)
	// oauthauthcodeDescUsed is the schema descriptor for used field.
	oauthauthcodeDescUsed := oauthauthcodeFields[12].Descriptor()
	// oauthauthcode.DefaultUsed holds the default value on creation for the used field.
	oauthauthcode.DefaultUsed = oauthauthcodeDescUsed.Default.(bool)
	// oauthauthcodeDescCreatedAt is the schema descriptor for created_at field.
	oauthauthcodeDescCreatedAt := oauthauthcodeFields[16].Descriptor()
	// oauthauthcode.DefaultCreatedAt holds the default value on creation for the created_at field.
	oauthauthcode.DefaultCreatedAt = oauthauthcodeDescCreatedAt.Default.(func() time.Time)
	// oauthauthcodeDescID is the schema descriptor for id field.
	oauthauthcodeDescID := oauthauthcodeFields[0].Descriptor()
	// oauthauthcode.DefaultID holds the default value on creation for the id field.
	oauthauthcode.DefaultID = oauthauthcodeDescID.Default.(func() uuid.UUID)
	oauthconsentFields := schema.OAuthConsent{}.Fields()
	_ = oauthconsentFields
	// oauthconsentDescScopes is the schema descriptor for scopes field.
	oauthconsentDescScopes := oauthconsentFields[3].Descriptor()
	// oauthconsent.DefaultScopes holds the default value on creation for the scopes field.
	oauthconsent.DefaultScopes = oauthconsentDescScopes.Default.([]string)
	// oauthconsentDescGranted is the schema descriptor for granted field.
	oauthconsentDescGranted := oauthconsentFields[4].Descriptor()
	// oauthconsent.DefaultGranted holds the default value on creation for the granted field.
	oauthconsent.DefaultGranted = oauthconsentDescGranted.Default.(bool)
	// oauthconsentDescGrantedAt is the schema descriptor for granted_at field.
	oauthconsentDescGrantedAt := oauthconsentFields[5].Descriptor()
	// oauthconsent.DefaultGrantedAt holds the default value on creation for the granted_at field.
	oauthconsent.DefaultGrantedAt = oauthconsentDescGrantedAt.Default.(func() time.Time)
	// oauthconsentDescRevoked is the schema descriptor for revoked field.
	oauthconsentDescRevoked := oauthconsentFields[7].Descriptor()
	// oauthconsent.DefaultRevoked holds the default value on creation for the revoked field.
	oauthconsent.DefaultRevoked = oauthconsentDescRevoked.Default.(bool)
	// oauthconsentDescCreatedAt is the schema descriptor for created_at field.
	oauthconsentDescCreatedAt := oauthconsentFields[10].Descriptor()
	// oauthconsent.DefaultCreatedAt holds the default value on creation for the created_at field.
	oauthconsent.DefaultCreatedAt = oauthconsentDescCreatedAt.Default.(func() time.Time)
	// oauthconsentDescUpdatedAt is the schema descriptor for updated_at field.
	oauthconsentDescUpdatedAt := oauthconsentFields[11].Descriptor()
	// oauthconsent.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	oauthconsent.DefaultUpdatedAt = oauthconsentDescUpdatedAt.Default.(func() time.Time)
	// oauthconsent.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	oauthconsent.UpdateDefaultUpdatedAt = oauthconsentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// oauthconsentDescID is the schema descriptor for id field.
	oauthconsentDescID := oauthconsentFields[0].Descriptor()
	// oauthconsent.DefaultID holds the default value on creation for the id field.
	oauthconsent.DefaultID = oauthconsentDescID.Default.(func() uuid.UUID)
	oauthtokenFields := schema.OAuthToken{}.Fields()
	_ = oauthtokenFields
	// oauthtokenDescFamilyID is the schema descriptor for family_id field.
	oauthtokenDescFamilyID := oauthtokenFields[6].Descriptor()
	// oauthtoken.DefaultFamilyID holds the default value on creation for the family_id field.
	oauthtoken.DefaultFamilyID = oauthtokenDescFamilyID.Default.(func() uuid.UUID)
	// oauthtokenDescScopes is the schema descriptor for scopes field.
	oauthtokenDescScopes := oauthtokenFields[7].Descriptor()
	// oauthtoken.DefaultScopes holds the default value on creation for the scopes field.
	oauthtoken.DefaultScopes = oauthtokenDescScopes.Default.([]string)
	// oauthtokenDescAudience is the schema descriptor for audience field.
	oauthtokenDescAudience := oauthtokenFields[8].Descriptor()
	// oauthtoken.DefaultAudience holds the default value on creation for the audience field.
	oauthtoken.DefaultAudience = oauthtokenDescAudience.Default.([]string)
	// oauthtokenDescRevoked is the schema descriptor for revoked field.
	oauthtokenDescRevoked := oauthtokenFields[13].Descriptor()
	// oauthtoken.DefaultRevoked holds the default value on creation for the revoked field.
	oauthtoken.DefaultRevoked = oauthtokenDescRevoked.Default.(bool)
	// oauthtokenDescCreatedAt is the schema descriptor for created_at field.
	oauthtokenDescCreatedAt := oauthtokenFields[19].Descriptor()
	// oauthtoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	oauthtoken.DefaultCreatedAt = oauthtokenDescCreatedAt.Default.(func() time.Time)
	// oauthtokenDescID is the schema descriptor for id field.
	oauthtokenDescID := oauthtokenFields[0].Descriptor()
	// oauthtoken.DefaultID holds the default value on creation for the id field.
	oauthtoken.DefaultID = oauthtokenDescID.Default.(func() uuid.UUID)
	organizationMixin := schema.Organization{}.Mixin()
	organizationMixinFields0 := organizationMixin[0].Fields()
	_ = organizationMixinFields0
	organizationFields := schema.Organization{}.Fields()
	_ = organizationFields
	// organizationDescCreatedAt is the schema descriptor for created_at field.
	organizationDescCreatedAt := organizationMixinFields0[1].Descriptor()
	// organization.DefaultCreatedAt holds the default value on creation for the created_at field.
	organization.DefaultCreatedAt = organizationDescCreatedAt.Default.(func() time.Time)
	// organizationDescUpdatedAt is the schema descriptor for updated_at field.
	organizationDescUpdatedAt := organizationMixinFields0[2].Descriptor()
	// organization.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	organization.DefaultUpdatedAt = organizationDescUpdatedAt.Default.(func() time.Time)
	// organization.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	organization.UpdateDefaultUpdatedAt = organizationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// organizationDescName is the schema descriptor for name field.
	organizationDescName := organizationFields[0].Descriptor()
	// organization.NameValidator is a validator for the "name" field. It is called by the builders before save.
	organization.NameValidator = organizationDescName.Validators[0].(func(string) error)
	// organizationDescSlug is the schema descriptor for slug field.
	organizationDescSlug := organizationFields[1].Descriptor()
	// organization.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	organization.SlugValidator = organizationDescSlug.Validators[0].(func(string) error)
	// organizationDescActive is the schema descriptor for active field.
	organizationDescActive := organizationFields[9].Descriptor()
	// organization.DefaultActive holds the default value on creation for the active field.
	organization.DefaultActive = organizationDescActive.Default.(bool)
	// organizationDescID is the schema descriptor for id field.
	organizationDescID := organizationMixinFields0[0].Descriptor()
	// organization.DefaultID holds the default value on creation for the id field.
	organization.DefaultID = organizationDescID.Default.(func() uuid.UUID)
	principalMixin := schema.Principal{}.Mixin()
	principalMixinFields0 := principalMixin[0].Fields()
	_ = principalMixinFields0
	principalFields := schema.Principal{}.Fields()
	_ = principalFields
	// principalDescCreatedAt is the schema descriptor for created_at field.
	principalDescCreatedAt := principalMixinFields0[1].Descriptor()
	// principal.DefaultCreatedAt holds the default value on creation for the created_at field.
	principal.DefaultCreatedAt = principalDescCreatedAt.Default.(func() time.Time)
	// principalDescUpdatedAt is the schema descriptor for updated_at field.
	principalDescUpdatedAt := principalMixinFields0[2].Descriptor()
	// principal.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	principal.DefaultUpdatedAt = principalDescUpdatedAt.Default.(func() time.Time)
	// principal.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	principal.UpdateDefaultUpdatedAt = principalDescUpdatedAt.UpdateDefault.(func() time.Time)
	// principalDescIdentifier is the schema descriptor for identifier field.
	principalDescIdentifier := principalFields[1].Descriptor()
	// principal.IdentifierValidator is a validator for the "identifier" field. It is called by the builders before save.
	principal.IdentifierValidator = principalDescIdentifier.Validators[0].(func(string) error)
	// principalDescDisplayName is the schema descriptor for display_name field.
	principalDescDisplayName := principalFields[2].Descriptor()
	// principal.DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	principal.DisplayNameValidator = principalDescDisplayName.Validators[0].(func(string) error)
	// principalDescActive is the schema descriptor for active field.
	principalDescActive := principalFields[4].Descriptor()
	// principal.DefaultActive holds the default value on creation for the active field.
	principal.DefaultActive = principalDescActive.Default.(bool)
	// principalDescCapabilities is the schema descriptor for capabilities field.
	principalDescCapabilities := principalFields[5].Descriptor()
	// principal.DefaultCapabilities holds the default value on creation for the capabilities field.
	principal.DefaultCapabilities = principalDescCapabilities.Default.(map[string]bool)
	// principalDescAllowedScopes is the schema descriptor for allowed_scopes field.
	principalDescAllowedScopes := principalFields[6].Descriptor()
	// principal.DefaultAllowedScopes holds the default value on creation for the allowed_scopes field.
	principal.DefaultAllowedScopes = principalDescAllowedScopes.Default.([]string)
	// principalDescID is the schema descriptor for id field.
	principalDescID := principalMixinFields0[0].Descriptor()
	// principal.DefaultID holds the default value on creation for the id field.
	principal.DefaultID = principalDescID.Default.(func() uuid.UUID)
	principalmembershipMixin := schema.PrincipalMembership{}.Mixin()
	principalmembershipMixinFields0 := principalmembershipMixin[0].Fields()
	_ = principalmembershipMixinFields0
	principalmembershipFields := schema.PrincipalMembership{}.Fields()
	_ = principalmembershipFields
	// principalmembershipDescCreatedAt is the schema descriptor for created_at field.
	principalmembershipDescCreatedAt := principalmembershipMixinFields0[1].Descriptor()
	// principalmembership.DefaultCreatedAt holds the default value on creation for the created_at field.
	principalmembership.DefaultCreatedAt = principalmembershipDescCreatedAt.Default.(func() time.Time)
	// principalmembershipDescUpdatedAt is the schema descriptor for updated_at field.
	principalmembershipDescUpdatedAt := principalmembershipMixinFields0[2].Descriptor()
	// principalmembership.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	principalmembership.DefaultUpdatedAt = principalmembershipDescUpdatedAt.Default.(func() time.Time)
	// principalmembership.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	principalmembership.UpdateDefaultUpdatedAt = principalmembershipDescUpdatedAt.UpdateDefault.(func() time.Time)
	// principalmembershipDescRole is the schema descriptor for role field.
	principalmembershipDescRole := principalmembershipFields[2].Descriptor()
	// principalmembership.RoleValidator is a validator for the "role" field. It is called by the builders before save.
	principalmembership.RoleValidator = principalmembershipDescRole.Validators[0].(func(string) error)
	// principalmembershipDescActive is the schema descriptor for active field.
	principalmembershipDescActive := principalmembershipFields[4].Descriptor()
	// principalmembership.DefaultActive holds the default value on creation for the active field.
	principalmembership.DefaultActive = principalmembershipDescActive.Default.(bool)
	// principalmembershipDescID is the schema descriptor for id field.
	principalmembershipDescID := principalmembershipMixinFields0[0].Descriptor()
	// principalmembership.DefaultID holds the default value on creation for the id field.
	principalmembership.DefaultID = principalmembershipDescID.Default.(func() uuid.UUID)
	principaltokenFields := schema.PrincipalToken{}.Fields()
	_ = principaltokenFields
	// principaltokenDescFamilyID is the schema descriptor for family_id field.
	principaltokenDescFamilyID := principaltokenFields[6].Descriptor()
	// principaltoken.DefaultFamilyID holds the default value on creation for the family_id field.
	principaltoken.DefaultFamilyID = principaltokenDescFamilyID.Default.(func() uuid.UUID)
	// principaltokenDescScopes is the schema descriptor for scopes field.
	principaltokenDescScopes := principaltokenFields[8].Descriptor()
	// principaltoken.DefaultScopes holds the default value on creation for the scopes field.
	principaltoken.DefaultScopes = principaltokenDescScopes.Default.([]string)
	// principaltokenDescAudience is the schema descriptor for audience field.
	principaltokenDescAudience := principaltokenFields[9].Descriptor()
	// principaltoken.DefaultAudience holds the default value on creation for the audience field.
	principaltoken.DefaultAudience = principaltokenDescAudience.Default.([]string)
	// principaltokenDescCapabilities is the schema descriptor for capabilities field.
	principaltokenDescCapabilities := principaltokenFields[10].Descriptor()
	// principaltoken.DefaultCapabilities holds the default value on creation for the capabilities field.
	principaltoken.DefaultCapabilities = principaltokenDescCapabilities.Default.(map[string]bool)
	// principaltokenDescDelegationChain is the schema descriptor for delegation_chain field.
	principaltokenDescDelegationChain := principaltokenFields[11].Descriptor()
	// principaltoken.DefaultDelegationChain holds the default value on creation for the delegation_chain field.
	principaltoken.DefaultDelegationChain = principaltokenDescDelegationChain.Default.([]string)
	// principaltokenDescRevoked is the schema descriptor for revoked field.
	principaltokenDescRevoked := principaltokenFields[17].Descriptor()
	// principaltoken.DefaultRevoked holds the default value on creation for the revoked field.
	principaltoken.DefaultRevoked = principaltokenDescRevoked.Default.(bool)
	// principaltokenDescCreatedAt is the schema descriptor for created_at field.
	principaltokenDescCreatedAt := principaltokenFields[23].Descriptor()
	// principaltoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	principaltoken.DefaultCreatedAt = principaltokenDescCreatedAt.Default.(func() time.Time)
	// principaltokenDescID is the schema descriptor for id field.
	principaltokenDescID := principaltokenFields[0].Descriptor()
	// principaltoken.DefaultID holds the default value on creation for the id field.
	principaltoken.DefaultID = principaltokenDescID.Default.(func() uuid.UUID)
	refreshtokenMixin := schema.RefreshToken{}.Mixin()
	refreshtokenMixinFields0 := refreshtokenMixin[0].Fields()
	_ = refreshtokenMixinFields0
	refreshtokenFields := schema.RefreshToken{}.Fields()
	_ = refreshtokenFields
	// refreshtokenDescCreatedAt is the schema descriptor for created_at field.
	refreshtokenDescCreatedAt := refreshtokenMixinFields0[1].Descriptor()
	// refreshtoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	refreshtoken.DefaultCreatedAt = refreshtokenDescCreatedAt.Default.(func() time.Time)
	// refreshtokenDescUpdatedAt is the schema descriptor for updated_at field.
	refreshtokenDescUpdatedAt := refreshtokenMixinFields0[2].Descriptor()
	// refreshtoken.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	refreshtoken.DefaultUpdatedAt = refreshtokenDescUpdatedAt.Default.(func() time.Time)
	// refreshtoken.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	refreshtoken.UpdateDefaultUpdatedAt = refreshtokenDescUpdatedAt.UpdateDefault.(func() time.Time)
	// refreshtokenDescToken is the schema descriptor for token field.
	refreshtokenDescToken := refreshtokenFields[1].Descriptor()
	// refreshtoken.TokenValidator is a validator for the "token" field. It is called by the builders before save.
	refreshtoken.TokenValidator = refreshtokenDescToken.Validators[0].(func(string) error)
	// refreshtokenDescFamily is the schema descriptor for family field.
	refreshtokenDescFamily := refreshtokenFields[2].Descriptor()
	// refreshtoken.FamilyValidator is a validator for the "family" field. It is called by the builders before save.
	refreshtoken.FamilyValidator = refreshtokenDescFamily.Validators[0].(func(string) error)
	// refreshtokenDescRevoked is the schema descriptor for revoked field.
	refreshtokenDescRevoked := refreshtokenFields[4].Descriptor()
	// refreshtoken.DefaultRevoked holds the default value on creation for the revoked field.
	refreshtoken.DefaultRevoked = refreshtokenDescRevoked.Default.(bool)
	// refreshtokenDescID is the schema descriptor for id field.
	refreshtokenDescID := refreshtokenMixinFields0[0].Descriptor()
	// refreshtoken.DefaultID holds the default value on creation for the id field.
	refreshtoken.DefaultID = refreshtokenDescID.Default.(func() uuid.UUID)
	seatassignmentMixin := schema.SeatAssignment{}.Mixin()
	seatassignmentMixinFields0 := seatassignmentMixin[0].Fields()
	_ = seatassignmentMixinFields0
	seatassignmentFields := schema.SeatAssignment{}.Fields()
	_ = seatassignmentFields
	// seatassignmentDescAssignedAt is the schema descriptor for assigned_at field.
	seatassignmentDescAssignedAt := seatassignmentMixinFields0[4].Descriptor()
	// seatassignment.DefaultAssignedAt holds the default value on creation for the assigned_at field.
	seatassignment.DefaultAssignedAt = seatassignmentDescAssignedAt.Default.(func() time.Time)
	// seatassignmentDescID is the schema descriptor for id field.
	seatassignmentDescID := seatassignmentMixinFields0[0].Descriptor()
	// seatassignment.DefaultID holds the default value on creation for the id field.
	seatassignment.DefaultID = seatassignmentDescID.Default.(func() uuid.UUID)
	serviceaccountFields := schema.ServiceAccount{}.Fields()
	_ = serviceaccountFields
	// serviceaccountDescName is the schema descriptor for name field.
	serviceaccountDescName := serviceaccountFields[1].Descriptor()
	// serviceaccount.NameValidator is a validator for the "name" field. It is called by the builders before save.
	serviceaccount.NameValidator = func() func(string) error {
		validators := serviceaccountDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// serviceaccountDescDescription is the schema descriptor for description field.
	serviceaccountDescDescription := serviceaccountFields[2].Descriptor()
	// serviceaccount.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	serviceaccount.DescriptionValidator = serviceaccountDescDescription.Validators[0].(func(string) error)
	// serviceaccountDescEmail is the schema descriptor for email field.
	serviceaccountDescEmail := serviceaccountFields[3].Descriptor()
	// serviceaccount.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	serviceaccount.EmailValidator = serviceaccountDescEmail.Validators[0].(func(string) error)
	// serviceaccountDescAllowedScopes is the schema descriptor for allowed_scopes field.
	serviceaccountDescAllowedScopes := serviceaccountFields[6].Descriptor()
	// serviceaccount.DefaultAllowedScopes holds the default value on creation for the allowed_scopes field.
	serviceaccount.DefaultAllowedScopes = serviceaccountDescAllowedScopes.Default.([]string)
	// serviceaccountDescActive is the schema descriptor for active field.
	serviceaccountDescActive := serviceaccountFields[7].Descriptor()
	// serviceaccount.DefaultActive holds the default value on creation for the active field.
	serviceaccount.DefaultActive = serviceaccountDescActive.Default.(bool)
	// serviceaccountDescCreatedAt is the schema descriptor for created_at field.
	serviceaccountDescCreatedAt := serviceaccountFields[9].Descriptor()
	// serviceaccount.DefaultCreatedAt holds the default value on creation for the created_at field.
	serviceaccount.DefaultCreatedAt = serviceaccountDescCreatedAt.Default.(func() time.Time)
	// serviceaccountDescUpdatedAt is the schema descriptor for updated_at field.
	serviceaccountDescUpdatedAt := serviceaccountFields[10].Descriptor()
	// serviceaccount.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	serviceaccount.DefaultUpdatedAt = serviceaccountDescUpdatedAt.Default.(func() time.Time)
	// serviceaccount.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	serviceaccount.UpdateDefaultUpdatedAt = serviceaccountDescUpdatedAt.UpdateDefault.(func() time.Time)
	// serviceaccountDescID is the schema descriptor for id field.
	serviceaccountDescID := serviceaccountFields[0].Descriptor()
	// serviceaccount.DefaultID holds the default value on creation for the id field.
	serviceaccount.DefaultID = serviceaccountDescID.Default.(func() uuid.UUID)
	serviceaccountkeypairFields := schema.ServiceAccountKeyPair{}.Fields()
	_ = serviceaccountkeypairFields
	// serviceaccountkeypairDescKeyID is the schema descriptor for key_id field.
	serviceaccountkeypairDescKeyID := serviceaccountkeypairFields[2].Descriptor()
	// serviceaccountkeypair.KeyIDValidator is a validator for the "key_id" field. It is called by the builders before save.
	serviceaccountkeypair.KeyIDValidator = serviceaccountkeypairDescKeyID.Validators[0].(func(string) error)
	// serviceaccountkeypairDescPublicKeyPem is the schema descriptor for public_key_pem field.
	serviceaccountkeypairDescPublicKeyPem := serviceaccountkeypairFields[5].Descriptor()
	// serviceaccountkeypair.PublicKeyPemValidator is a validator for the "public_key_pem" field. It is called by the builders before save.
	serviceaccountkeypair.PublicKeyPemValidator = serviceaccountkeypairDescPublicKeyPem.Validators[0].(func(string) error)
	// serviceaccountkeypairDescActive is the schema descriptor for active field.
	serviceaccountkeypairDescActive := serviceaccountkeypairFields[7].Descriptor()
	// serviceaccountkeypair.DefaultActive holds the default value on creation for the active field.
	serviceaccountkeypair.DefaultActive = serviceaccountkeypairDescActive.Default.(bool)
	// serviceaccountkeypairDescRevoked is the schema descriptor for revoked field.
	serviceaccountkeypairDescRevoked := serviceaccountkeypairFields[9].Descriptor()
	// serviceaccountkeypair.DefaultRevoked holds the default value on creation for the revoked field.
	serviceaccountkeypair.DefaultRevoked = serviceaccountkeypairDescRevoked.Default.(bool)
	// serviceaccountkeypairDescCreatedAt is the schema descriptor for created_at field.
	serviceaccountkeypairDescCreatedAt := serviceaccountkeypairFields[11].Descriptor()
	// serviceaccountkeypair.DefaultCreatedAt holds the default value on creation for the created_at field.
	serviceaccountkeypair.DefaultCreatedAt = serviceaccountkeypairDescCreatedAt.Default.(func() time.Time)
	// serviceaccountkeypairDescID is the schema descriptor for id field.
	serviceaccountkeypairDescID := serviceaccountkeypairFields[0].Descriptor()
	// serviceaccountkeypair.DefaultID holds the default value on creation for the id field.
	serviceaccountkeypair.DefaultID = serviceaccountkeypairDescID.Default.(func() uuid.UUID)
	serviceprincipalMixin := schema.ServicePrincipal{}.Mixin()
	serviceprincipalMixinFields0 := serviceprincipalMixin[0].Fields()
	_ = serviceprincipalMixinFields0
	serviceprincipalFields := schema.ServicePrincipal{}.Fields()
	_ = serviceprincipalFields
	// serviceprincipalDescCreatedAt is the schema descriptor for created_at field.
	serviceprincipalDescCreatedAt := serviceprincipalMixinFields0[1].Descriptor()
	// serviceprincipal.DefaultCreatedAt holds the default value on creation for the created_at field.
	serviceprincipal.DefaultCreatedAt = serviceprincipalDescCreatedAt.Default.(func() time.Time)
	// serviceprincipalDescUpdatedAt is the schema descriptor for updated_at field.
	serviceprincipalDescUpdatedAt := serviceprincipalMixinFields0[2].Descriptor()
	// serviceprincipal.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	serviceprincipal.DefaultUpdatedAt = serviceprincipalDescUpdatedAt.Default.(func() time.Time)
	// serviceprincipal.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	serviceprincipal.UpdateDefaultUpdatedAt = serviceprincipalDescUpdatedAt.UpdateDefault.(func() time.Time)
	// serviceprincipalDescServiceType is the schema descriptor for service_type field.
	serviceprincipalDescServiceType := serviceprincipalFields[1].Descriptor()
	// serviceprincipal.ServiceTypeValidator is a validator for the "service_type" field. It is called by the builders before save.
	serviceprincipal.ServiceTypeValidator = serviceprincipalDescServiceType.Validators[0].(func(string) error)
	// serviceprincipalDescDescription is the schema descriptor for description field.
	serviceprincipalDescDescription := serviceprincipalFields[2].Descriptor()
	// serviceprincipal.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	serviceprincipal.DescriptionValidator = serviceprincipalDescDescription.Validators[0].(func(string) error)
	// serviceprincipalDescAllowedIps is the schema descriptor for allowed_ips field.
	serviceprincipalDescAllowedIps := serviceprincipalFields[5].Descriptor()
	// serviceprincipal.DefaultAllowedIps holds the default value on creation for the allowed_ips field.
	serviceprincipal.DefaultAllowedIps = serviceprincipalDescAllowedIps.Default.([]string)
	// serviceprincipalDescID is the schema descriptor for id field.
	serviceprincipalDescID := serviceprincipalMixinFields0[0].Descriptor()
	// serviceprincipal.DefaultID holds the default value on creation for the id field.
	serviceprincipal.DefaultID = serviceprincipalDescID.Default.(func() uuid.UUID)
	subscriptionMixin := schema.Subscription{}.Mixin()
	subscriptionMixinFields0 := subscriptionMixin[0].Fields()
	_ = subscriptionMixinFields0
	subscriptionFields := schema.Subscription{}.Fields()
	_ = subscriptionFields
	// subscriptionDescPlanTier is the schema descriptor for plan_tier field.
	subscriptionDescPlanTier := subscriptionMixinFields0[2].Descriptor()
	// subscription.DefaultPlanTier holds the default value on creation for the plan_tier field.
	subscription.DefaultPlanTier = subscriptionDescPlanTier.Default.(string)
	// subscription.PlanTierValidator is a validator for the "plan_tier" field. It is called by the builders before save.
	subscription.PlanTierValidator = subscriptionDescPlanTier.Validators[0].(func(string) error)
	// subscriptionDescCurrentPeriodStart is the schema descriptor for current_period_start field.
	subscriptionDescCurrentPeriodStart := subscriptionMixinFields0[4].Descriptor()
	// subscription.DefaultCurrentPeriodStart holds the default value on creation for the current_period_start field.
	subscription.DefaultCurrentPeriodStart = subscriptionDescCurrentPeriodStart.Default.(func() time.Time)
	// subscriptionDescCancelAtPeriodEnd is the schema descriptor for cancel_at_period_end field.
	subscriptionDescCancelAtPeriodEnd := subscriptionMixinFields0[8].Descriptor()
	// subscription.DefaultCancelAtPeriodEnd holds the default value on creation for the cancel_at_period_end field.
	subscription.DefaultCancelAtPeriodEnd = subscriptionDescCancelAtPeriodEnd.Default.(bool)
	// subscriptionDescCreatedAt is the schema descriptor for created_at field.
	subscriptionDescCreatedAt := subscriptionMixinFields0[9].Descriptor()
	// subscription.DefaultCreatedAt holds the default value on creation for the created_at field.
	subscription.DefaultCreatedAt = subscriptionDescCreatedAt.Default.(func() time.Time)
	// subscriptionDescUpdatedAt is the schema descriptor for updated_at field.
	subscriptionDescUpdatedAt := subscriptionMixinFields0[10].Descriptor()
	// subscription.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	subscription.DefaultUpdatedAt = subscriptionDescUpdatedAt.Default.(func() time.Time)
	// subscription.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	subscription.UpdateDefaultUpdatedAt = subscriptionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// subscriptionDescID is the schema descriptor for id field.
	subscriptionDescID := subscriptionMixinFields0[0].Descriptor()
	// subscription.DefaultID holds the default value on creation for the id field.
	subscription.DefaultID = subscriptionDescID.Default.(func() uuid.UUID)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[2].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[0].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescIsPlatformAdmin is the schema descriptor for is_platform_admin field.
	userDescIsPlatformAdmin := userFields[4].Descriptor()
	// user.DefaultIsPlatformAdmin holds the default value on creation for the is_platform_admin field.
	user.DefaultIsPlatformAdmin = userDescIsPlatformAdmin.Default.(bool)
	// userDescActive is the schema descriptor for active field.
	userDescActive := userFields[5].Descriptor()
	// user.DefaultActive holds the default value on creation for the active field.
	user.DefaultActive = userDescActive.Default.(bool)
	// userDescID is the schema descriptor for id field.
	userDescID := userMixinFields0[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
