// Code generated by ent, DO NOT EDIT.

package loginsession

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/plexusone/systemforge/identity/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldLTE(FieldID, id))
}

// TokenHash applies equality check predicate on the "token_hash" field. It's identical to TokenHashEQ.
func TokenHash(v string) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldEQ(FieldTokenHash, v))
}

// PrincipalID applies equality check predicate on the "principal_id" field. It's identical to PrincipalIDEQ.
func PrincipalID(v uuid.UUID) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldEQ(FieldPrincipalID, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldEQ(FieldProvider, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldEQ(FieldCreatedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldEQ(FieldExpiresAt, v))
}

// TokenHashEQ applies the EQ predicate on the "token_hash" field.
func TokenHashEQ(v string) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldEQ(FieldTokenHash, v))
}

// TokenHashNEQ applies the NEQ predicate on the "token_hash" field.
func TokenHashNEQ(v string) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldNEQ(FieldTokenHash, v))
}

// TokenHashIn applies the In predicate on the "token_hash" field.
func TokenHashIn(vs ...string) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldIn(FieldTokenHash, vs...))
}

// TokenHashNotIn applies the NotIn predicate on the "token_hash" field.
func TokenHashNotIn(vs ...string) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldNotIn(FieldTokenHash, vs...))
}

// TokenHashGT applies the GT predicate on the "token_hash" field.
func TokenHashGT(v string) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldGT(FieldTokenHash, v))
}

// TokenHashGTE applies the GTE predicate on the "token_hash" field.
func TokenHashGTE(v string) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldGTE(FieldTokenHash, v))
}

// TokenHashLT applies the LT predicate on the "token_hash" field.
func TokenHashLT(v string) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldLT(FieldTokenHash, v))
}

// TokenHashLTE applies the LTE predicate on the "token_hash" field.
func TokenHashLTE(v string) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldLTE(FieldTokenHash, v))
}

// TokenHashContains applies the Contains predicate on the "token_hash" field.
func TokenHashContains(v string) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldContains(FieldTokenHash, v))
}

// TokenHashHasPrefix applies the HasPrefix predicate on the "token_hash" field.
func TokenHashHasPrefix(v string) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldHasPrefix(FieldTokenHash, v))
}

// TokenHashHasSuffix applies the HasSuffix predicate on the "token_hash" field.
func TokenHashHasSuffix(v string) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldHasSuffix(FieldTokenHash, v))
}

// TokenHashEqualFold applies the EqualFold predicate on the "token_hash" field.
func TokenHashEqualFold(v string) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldEqualFold(FieldTokenHash, v))
}

// TokenHashContainsFold applies the ContainsFold predicate on the "token_hash" field.
func TokenHashContainsFold(v string) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldContainsFold(FieldTokenHash, v))
}

// PrincipalIDEQ applies the EQ predicate on the "principal_id" field.
func PrincipalIDEQ(v uuid.UUID) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldEQ(FieldPrincipalID, v))
}

// PrincipalIDNEQ applies the NEQ predicate on the "principal_id" field.
func PrincipalIDNEQ(v uuid.UUID) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldNEQ(FieldPrincipalID, v))
}

// PrincipalIDIn applies the In predicate on the "principal_id" field.
func PrincipalIDIn(vs ...uuid.UUID) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldIn(FieldPrincipalID, vs...))
}

// PrincipalIDNotIn applies the NotIn predicate on the "principal_id" field.
func PrincipalIDNotIn(vs ...uuid.UUID) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldNotIn(FieldPrincipalID, vs...))
}

// PrincipalIDGT applies the GT predicate on the "principal_id" field.
func PrincipalIDGT(v uuid.UUID) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldGT(FieldPrincipalID, v))
}

// PrincipalIDGTE applies the GTE predicate on the "principal_id" field.
func PrincipalIDGTE(v uuid.UUID) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldGTE(FieldPrincipalID, v))
}

// PrincipalIDLT applies the LT predicate on the "principal_id" field.
func PrincipalIDLT(v uuid.UUID) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldLT(FieldPrincipalID, v))
}

// PrincipalIDLTE applies the LTE predicate on the "principal_id" field.
func PrincipalIDLTE(v uuid.UUID) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldLTE(FieldPrincipalID, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderIsNil applies the IsNil predicate on the "provider" field.
func ProviderIsNil() predicate.LoginSession {
	return predicate.LoginSession(sql.FieldIsNull(FieldProvider))
}

// ProviderNotNil applies the NotNil predicate on the "provider" field.
func ProviderNotNil() predicate.LoginSession {
	return predicate.LoginSession(sql.FieldNotNull(FieldProvider))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldContainsFold(FieldProvider, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldLTE(FieldCreatedAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.LoginSession {
	return predicate.LoginSession(sql.FieldLTE(FieldExpiresAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LoginSession) predicate.LoginSession {
	return predicate.LoginSession(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LoginSession) predicate.LoginSession {
	return predicate.LoginSession(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LoginSession) predicate.LoginSession {
	return predicate.LoginSession(sql.NotPredicates(p))
}
