package schema

// UserSchema returns the SCIM User schema definition.
func UserSchema() Schema {
	return Schema{
		ID:          URIUser,
		Name:        "User",
		Description: "User Account",
		Attributes:  userAttributes(),
		Meta: &SchemaMeta{
			ResourceType: "Schema",
		},
	}
}

// userAttributes returns the attribute definitions for the User schema.
func userAttributes() []Attribute {
	return []Attribute{
		{
			Name:        "userName",
			Type:        TypeString,
			MultiValued: false,
			Description: "Unique identifier for the User, typically used by the user to directly authenticate to the service provider.",
			Required:    true,
			CaseExact:   false,
			Mutability:  MutabilityReadWrite,
			Returned:    ReturnedDefault,
			Uniqueness:  UniquenessServer,
		},
		{
			Name:        "name",
			Type:        TypeComplex,
			MultiValued: false,
			Description: "The components of the user's real name.",
			Required:    false,
			Mutability:  MutabilityReadWrite,
			Returned:    ReturnedDefault,
			Uniqueness:  UniquenessNone,
			SubAttributes: []Attribute{
				{
					Name:        "formatted",
					Type:        TypeString,
					MultiValued: false,
					Description: "The full name, including all middle names, titles, and suffixes as appropriate.",
					Required:    false,
					Mutability:  MutabilityReadWrite,
					Returned:    ReturnedDefault,
					Uniqueness:  UniquenessNone,
				},
				{
					Name:        "familyName",
					Type:        TypeString,
					MultiValued: false,
					Description: "The family name of the User, or last name.",
					Required:    false,
					Mutability:  MutabilityReadWrite,
					Returned:    ReturnedDefault,
					Uniqueness:  UniquenessNone,
				},
				{
					Name:        "givenName",
					Type:        TypeString,
					MultiValued: false,
					Description: "The given name of the User, or first name.",
					Required:    false,
					Mutability:  MutabilityReadWrite,
					Returned:    ReturnedDefault,
					Uniqueness:  UniquenessNone,
				},
				{
					Name:        "middleName",
					Type:        TypeString,
					MultiValued: false,
					Description: "The middle name(s) of the User.",
					Required:    false,
					Mutability:  MutabilityReadWrite,
					Returned:    ReturnedDefault,
					Uniqueness:  UniquenessNone,
				},
				{
					Name:        "honorificPrefix",
					Type:        TypeString,
					MultiValued: false,
					Description: "The honorific prefix(es) of the User, or title.",
					Required:    false,
					Mutability:  MutabilityReadWrite,
					Returned:    ReturnedDefault,
					Uniqueness:  UniquenessNone,
				},
				{
					Name:        "honorificSuffix",
					Type:        TypeString,
					MultiValued: false,
					Description: "The honorific suffix(es) of the User.",
					Required:    false,
					Mutability:  MutabilityReadWrite,
					Returned:    ReturnedDefault,
					Uniqueness:  UniquenessNone,
				},
			},
		},
		{
			Name:        "displayName",
			Type:        TypeString,
			MultiValued: false,
			Description: "The name of the User, suitable for display to end-users.",
			Required:    false,
			Mutability:  MutabilityReadWrite,
			Returned:    ReturnedDefault,
			Uniqueness:  UniquenessNone,
		},
		{
			Name:        "nickName",
			Type:        TypeString,
			MultiValued: false,
			Description: "The casual way to address the user in real life.",
			Required:    false,
			Mutability:  MutabilityReadWrite,
			Returned:    ReturnedDefault,
			Uniqueness:  UniquenessNone,
		},
		{
			Name:           "profileUrl",
			Type:           TypeReference,
			MultiValued:    false,
			Description:    "A fully qualified URL pointing to a page representing the User's online profile.",
			Required:       false,
			Mutability:     MutabilityReadWrite,
			Returned:       ReturnedDefault,
			Uniqueness:     UniquenessNone,
			ReferenceTypes: []string{"external"},
		},
		{
			Name:        "title",
			Type:        TypeString,
			MultiValued: false,
			Description: "The user's title, such as 'Vice President'.",
			Required:    false,
			Mutability:  MutabilityReadWrite,
			Returned:    ReturnedDefault,
			Uniqueness:  UniquenessNone,
		},
		{
			Name:        "userType",
			Type:        TypeString,
			MultiValued: false,
			Description: "Used to identify the relationship between the organization and the user.",
			Required:    false,
			Mutability:  MutabilityReadWrite,
			Returned:    ReturnedDefault,
			Uniqueness:  UniquenessNone,
		},
		{
			Name:        "preferredLanguage",
			Type:        TypeString,
			MultiValued: false,
			Description: "Indicates the User's preferred written or spoken language.",
			Required:    false,
			Mutability:  MutabilityReadWrite,
			Returned:    ReturnedDefault,
			Uniqueness:  UniquenessNone,
		},
		{
			Name:        "locale",
			Type:        TypeString,
			MultiValued: false,
			Description: "Used to indicate the User's default location for purposes of localizing items.",
			Required:    false,
			Mutability:  MutabilityReadWrite,
			Returned:    ReturnedDefault,
			Uniqueness:  UniquenessNone,
		},
		{
			Name:        "timezone",
			Type:        TypeString,
			MultiValued: false,
			Description: "The User's time zone in the 'Olson' time zone database format.",
			Required:    false,
			Mutability:  MutabilityReadWrite,
			Returned:    ReturnedDefault,
			Uniqueness:  UniquenessNone,
		},
		{
			Name:        "active",
			Type:        TypeBoolean,
			MultiValued: false,
			Description: "A Boolean value indicating the User's administrative status.",
			Required:    false,
			Mutability:  MutabilityReadWrite,
			Returned:    ReturnedDefault,
			Uniqueness:  UniquenessNone,
		},
		{
			Name:        "password",
			Type:        TypeString,
			MultiValued: false,
			Description: "The User's cleartext password.",
			Required:    false,
			Mutability:  MutabilityWriteOnly,
			Returned:    ReturnedNever,
			Uniqueness:  UniquenessNone,
		},
		{
			Name:        "emails",
			Type:        TypeComplex,
			MultiValued: true,
			Description: "Email addresses for the user.",
			Required:    false,
			Mutability:  MutabilityReadWrite,
			Returned:    ReturnedDefault,
			Uniqueness:  UniquenessNone,
			SubAttributes: []Attribute{
				{
					Name:        "value",
					Type:        TypeString,
					MultiValued: false,
					Description: "Email address value.",
					Required:    false,
					Mutability:  MutabilityReadWrite,
					Returned:    ReturnedDefault,
					Uniqueness:  UniquenessNone,
				},
				{
					Name:        "display",
					Type:        TypeString,
					MultiValued: false,
					Description: "A human-readable name, primarily used for display purposes.",
					Required:    false,
					Mutability:  MutabilityReadWrite,
					Returned:    ReturnedDefault,
					Uniqueness:  UniquenessNone,
				},
				{
					Name:            "type",
					Type:            TypeString,
					MultiValued:     false,
					Description:     "A label indicating the attribute's function.",
					Required:        false,
					Mutability:      MutabilityReadWrite,
					Returned:        ReturnedDefault,
					Uniqueness:      UniquenessNone,
					CanonicalValues: []string{"work", "home", "other"},
				},
				{
					Name:        "primary",
					Type:        TypeBoolean,
					MultiValued: false,
					Description: "A Boolean value indicating the 'primary' or preferred attribute value.",
					Required:    false,
					Mutability:  MutabilityReadWrite,
					Returned:    ReturnedDefault,
					Uniqueness:  UniquenessNone,
				},
			},
		},
		{
			Name:        "phoneNumbers",
			Type:        TypeComplex,
			MultiValued: true,
			Description: "Phone numbers for the User.",
			Required:    false,
			Mutability:  MutabilityReadWrite,
			Returned:    ReturnedDefault,
			Uniqueness:  UniquenessNone,
			SubAttributes: []Attribute{
				{
					Name:        "value",
					Type:        TypeString,
					MultiValued: false,
					Description: "Phone number value.",
					Required:    false,
					Mutability:  MutabilityReadWrite,
					Returned:    ReturnedDefault,
					Uniqueness:  UniquenessNone,
				},
				{
					Name:        "display",
					Type:        TypeString,
					MultiValued: false,
					Description: "A human-readable name, primarily used for display purposes.",
					Required:    false,
					Mutability:  MutabilityReadWrite,
					Returned:    ReturnedDefault,
					Uniqueness:  UniquenessNone,
				},
				{
					Name:            "type",
					Type:            TypeString,
					MultiValued:     false,
					Description:     "A label indicating the attribute's function.",
					Required:        false,
					Mutability:      MutabilityReadWrite,
					Returned:        ReturnedDefault,
					Uniqueness:      UniquenessNone,
					CanonicalValues: []string{"work", "home", "mobile", "fax", "pager", "other"},
				},
				{
					Name:        "primary",
					Type:        TypeBoolean,
					MultiValued: false,
					Description: "A Boolean value indicating the 'primary' or preferred attribute value.",
					Required:    false,
					Mutability:  MutabilityReadWrite,
					Returned:    ReturnedDefault,
					Uniqueness:  UniquenessNone,
				},
			},
		},
		{
			Name:        "photos",
			Type:        TypeComplex,
			MultiValued: true,
			Description: "URLs of photos of the User.",
			Required:    false,
			Mutability:  MutabilityReadWrite,
			Returned:    ReturnedDefault,
			Uniqueness:  UniquenessNone,
			SubAttributes: []Attribute{
				{
					Name:           "value",
					Type:           TypeReference,
					MultiValued:    false,
					Description:    "URL of a photo of the User.",
					Required:       false,
					Mutability:     MutabilityReadWrite,
					Returned:       ReturnedDefault,
					Uniqueness:     UniquenessNone,
					ReferenceTypes: []string{"external"},
				},
				{
					Name:            "type",
					Type:            TypeString,
					MultiValued:     false,
					Description:     "A label indicating the attribute's function.",
					Required:        false,
					Mutability:      MutabilityReadWrite,
					Returned:        ReturnedDefault,
					Uniqueness:      UniquenessNone,
					CanonicalValues: []string{"photo", "thumbnail"},
				},
				{
					Name:        "primary",
					Type:        TypeBoolean,
					MultiValued: false,
					Description: "A Boolean value indicating the 'primary' or preferred attribute value.",
					Required:    false,
					Mutability:  MutabilityReadWrite,
					Returned:    ReturnedDefault,
					Uniqueness:  UniquenessNone,
				},
			},
		},
		{
			Name:        "groups",
			Type:        TypeComplex,
			MultiValued: true,
			Description: "A list of groups to which the user belongs.",
			Required:    false,
			Mutability:  MutabilityReadOnly,
			Returned:    ReturnedDefault,
			Uniqueness:  UniquenessNone,
			SubAttributes: []Attribute{
				{
					Name:        "value",
					Type:        TypeString,
					MultiValued: false,
					Description: "The identifier of the User's group.",
					Required:    false,
					Mutability:  MutabilityReadOnly,
					Returned:    ReturnedDefault,
					Uniqueness:  UniquenessNone,
				},
				{
					Name:           "$ref",
					Type:           TypeReference,
					MultiValued:    false,
					Description:    "The URI of the corresponding 'Group' resource.",
					Required:       false,
					Mutability:     MutabilityReadOnly,
					Returned:       ReturnedDefault,
					Uniqueness:     UniquenessNone,
					ReferenceTypes: []string{"User", "Group"},
				},
				{
					Name:        "display",
					Type:        TypeString,
					MultiValued: false,
					Description: "A human-readable name, primarily used for display purposes.",
					Required:    false,
					Mutability:  MutabilityReadOnly,
					Returned:    ReturnedDefault,
					Uniqueness:  UniquenessNone,
				},
				{
					Name:            "type",
					Type:            TypeString,
					MultiValued:     false,
					Description:     "A label indicating the attribute's function.",
					Required:        false,
					Mutability:      MutabilityReadOnly,
					Returned:        ReturnedDefault,
					Uniqueness:      UniquenessNone,
					CanonicalValues: []string{"direct", "indirect"},
				},
			},
		},
		{
			Name:          "entitlements",
			Type:          TypeComplex,
			MultiValued:   true,
			Description:   "A list of entitlements for the User.",
			Required:      false,
			Mutability:    MutabilityReadWrite,
			Returned:      ReturnedDefault,
			Uniqueness:    UniquenessNone,
			SubAttributes: multiValueSubAttributes(),
		},
		{
			Name:          "roles",
			Type:          TypeComplex,
			MultiValued:   true,
			Description:   "A list of roles for the User.",
			Required:      false,
			Mutability:    MutabilityReadWrite,
			Returned:      ReturnedDefault,
			Uniqueness:    UniquenessNone,
			SubAttributes: multiValueSubAttributes(),
		},
		{
			Name:        "x509Certificates",
			Type:        TypeComplex,
			MultiValued: true,
			Description: "A list of certificates issued to the User.",
			Required:    false,
			Mutability:  MutabilityReadWrite,
			Returned:    ReturnedDefault,
			Uniqueness:  UniquenessNone,
			SubAttributes: []Attribute{
				{
					Name:        "value",
					Type:        TypeBinary,
					MultiValued: false,
					Description: "The value of an X.509 certificate.",
					Required:    false,
					Mutability:  MutabilityReadWrite,
					Returned:    ReturnedDefault,
					Uniqueness:  UniquenessNone,
				},
				{
					Name:        "display",
					Type:        TypeString,
					MultiValued: false,
					Description: "A human-readable name, primarily used for display purposes.",
					Required:    false,
					Mutability:  MutabilityReadWrite,
					Returned:    ReturnedDefault,
					Uniqueness:  UniquenessNone,
				},
				{
					Name:        "type",
					Type:        TypeString,
					MultiValued: false,
					Description: "A label indicating the attribute's function.",
					Required:    false,
					Mutability:  MutabilityReadWrite,
					Returned:    ReturnedDefault,
					Uniqueness:  UniquenessNone,
				},
				{
					Name:        "primary",
					Type:        TypeBoolean,
					MultiValued: false,
					Description: "A Boolean value indicating the 'primary' or preferred attribute value.",
					Required:    false,
					Mutability:  MutabilityReadWrite,
					Returned:    ReturnedDefault,
					Uniqueness:  UniquenessNone,
				},
			},
		},
	}
}

// multiValueSubAttributes returns the standard sub-attributes for multi-valued attributes.
func multiValueSubAttributes() []Attribute {
	return []Attribute{
		{
			Name:        "value",
			Type:        TypeString,
			MultiValued: false,
			Description: "The value of the attribute.",
			Required:    false,
			Mutability:  MutabilityReadWrite,
			Returned:    ReturnedDefault,
			Uniqueness:  UniquenessNone,
		},
		{
			Name:        "display",
			Type:        TypeString,
			MultiValued: false,
			Description: "A human-readable name, primarily used for display purposes.",
			Required:    false,
			Mutability:  MutabilityReadWrite,
			Returned:    ReturnedDefault,
			Uniqueness:  UniquenessNone,
		},
		{
			Name:        "type",
			Type:        TypeString,
			MultiValued: false,
			Description: "A label indicating the attribute's function.",
			Required:    false,
			Mutability:  MutabilityReadWrite,
			Returned:    ReturnedDefault,
			Uniqueness:  UniquenessNone,
		},
		{
			Name:        "primary",
			Type:        TypeBoolean,
			MultiValued: false,
			Description: "A Boolean value indicating the 'primary' or preferred attribute value.",
			Required:    false,
			Mutability:  MutabilityReadWrite,
			Returned:    ReturnedDefault,
			Uniqueness:  UniquenessNone,
		},
	}
}

// UserResourceType returns the SCIM User resource type definition.
func UserResourceType(baseURL string) ResourceType {
	return ResourceType{
		ID:          "User",
		Name:        "User",
		Description: "User Account",
		Endpoint:    "/Users",
		Schema:      URIUser,
		SchemaExtensions: []SchemaExtension{
			{
				Schema:   URIEnterpriseUser,
				Required: false,
			},
		},
		Meta: &ResourceTypeMeta{
			ResourceType: "ResourceType",
			Location:     baseURL + "/ResourceTypes/User",
		},
	}
}
