// Code generated by ent, DO NOT EDIT.

package seatassignment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the seatassignment type in the database.
	Label = "seat_assignment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLicenseID holds the string denoting the license_id field in the database.
	FieldLicenseID = "license_id"
	// FieldPrincipalID holds the string denoting the principal_id field in the database.
	FieldPrincipalID = "principal_id"
	// FieldAssignedBy holds the string denoting the assigned_by field in the database.
	FieldAssignedBy = "assigned_by"
	// FieldAssignedAt holds the string denoting the assigned_at field in the database.
	FieldAssignedAt = "assigned_at"
	// EdgeLicense holds the string denoting the license edge name in mutations.
	EdgeLicense = "license"
	// EdgePrincipal holds the string denoting the principal edge name in mutations.
	EdgePrincipal = "principal"
	// EdgeAssigner holds the string denoting the assigner edge name in mutations.
	EdgeAssigner = "assigner"
	// Table holds the table name of the seatassignment in the database.
	Table = "sf_seat_assignments"
	// LicenseTable is the table that holds the license relation/edge.
	LicenseTable = "sf_seat_assignments"
	// LicenseInverseTable is the table name for the License entity.
	// It exists in this package in order to avoid circular dependency with the "license" package.
	LicenseInverseTable = "sf_licenses"
	// LicenseColumn is the table column denoting the license relation/edge.
	LicenseColumn = "license_id"
	// PrincipalTable is the table that holds the principal relation/edge.
	PrincipalTable = "sf_seat_assignments"
	// PrincipalInverseTable is the table name for the Principal entity.
	// It exists in this package in order to avoid circular dependency with the "principal" package.
	PrincipalInverseTable = "sf_principals"
	// PrincipalColumn is the table column denoting the principal relation/edge.
	PrincipalColumn = "principal_id"
	// AssignerTable is the table that holds the assigner relation/edge.
	AssignerTable = "sf_seat_assignments"
	// AssignerInverseTable is the table name for the Principal entity.
	// It exists in this package in order to avoid circular dependency with the "principal" package.
	AssignerInverseTable = "sf_principals"
	// AssignerColumn is the table column denoting the assigner relation/edge.
	AssignerColumn = "assigned_by"
)

// Columns holds all SQL columns for seatassignment fields.
var Columns = []string{
	FieldID,
	FieldLicenseID,
	FieldPrincipalID,
	FieldAssignedBy,
	FieldAssignedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultAssignedAt holds the default value on creation for the "assigned_at" field.
	DefaultAssignedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the SeatAssignment queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByLicenseID orders the results by the license_id field.
func ByLicenseID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLicenseID, opts...).ToFunc()
}

// ByPrincipalID orders the results by the principal_id field.
func ByPrincipalID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrincipalID, opts...).ToFunc()
}

// ByAssignedBy orders the results by the assigned_by field.
func ByAssignedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAssignedBy, opts...).ToFunc()
}

// ByAssignedAt orders the results by the assigned_at field.
func ByAssignedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAssignedAt, opts...).ToFunc()
}

// ByLicenseField orders the results by license field.
func ByLicenseField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLicenseStep(), sql.OrderByField(field, opts...))
	}
}

// ByPrincipalField orders the results by principal field.
func ByPrincipalField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPrincipalStep(), sql.OrderByField(field, opts...))
	}
}

// ByAssignerField orders the results by assigner field.
func ByAssignerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAssignerStep(), sql.OrderByField(field, opts...))
	}
}
func newLicenseStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LicenseInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, LicenseTable, LicenseColumn),
	)
}
func newPrincipalStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PrincipalInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PrincipalTable, PrincipalColumn),
	)
}
func newAssignerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AssignerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AssignerTable, AssignerColumn),
	)
}
